import 'package:json_annotation/json_annotation.dart';
import 'package:cloud_firestore_odm/cloud_firestore_odm.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
part 'configurations.g.dart';

@JsonSerializable()
@Collection<Configurations>('configurations')
class Configurations {
  final int? id;
  final String? taxType;
  final double? taxPercentage;
  final int? businessId;
  final int? branchId;

  Configurations({
    this.id,
    this.taxType,
    this.taxPercentage,
    this.businessId,
    this.branchId,
  });
  // From JSON method generated by json_serializable
  factory Configurations.fromJson(Map<String, dynamic> json) =>
      _$ConfigurationsFromJson(json);

  // To JSON method generated by json_serializable
  Map<String, dynamic> toJson() => _$ConfigurationsToJson(this);
}

final configurationsRef = ConfigurationsCollectionReference();
