import 'package:flipper_models/isar_models.dart';

final List<CollectionSchema> models = [
  ITransactionSchema,
  IBusinessSchema,
  IBranchSchema,
  TransactionItemSchema,
  ProductSchema,
  VariantSchema,
  ProfileSchema,
  SubscriptionSchema,
  PointssSchema,
  StockSchema,
  FeatureSchema,
  VoucherSchema,
  PColorSchema,
  CategorySchema,
  IUnitSchema,
  SettingSchema,
  DiscountSchema,
  CustomerSchema,
  IPinSchema,
  ReceiptSchema,
  DrawersSchema,
  IITenantSchema,
  IPermissionSchema,
  ICounterSchema,
  TokenSchema,
  SocialSchema,
  IConversationSchema,
  DeviceSchema,
  FavoriteSchema,
  EBMSchema,
  UserActivitySchema,
  SyncRecordSchema
];
