import 'package:flipper_models/isar_models.dart';

const models = [
  ITransactionSchema,
  BusinessSchema,
  BranchSchema,
  TransactionItemSchema,
  ProductSchema,
  VariantSchema,
  ProfileSchema,
  SubscriptionSchema,
  PointssSchema,
  StockSchema,
  FeatureSchema,
  VoucherSchema,
  PColorSchema,
  CategorySchema,
  IUnitSchema,
  SettingSchema,
  DiscountSchema,
  CustomerSchema,
  PinSchema,
  ReceiptSchema,
  DrawersSchema,
  ITenantSchema,
  PermissionSchema,
  CounterSchema,
  TokenSchema,
  SocialSchema,
  ConversationSchema,
  DeviceSchema,
  FavoriteSchema,
  EBMSchema,
  UserActivitySchema,
  SyncRecordSchema
];
