import "realm_model_export.dart";

final realmModels = [
  Variant.schema,
  Product.schema,
  Stock.schema,
  Customer.schema,
  Receipt.schema,
  IUnit.schema,
  Pin.schema,
  Category.schema,
  Tenant.schema,
  PColor.schema,
  Device.schema,
  Conversation.schema,
  Counter.schema,
  Favorite.schema,
  EBM.schema,
  Drawers.schema,
  TransactionItem.schema,
  ITransaction.schema,
  Discount.schema,
  LPermission.schema,
  Setting.schema,
  Voucher.schema,
  Token.schema,
];
