// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'purchase.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Purchase _$PurchaseFromJson(Map<String, dynamic> json) => Purchase(
      id: (json['id'] as num?)?.toInt(),
      itemIds:
          (json['itemIds'] as List<dynamic>).map((e) => e as String).toList(),
      createdAt: DateTime.parse(json['createdAt'] as String),
      action: json['action'] as String,
      lastTouched: json['lastTouched'] == null
          ? null
          : DateTime.parse(json['lastTouched'] as String),
      tin: json['tin'] as String?,
      bhfId: json['bhfId'] as String?,
      invcNo: (json['invcNo'] as num?)?.toInt(),
      orgInvcNo: (json['orgInvcNo'] as num?)?.toInt(),
      spplrTin: json['spplrTin'] as String?,
      spplrBhfId: json['spplrBhfId'] as String?,
      spplrNm: json['spplrNm'] as String?,
      spplrInvcNo: json['spplrInvcNo'] as String?,
      regTyCd: json['regTyCd'] as String?,
      pchsTyCd: json['pchsTyCd'] as String?,
      rcptTyCd: json['rcptTyCd'] as String?,
      pmtTyCd: json['pmtTyCd'] as String?,
      pchsSttsCd: json['pchsSttsCd'] as String?,
      cfmDt: json['cfmDt'] as String?,
      pchsDt: json['pchsDt'] as String?,
      wrhsDt: json['wrhsDt'] as String?,
      cnclReqDt: json['cnclReqDt'] as String?,
      cnclDt: json['cnclDt'] as String?,
      rfdDt: json['rfdDt'] as String?,
      totItemCnt: (json['totItemCnt'] as num?)?.toInt(),
      taxblAmtA: (json['taxblAmtA'] as num?)?.toDouble(),
      taxblAmtB: (json['taxblAmtB'] as num?)?.toDouble(),
      taxblAmtC: (json['taxblAmtC'] as num?)?.toDouble(),
      taxblAmtD: (json['taxblAmtD'] as num?)?.toDouble(),
      taxRtA: (json['taxRtA'] as num?)?.toDouble(),
      taxRtB: (json['taxRtB'] as num?)?.toDouble(),
      taxRtC: (json['taxRtC'] as num?)?.toDouble(),
      taxRtD: (json['taxRtD'] as num?)?.toDouble(),
      taxAmtA: (json['taxAmtA'] as num?)?.toDouble(),
      taxAmtB: (json['taxAmtB'] as num?)?.toDouble(),
      taxAmtC: (json['taxAmtC'] as num?)?.toDouble(),
      taxAmtD: (json['taxAmtD'] as num?)?.toDouble(),
      totTaxblAmt: (json['totTaxblAmt'] as num?)?.toDouble(),
      totTaxAmt: (json['totTaxAmt'] as num?)?.toDouble(),
      totAmt: (json['totAmt'] as num?)?.toDouble(),
      remark: json['remark'] as String?,
      modrId: (json['modrId'] as num?)?.toInt(),
      modrNm: json['modrNm'] as String?,
      regrId: (json['regrId'] as num?)?.toInt(),
    )..deletedAt = json['deletedAt'] == null
        ? null
        : DateTime.parse(json['deletedAt'] as String);

Map<String, dynamic> _$PurchaseToJson(Purchase instance) => <String, dynamic>{
      'deletedAt': instance.deletedAt?.toIso8601String(),
      'id': instance.id,
      'itemIds': instance.itemIds,
      'lastTouched': instance.lastTouched?.toIso8601String(),
      'createdAt': instance.createdAt.toIso8601String(),
      'action': instance.action,
      'tin': instance.tin,
      'bhfId': instance.bhfId,
      'invcNo': instance.invcNo,
      'orgInvcNo': instance.orgInvcNo,
      'spplrTin': instance.spplrTin,
      'spplrBhfId': instance.spplrBhfId,
      'spplrNm': instance.spplrNm,
      'spplrInvcNo': instance.spplrInvcNo,
      'regTyCd': instance.regTyCd,
      'pchsTyCd': instance.pchsTyCd,
      'rcptTyCd': instance.rcptTyCd,
      'pmtTyCd': instance.pmtTyCd,
      'pchsSttsCd': instance.pchsSttsCd,
      'cfmDt': instance.cfmDt,
      'pchsDt': instance.pchsDt,
      'wrhsDt': instance.wrhsDt,
      'cnclReqDt': instance.cnclReqDt,
      'cnclDt': instance.cnclDt,
      'rfdDt': instance.rfdDt,
      'totItemCnt': instance.totItemCnt,
      'taxblAmtA': instance.taxblAmtA,
      'taxblAmtB': instance.taxblAmtB,
      'taxblAmtC': instance.taxblAmtC,
      'taxblAmtD': instance.taxblAmtD,
      'taxRtA': instance.taxRtA,
      'taxRtB': instance.taxRtB,
      'taxRtC': instance.taxRtC,
      'taxRtD': instance.taxRtD,
      'taxAmtA': instance.taxAmtA,
      'taxAmtB': instance.taxAmtB,
      'taxAmtC': instance.taxAmtC,
      'taxAmtD': instance.taxAmtD,
      'totTaxblAmt': instance.totTaxblAmt,
      'totTaxAmt': instance.totTaxAmt,
      'totAmt': instance.totAmt,
      'remark': instance.remark,
      'modrId': instance.modrId,
      'modrNm': instance.modrNm,
      'regrId': instance.regrId,
    };
