// GENERATED CODE EDIT WITH CAUTION
// THIS FILE **WILL NOT** BE REGENERATED
// This file should be version controlled and can be manually edited.
part of 'schema.g.dart';

// While migrations are intelligently created, the difference between some commands, such as
// DropTable vs. RenameTable, cannot be determined. For this reason, please review migrations after
// they are created to ensure the correct inference was made.

// The migration version must **always** mirror the file name

const List<MigrationCommand> _migration_20241128141446_up = [
  InsertTable('Category'),
  InsertTable('UnversalProduct'),
  InsertTable('ITransaction'),
  InsertTable('Configurations'),
  InsertTable('PColor'),
  InsertTable('Device'),
  InsertTable('Favorite'),
  InsertTable('Setting'),
  InsertTable('Tenant'),
  InsertTable('Pin'),
  InsertTable('Access'),
  InsertTable('Customer'),
  InsertTable('Report'),
  InsertTable('Business'),
  InsertTable('SKU'),
  InsertTable('IUnit'),
  InsertTable('Location'),
  InsertTable('Receipt'),
  InsertTable('Drawers'),
  InsertColumn('id', Column.integer, onTable: 'Category', unique: true),
  InsertColumn('active', Column.boolean, onTable: 'Category'),
  InsertColumn('focused', Column.boolean, onTable: 'Category'),
  InsertColumn('name', Column.varchar, onTable: 'Category'),
  InsertColumn('branch_id', Column.integer, onTable: 'Category'),
  InsertColumn('deleted_at', Column.datetime, onTable: 'Category'),
  InsertColumn('last_touched', Column.datetime, onTable: 'Category'),
  InsertColumn('id', Column.integer, onTable: 'UnversalProduct', unique: true),
  InsertColumn('item_cls_cd', Column.varchar, onTable: 'UnversalProduct'),
  InsertColumn('item_cls_nm', Column.varchar, onTable: 'UnversalProduct'),
  InsertColumn('item_cls_lvl', Column.integer, onTable: 'UnversalProduct'),
  InsertColumn('tax_ty_cd', Column.varchar, onTable: 'UnversalProduct'),
  InsertColumn('mjr_tg_yn', Column.varchar, onTable: 'UnversalProduct'),
  InsertColumn('use_yn', Column.varchar, onTable: 'UnversalProduct'),
  InsertColumn('business_id', Column.integer, onTable: 'UnversalProduct'),
  InsertColumn('branch_id', Column.integer, onTable: 'UnversalProduct'),
  InsertColumn('id', Column.integer, onTable: 'ITransaction', unique: true),
  InsertColumn('reference', Column.varchar, onTable: 'ITransaction'),
  InsertColumn('category_id', Column.varchar, onTable: 'ITransaction'),
  InsertColumn('transaction_number', Column.varchar, onTable: 'ITransaction'),
  InsertColumn('branch_id', Column.integer, onTable: 'ITransaction'),
  InsertColumn('status', Column.varchar, onTable: 'ITransaction'),
  InsertColumn('transaction_type', Column.varchar, onTable: 'ITransaction'),
  InsertColumn('sub_total', Column.Double, onTable: 'ITransaction'),
  InsertColumn('payment_type', Column.varchar, onTable: 'ITransaction'),
  InsertColumn('cash_received', Column.Double, onTable: 'ITransaction'),
  InsertColumn('customer_change_due', Column.Double, onTable: 'ITransaction'),
  InsertColumn('created_at', Column.varchar, onTable: 'ITransaction'),
  InsertColumn('receipt_type', Column.varchar, onTable: 'ITransaction'),
  InsertColumn('updated_at', Column.varchar, onTable: 'ITransaction'),
  InsertColumn('customer_id', Column.integer, onTable: 'ITransaction'),
  InsertColumn('customer_type', Column.varchar, onTable: 'ITransaction'),
  InsertColumn('note', Column.varchar, onTable: 'ITransaction'),
  InsertColumn('last_touched', Column.datetime, onTable: 'ITransaction'),
  InsertColumn('ticket_name', Column.varchar, onTable: 'ITransaction'),
  InsertColumn('deleted_at', Column.datetime, onTable: 'ITransaction'),
  InsertColumn('supplier_id', Column.integer, onTable: 'ITransaction'),
  InsertColumn('ebm_synced', Column.boolean, onTable: 'ITransaction'),
  InsertColumn('is_income', Column.boolean, onTable: 'ITransaction'),
  InsertColumn('is_expense', Column.boolean, onTable: 'ITransaction'),
  InsertColumn('is_refunded', Column.boolean, onTable: 'ITransaction'),
  InsertColumn('customer_name', Column.varchar, onTable: 'ITransaction'),
  InsertColumn('customer_tin', Column.varchar, onTable: 'ITransaction'),
  InsertColumn('remark', Column.varchar, onTable: 'ITransaction'),
  InsertColumn('customer_bhf_id', Column.varchar, onTable: 'ITransaction'),
  InsertColumn('sar_ty_cd', Column.varchar, onTable: 'ITransaction'),
  InsertColumn('receipt_number', Column.integer, onTable: 'ITransaction'),
  InsertColumn('total_receipt_number', Column.integer, onTable: 'ITransaction'),
  InsertColumn('invoice_number', Column.integer, onTable: 'ITransaction'),
  InsertColumn('id', Column.integer, onTable: 'Configurations', unique: true),
  InsertColumn('tax_type', Column.varchar, onTable: 'Configurations'),
  InsertColumn('tax_percentage', Column.Double, onTable: 'Configurations'),
  InsertColumn('business_id', Column.integer, onTable: 'Configurations'),
  InsertColumn('branch_id', Column.integer, onTable: 'Configurations'),
  InsertColumn('id', Column.integer, onTable: 'PColor', unique: true),
  InsertColumn('name', Column.varchar, onTable: 'PColor'),
  InsertColumn('colors', Column.varchar, onTable: 'PColor'),
  InsertColumn('branch_id', Column.integer, onTable: 'PColor'),
  InsertColumn('active', Column.boolean, onTable: 'PColor'),
  InsertColumn('last_touched', Column.datetime, onTable: 'PColor'),
  InsertColumn('deleted_at', Column.datetime, onTable: 'PColor'),
  InsertColumn('id', Column.integer, onTable: 'Device', unique: true),
  InsertColumn('linking_code', Column.varchar, onTable: 'Device'),
  InsertColumn('device_name', Column.varchar, onTable: 'Device'),
  InsertColumn('device_version', Column.varchar, onTable: 'Device'),
  InsertColumn('pub_nub_published', Column.boolean, onTable: 'Device'),
  InsertColumn('phone', Column.varchar, onTable: 'Device'),
  InsertColumn('branch_id', Column.integer, onTable: 'Device'),
  InsertColumn('business_id', Column.integer, onTable: 'Device'),
  InsertColumn('user_id', Column.integer, onTable: 'Device'),
  InsertColumn('default_app', Column.varchar, onTable: 'Device'),
  InsertColumn('last_touched', Column.datetime, onTable: 'Device'),
  InsertColumn('deleted_at', Column.datetime, onTable: 'Device'),
  InsertColumn('id', Column.integer, onTable: 'Favorite', unique: true),
  InsertColumn('fav_index', Column.integer, onTable: 'Favorite'),
  InsertColumn('product_id', Column.integer, onTable: 'Favorite'),
  InsertColumn('branch_id', Column.integer, onTable: 'Favorite'),
  InsertColumn('last_touched', Column.datetime, onTable: 'Favorite'),
  InsertColumn('deleted_at', Column.datetime, onTable: 'Favorite'),
  InsertColumn('id', Column.integer, onTable: 'Setting', unique: true),
  InsertColumn('email', Column.varchar, onTable: 'Setting'),
  InsertColumn('user_id', Column.integer, onTable: 'Setting'),
  InsertColumn('open_receipt_file_o_sale_complete', Column.boolean, onTable: 'Setting'),
  InsertColumn('auto_print', Column.boolean, onTable: 'Setting'),
  InsertColumn('send_daily_report', Column.boolean, onTable: 'Setting'),
  InsertColumn('default_language', Column.varchar, onTable: 'Setting'),
  InsertColumn('attendnace_doc_created', Column.boolean, onTable: 'Setting'),
  InsertColumn('is_attendance_enabled', Column.boolean, onTable: 'Setting'),
  InsertColumn('type', Column.varchar, onTable: 'Setting'),
  InsertColumn('enrolled_in_bot', Column.boolean, onTable: 'Setting'),
  InsertColumn('device_token', Column.varchar, onTable: 'Setting'),
  InsertColumn('business_phone_number', Column.varchar, onTable: 'Setting'),
  InsertColumn('auto_respond', Column.boolean, onTable: 'Setting'),
  InsertColumn('token', Column.varchar, onTable: 'Setting'),
  InsertColumn('has_pin', Column.boolean, onTable: 'Setting'),
  InsertColumn('business_id', Column.integer, onTable: 'Setting'),
  InsertColumn('created_at', Column.varchar, onTable: 'Setting'),
  InsertColumn('last_touched', Column.datetime, onTable: 'Setting'),
  InsertColumn('deleted_at', Column.datetime, onTable: 'Setting'),
  InsertColumn('id', Column.integer, onTable: 'Tenant', unique: true),
  InsertColumn('name', Column.varchar, onTable: 'Tenant'),
  InsertColumn('phone_number', Column.varchar, onTable: 'Tenant'),
  InsertColumn('email', Column.varchar, onTable: 'Tenant'),
  InsertColumn('nfc_enabled', Column.boolean, onTable: 'Tenant'),
  InsertColumn('business_id', Column.integer, onTable: 'Tenant'),
  InsertColumn('user_id', Column.integer, onTable: 'Tenant'),
  InsertColumn('image_url', Column.varchar, onTable: 'Tenant'),
  InsertColumn('last_touched', Column.datetime, onTable: 'Tenant'),
  InsertColumn('deleted_at', Column.datetime, onTable: 'Tenant'),
  InsertColumn('pin', Column.integer, onTable: 'Tenant'),
  InsertColumn('session_active', Column.boolean, onTable: 'Tenant'),
  InsertColumn('is_default', Column.boolean, onTable: 'Tenant'),
  InsertColumn('is_long_pressed', Column.boolean, onTable: 'Tenant'),
  InsertColumn('type', Column.varchar, onTable: 'Tenant'),
  InsertColumn('id', Column.integer, onTable: 'Pin', unique: true),
  InsertColumn('user_id', Column.integer, onTable: 'Pin'),
  InsertColumn('phone_number', Column.varchar, onTable: 'Pin'),
  InsertColumn('pin', Column.integer, onTable: 'Pin'),
  InsertColumn('branch_id', Column.integer, onTable: 'Pin'),
  InsertColumn('business_id', Column.integer, onTable: 'Pin'),
  InsertColumn('owner_name', Column.varchar, onTable: 'Pin'),
  InsertColumn('token_uid', Column.varchar, onTable: 'Pin'),
  InsertColumn('uid', Column.varchar, onTable: 'Pin'),
  InsertColumn('id', Column.integer, onTable: 'Access', unique: true),
  InsertColumn('branch_id', Column.integer, onTable: 'Access'),
  InsertColumn('business_id', Column.integer, onTable: 'Access'),
  InsertColumn('user_id', Column.integer, onTable: 'Access'),
  InsertColumn('feature_name', Column.varchar, onTable: 'Access'),
  InsertColumn('user_type', Column.varchar, onTable: 'Access'),
  InsertColumn('access_level', Column.varchar, onTable: 'Access'),
  InsertColumn('created_at', Column.datetime, onTable: 'Access'),
  InsertColumn('expires_at', Column.datetime, onTable: 'Access'),
  InsertColumn('status', Column.varchar, onTable: 'Access'),
  InsertColumn('id', Column.integer, onTable: 'Customer', unique: true),
  InsertColumn('cust_nm', Column.varchar, onTable: 'Customer'),
  InsertColumn('email', Column.varchar, onTable: 'Customer'),
  InsertColumn('tel_no', Column.varchar, onTable: 'Customer'),
  InsertColumn('adrs', Column.varchar, onTable: 'Customer'),
  InsertColumn('branch_id', Column.integer, onTable: 'Customer'),
  InsertColumn('updated_at', Column.datetime, onTable: 'Customer'),
  InsertColumn('cust_no', Column.varchar, onTable: 'Customer'),
  InsertColumn('cust_tin', Column.varchar, onTable: 'Customer'),
  InsertColumn('regr_nm', Column.varchar, onTable: 'Customer'),
  InsertColumn('regr_id', Column.varchar, onTable: 'Customer'),
  InsertColumn('modr_nm', Column.varchar, onTable: 'Customer'),
  InsertColumn('modr_id', Column.varchar, onTable: 'Customer'),
  InsertColumn('ebm_synced', Column.boolean, onTable: 'Customer'),
  InsertColumn('last_touched', Column.datetime, onTable: 'Customer'),
  InsertColumn('deleted_at', Column.datetime, onTable: 'Customer'),
  InsertColumn('tin', Column.integer, onTable: 'Customer'),
  InsertColumn('bhf_id', Column.varchar, onTable: 'Customer'),
  InsertColumn('use_yn', Column.varchar, onTable: 'Customer'),
  InsertColumn('customer_type', Column.varchar, onTable: 'Customer'),
  InsertColumn('id', Column.integer, onTable: 'Report', unique: true),
  InsertColumn('branch_id', Column.integer, onTable: 'Report'),
  InsertColumn('business_id', Column.integer, onTable: 'Report'),
  InsertColumn('filename', Column.varchar, onTable: 'Report'),
  InsertColumn('s3_url', Column.varchar, onTable: 'Report'),
  InsertColumn('downloaded', Column.boolean, onTable: 'Report'),
  InsertColumn('id', Column.integer, onTable: 'Business', unique: true),
  InsertColumn('name', Column.varchar, onTable: 'Business'),
  InsertColumn('currency', Column.varchar, onTable: 'Business'),
  InsertColumn('category_id', Column.varchar, onTable: 'Business'),
  InsertColumn('latitude', Column.varchar, onTable: 'Business'),
  InsertColumn('longitude', Column.varchar, onTable: 'Business'),
  InsertColumn('user_id', Column.integer, onTable: 'Business'),
  InsertColumn('time_zone', Column.varchar, onTable: 'Business'),
  InsertColumn('country', Column.varchar, onTable: 'Business'),
  InsertColumn('business_url', Column.varchar, onTable: 'Business'),
  InsertColumn('hex_color', Column.varchar, onTable: 'Business'),
  InsertColumn('image_url', Column.varchar, onTable: 'Business'),
  InsertColumn('type', Column.varchar, onTable: 'Business'),
  InsertColumn('active', Column.boolean, onTable: 'Business'),
  InsertColumn('chat_uid', Column.varchar, onTable: 'Business'),
  InsertColumn('metadata', Column.varchar, onTable: 'Business'),
  InsertColumn('role', Column.varchar, onTable: 'Business'),
  InsertColumn('last_seen', Column.integer, onTable: 'Business'),
  InsertColumn('first_name', Column.varchar, onTable: 'Business'),
  InsertColumn('last_name', Column.varchar, onTable: 'Business'),
  InsertColumn('created_at', Column.varchar, onTable: 'Business'),
  InsertColumn('device_token', Column.varchar, onTable: 'Business'),
  InsertColumn('back_up_enabled', Column.boolean, onTable: 'Business'),
  InsertColumn('subscription_plan', Column.varchar, onTable: 'Business'),
  InsertColumn('next_billing_date', Column.varchar, onTable: 'Business'),
  InsertColumn('previous_billing_date', Column.varchar, onTable: 'Business'),
  InsertColumn('is_last_subscription_payment_succeeded', Column.boolean, onTable: 'Business'),
  InsertColumn('backup_file_id', Column.varchar, onTable: 'Business'),
  InsertColumn('email', Column.varchar, onTable: 'Business'),
  InsertColumn('last_db_backup', Column.varchar, onTable: 'Business'),
  InsertColumn('full_name', Column.varchar, onTable: 'Business'),
  InsertColumn('tin_number', Column.integer, onTable: 'Business'),
  InsertColumn('bhf_id', Column.varchar, onTable: 'Business'),
  InsertColumn('dvc_srl_no', Column.varchar, onTable: 'Business'),
  InsertColumn('adrs', Column.varchar, onTable: 'Business'),
  InsertColumn('tax_enabled', Column.boolean, onTable: 'Business'),
  InsertColumn('tax_server_url', Column.varchar, onTable: 'Business'),
  InsertColumn('is_default', Column.boolean, onTable: 'Business'),
  InsertColumn('business_type_id', Column.integer, onTable: 'Business'),
  InsertColumn('last_touched', Column.datetime, onTable: 'Business'),
  InsertColumn('deleted_at', Column.datetime, onTable: 'Business'),
  InsertColumn('encryption_key', Column.varchar, onTable: 'Business'),
  InsertColumn('id', Column.integer, onTable: 'SKU', unique: true),
  InsertColumn('sku', Column.integer, onTable: 'SKU'),
  InsertColumn('branch_id', Column.integer, onTable: 'SKU'),
  InsertColumn('business_id', Column.integer, onTable: 'SKU'),
  InsertColumn('consumed', Column.boolean, onTable: 'SKU'),
  InsertColumn('id', Column.integer, onTable: 'IUnit', unique: true),
  InsertColumn('branch_id', Column.integer, onTable: 'IUnit'),
  InsertColumn('name', Column.varchar, onTable: 'IUnit'),
  InsertColumn('value', Column.varchar, onTable: 'IUnit'),
  InsertColumn('active', Column.boolean, onTable: 'IUnit'),
  InsertColumn('last_touched', Column.datetime, onTable: 'IUnit'),
  InsertColumn('created_at', Column.varchar, onTable: 'IUnit'),
  InsertColumn('deleted_at', Column.datetime, onTable: 'IUnit'),
  InsertColumn('id', Column.integer, onTable: 'Location', unique: true),
  InsertColumn('server_id', Column.integer, onTable: 'Location'),
  InsertColumn('active', Column.boolean, onTable: 'Location'),
  InsertColumn('description', Column.varchar, onTable: 'Location'),
  InsertColumn('name', Column.varchar, onTable: 'Location'),
  InsertColumn('business_id', Column.integer, onTable: 'Location'),
  InsertColumn('longitude', Column.varchar, onTable: 'Location'),
  InsertColumn('latitude', Column.varchar, onTable: 'Location'),
  InsertColumn('location', Column.varchar, onTable: 'Location'),
  InsertColumn('is_default', Column.boolean, onTable: 'Location'),
  InsertColumn('last_touched', Column.datetime, onTable: 'Location'),
  InsertColumn('deleted_at', Column.datetime, onTable: 'Location'),
  InsertColumn('is_online', Column.boolean, onTable: 'Location'),
  InsertColumn('id', Column.integer, onTable: 'Receipt', unique: true),
  InsertColumn('result_cd', Column.varchar, onTable: 'Receipt'),
  InsertColumn('result_msg', Column.varchar, onTable: 'Receipt'),
  InsertColumn('result_dt', Column.varchar, onTable: 'Receipt'),
  InsertColumn('rcpt_no', Column.integer, onTable: 'Receipt'),
  InsertColumn('intrl_data', Column.varchar, onTable: 'Receipt'),
  InsertColumn('rcpt_sign', Column.varchar, onTable: 'Receipt'),
  InsertColumn('tot_rcpt_no', Column.integer, onTable: 'Receipt'),
  InsertColumn('vsdc_rcpt_pbct_date', Column.varchar, onTable: 'Receipt'),
  InsertColumn('sdc_id', Column.varchar, onTable: 'Receipt'),
  InsertColumn('mrc_no', Column.varchar, onTable: 'Receipt'),
  InsertColumn('qr_code', Column.varchar, onTable: 'Receipt'),
  InsertColumn('receipt_type', Column.varchar, onTable: 'Receipt'),
  InsertColumn('branch_id', Column.integer, onTable: 'Receipt'),
  InsertColumn('transaction_id', Column.integer, onTable: 'Receipt'),
  InsertColumn('last_touched', Column.datetime, onTable: 'Receipt'),
  InsertColumn('invc_no', Column.integer, onTable: 'Receipt'),
  InsertColumn('when_created', Column.datetime, onTable: 'Receipt'),
  InsertColumn('invoice_number', Column.integer, onTable: 'Receipt'),
  InsertColumn('id', Column.integer, onTable: 'Drawers', unique: true),
  InsertColumn('opening_balance', Column.Double, onTable: 'Drawers'),
  InsertColumn('closing_balance', Column.Double, onTable: 'Drawers'),
  InsertColumn('opening_date_time', Column.varchar, onTable: 'Drawers'),
  InsertColumn('closing_date_time', Column.varchar, onTable: 'Drawers'),
  InsertColumn('cs_sale_count', Column.integer, onTable: 'Drawers'),
  InsertColumn('trade_name', Column.varchar, onTable: 'Drawers'),
  InsertColumn('total_ns_sale_income', Column.Double, onTable: 'Drawers'),
  InsertColumn('total_cs_sale_income', Column.Double, onTable: 'Drawers'),
  InsertColumn('nr_sale_count', Column.integer, onTable: 'Drawers'),
  InsertColumn('ns_sale_count', Column.integer, onTable: 'Drawers'),
  InsertColumn('tr_sale_count', Column.integer, onTable: 'Drawers'),
  InsertColumn('ps_sale_count', Column.integer, onTable: 'Drawers'),
  InsertColumn('incomplete_sale', Column.integer, onTable: 'Drawers'),
  InsertColumn('other_transactions', Column.integer, onTable: 'Drawers'),
  InsertColumn('payment_mode', Column.varchar, onTable: 'Drawers'),
  InsertColumn('cashier_id', Column.integer, onTable: 'Drawers'),
  InsertColumn('open', Column.boolean, onTable: 'Drawers'),
  InsertColumn('deleted_at', Column.datetime, onTable: 'Drawers'),
  InsertColumn('business_id', Column.integer, onTable: 'Drawers'),
  InsertColumn('branch_id', Column.integer, onTable: 'Drawers')
];

const List<MigrationCommand> _migration_20241128141446_down = [
  DropTable('Category'),
  DropTable('UnversalProduct'),
  DropTable('ITransaction'),
  DropTable('Configurations'),
  DropTable('PColor'),
  DropTable('Device'),
  DropTable('Favorite'),
  DropTable('Setting'),
  DropTable('Tenant'),
  DropTable('Pin'),
  DropTable('Access'),
  DropTable('Customer'),
  DropTable('Report'),
  DropTable('Business'),
  DropTable('SKU'),
  DropTable('IUnit'),
  DropTable('Location'),
  DropTable('Receipt'),
  DropTable('Drawers'),
  DropColumn('id', onTable: 'Category'),
  DropColumn('active', onTable: 'Category'),
  DropColumn('focused', onTable: 'Category'),
  DropColumn('name', onTable: 'Category'),
  DropColumn('branch_id', onTable: 'Category'),
  DropColumn('deleted_at', onTable: 'Category'),
  DropColumn('last_touched', onTable: 'Category'),
  DropColumn('id', onTable: 'UnversalProduct'),
  DropColumn('item_cls_cd', onTable: 'UnversalProduct'),
  DropColumn('item_cls_nm', onTable: 'UnversalProduct'),
  DropColumn('item_cls_lvl', onTable: 'UnversalProduct'),
  DropColumn('tax_ty_cd', onTable: 'UnversalProduct'),
  DropColumn('mjr_tg_yn', onTable: 'UnversalProduct'),
  DropColumn('use_yn', onTable: 'UnversalProduct'),
  DropColumn('business_id', onTable: 'UnversalProduct'),
  DropColumn('branch_id', onTable: 'UnversalProduct'),
  DropColumn('id', onTable: 'ITransaction'),
  DropColumn('reference', onTable: 'ITransaction'),
  DropColumn('category_id', onTable: 'ITransaction'),
  DropColumn('transaction_number', onTable: 'ITransaction'),
  DropColumn('branch_id', onTable: 'ITransaction'),
  DropColumn('status', onTable: 'ITransaction'),
  DropColumn('transaction_type', onTable: 'ITransaction'),
  DropColumn('sub_total', onTable: 'ITransaction'),
  DropColumn('payment_type', onTable: 'ITransaction'),
  DropColumn('cash_received', onTable: 'ITransaction'),
  DropColumn('customer_change_due', onTable: 'ITransaction'),
  DropColumn('created_at', onTable: 'ITransaction'),
  DropColumn('receipt_type', onTable: 'ITransaction'),
  DropColumn('updated_at', onTable: 'ITransaction'),
  DropColumn('customer_id', onTable: 'ITransaction'),
  DropColumn('customer_type', onTable: 'ITransaction'),
  DropColumn('note', onTable: 'ITransaction'),
  DropColumn('last_touched', onTable: 'ITransaction'),
  DropColumn('ticket_name', onTable: 'ITransaction'),
  DropColumn('deleted_at', onTable: 'ITransaction'),
  DropColumn('supplier_id', onTable: 'ITransaction'),
  DropColumn('ebm_synced', onTable: 'ITransaction'),
  DropColumn('is_income', onTable: 'ITransaction'),
  DropColumn('is_expense', onTable: 'ITransaction'),
  DropColumn('is_refunded', onTable: 'ITransaction'),
  DropColumn('customer_name', onTable: 'ITransaction'),
  DropColumn('customer_tin', onTable: 'ITransaction'),
  DropColumn('remark', onTable: 'ITransaction'),
  DropColumn('customer_bhf_id', onTable: 'ITransaction'),
  DropColumn('sar_ty_cd', onTable: 'ITransaction'),
  DropColumn('receipt_number', onTable: 'ITransaction'),
  DropColumn('total_receipt_number', onTable: 'ITransaction'),
  DropColumn('invoice_number', onTable: 'ITransaction'),
  DropColumn('id', onTable: 'Configurations'),
  DropColumn('tax_type', onTable: 'Configurations'),
  DropColumn('tax_percentage', onTable: 'Configurations'),
  DropColumn('business_id', onTable: 'Configurations'),
  DropColumn('branch_id', onTable: 'Configurations'),
  DropColumn('id', onTable: 'PColor'),
  DropColumn('name', onTable: 'PColor'),
  DropColumn('colors', onTable: 'PColor'),
  DropColumn('branch_id', onTable: 'PColor'),
  DropColumn('active', onTable: 'PColor'),
  DropColumn('last_touched', onTable: 'PColor'),
  DropColumn('deleted_at', onTable: 'PColor'),
  DropColumn('id', onTable: 'Device'),
  DropColumn('linking_code', onTable: 'Device'),
  DropColumn('device_name', onTable: 'Device'),
  DropColumn('device_version', onTable: 'Device'),
  DropColumn('pub_nub_published', onTable: 'Device'),
  DropColumn('phone', onTable: 'Device'),
  DropColumn('branch_id', onTable: 'Device'),
  DropColumn('business_id', onTable: 'Device'),
  DropColumn('user_id', onTable: 'Device'),
  DropColumn('default_app', onTable: 'Device'),
  DropColumn('last_touched', onTable: 'Device'),
  DropColumn('deleted_at', onTable: 'Device'),
  DropColumn('id', onTable: 'Favorite'),
  DropColumn('fav_index', onTable: 'Favorite'),
  DropColumn('product_id', onTable: 'Favorite'),
  DropColumn('branch_id', onTable: 'Favorite'),
  DropColumn('last_touched', onTable: 'Favorite'),
  DropColumn('deleted_at', onTable: 'Favorite'),
  DropColumn('id', onTable: 'Setting'),
  DropColumn('email', onTable: 'Setting'),
  DropColumn('user_id', onTable: 'Setting'),
  DropColumn('open_receipt_file_o_sale_complete', onTable: 'Setting'),
  DropColumn('auto_print', onTable: 'Setting'),
  DropColumn('send_daily_report', onTable: 'Setting'),
  DropColumn('default_language', onTable: 'Setting'),
  DropColumn('attendnace_doc_created', onTable: 'Setting'),
  DropColumn('is_attendance_enabled', onTable: 'Setting'),
  DropColumn('type', onTable: 'Setting'),
  DropColumn('enrolled_in_bot', onTable: 'Setting'),
  DropColumn('device_token', onTable: 'Setting'),
  DropColumn('business_phone_number', onTable: 'Setting'),
  DropColumn('auto_respond', onTable: 'Setting'),
  DropColumn('token', onTable: 'Setting'),
  DropColumn('has_pin', onTable: 'Setting'),
  DropColumn('business_id', onTable: 'Setting'),
  DropColumn('created_at', onTable: 'Setting'),
  DropColumn('last_touched', onTable: 'Setting'),
  DropColumn('deleted_at', onTable: 'Setting'),
  DropColumn('id', onTable: 'Tenant'),
  DropColumn('name', onTable: 'Tenant'),
  DropColumn('phone_number', onTable: 'Tenant'),
  DropColumn('email', onTable: 'Tenant'),
  DropColumn('nfc_enabled', onTable: 'Tenant'),
  DropColumn('business_id', onTable: 'Tenant'),
  DropColumn('user_id', onTable: 'Tenant'),
  DropColumn('image_url', onTable: 'Tenant'),
  DropColumn('last_touched', onTable: 'Tenant'),
  DropColumn('deleted_at', onTable: 'Tenant'),
  DropColumn('pin', onTable: 'Tenant'),
  DropColumn('session_active', onTable: 'Tenant'),
  DropColumn('is_default', onTable: 'Tenant'),
  DropColumn('is_long_pressed', onTable: 'Tenant'),
  DropColumn('type', onTable: 'Tenant'),
  DropColumn('id', onTable: 'Pin'),
  DropColumn('user_id', onTable: 'Pin'),
  DropColumn('phone_number', onTable: 'Pin'),
  DropColumn('pin', onTable: 'Pin'),
  DropColumn('branch_id', onTable: 'Pin'),
  DropColumn('business_id', onTable: 'Pin'),
  DropColumn('owner_name', onTable: 'Pin'),
  DropColumn('token_uid', onTable: 'Pin'),
  DropColumn('uid', onTable: 'Pin'),
  DropColumn('id', onTable: 'Access'),
  DropColumn('branch_id', onTable: 'Access'),
  DropColumn('business_id', onTable: 'Access'),
  DropColumn('user_id', onTable: 'Access'),
  DropColumn('feature_name', onTable: 'Access'),
  DropColumn('user_type', onTable: 'Access'),
  DropColumn('access_level', onTable: 'Access'),
  DropColumn('created_at', onTable: 'Access'),
  DropColumn('expires_at', onTable: 'Access'),
  DropColumn('status', onTable: 'Access'),
  DropColumn('id', onTable: 'Customer'),
  DropColumn('cust_nm', onTable: 'Customer'),
  DropColumn('email', onTable: 'Customer'),
  DropColumn('tel_no', onTable: 'Customer'),
  DropColumn('adrs', onTable: 'Customer'),
  DropColumn('branch_id', onTable: 'Customer'),
  DropColumn('updated_at', onTable: 'Customer'),
  DropColumn('cust_no', onTable: 'Customer'),
  DropColumn('cust_tin', onTable: 'Customer'),
  DropColumn('regr_nm', onTable: 'Customer'),
  DropColumn('regr_id', onTable: 'Customer'),
  DropColumn('modr_nm', onTable: 'Customer'),
  DropColumn('modr_id', onTable: 'Customer'),
  DropColumn('ebm_synced', onTable: 'Customer'),
  DropColumn('last_touched', onTable: 'Customer'),
  DropColumn('deleted_at', onTable: 'Customer'),
  DropColumn('tin', onTable: 'Customer'),
  DropColumn('bhf_id', onTable: 'Customer'),
  DropColumn('use_yn', onTable: 'Customer'),
  DropColumn('customer_type', onTable: 'Customer'),
  DropColumn('id', onTable: 'Report'),
  DropColumn('branch_id', onTable: 'Report'),
  DropColumn('business_id', onTable: 'Report'),
  DropColumn('filename', onTable: 'Report'),
  DropColumn('s3_url', onTable: 'Report'),
  DropColumn('downloaded', onTable: 'Report'),
  DropColumn('id', onTable: 'Business'),
  DropColumn('name', onTable: 'Business'),
  DropColumn('currency', onTable: 'Business'),
  DropColumn('category_id', onTable: 'Business'),
  DropColumn('latitude', onTable: 'Business'),
  DropColumn('longitude', onTable: 'Business'),
  DropColumn('user_id', onTable: 'Business'),
  DropColumn('time_zone', onTable: 'Business'),
  DropColumn('country', onTable: 'Business'),
  DropColumn('business_url', onTable: 'Business'),
  DropColumn('hex_color', onTable: 'Business'),
  DropColumn('image_url', onTable: 'Business'),
  DropColumn('type', onTable: 'Business'),
  DropColumn('active', onTable: 'Business'),
  DropColumn('chat_uid', onTable: 'Business'),
  DropColumn('metadata', onTable: 'Business'),
  DropColumn('role', onTable: 'Business'),
  DropColumn('last_seen', onTable: 'Business'),
  DropColumn('first_name', onTable: 'Business'),
  DropColumn('last_name', onTable: 'Business'),
  DropColumn('created_at', onTable: 'Business'),
  DropColumn('device_token', onTable: 'Business'),
  DropColumn('back_up_enabled', onTable: 'Business'),
  DropColumn('subscription_plan', onTable: 'Business'),
  DropColumn('next_billing_date', onTable: 'Business'),
  DropColumn('previous_billing_date', onTable: 'Business'),
  DropColumn('is_last_subscription_payment_succeeded', onTable: 'Business'),
  DropColumn('backup_file_id', onTable: 'Business'),
  DropColumn('email', onTable: 'Business'),
  DropColumn('last_db_backup', onTable: 'Business'),
  DropColumn('full_name', onTable: 'Business'),
  DropColumn('tin_number', onTable: 'Business'),
  DropColumn('bhf_id', onTable: 'Business'),
  DropColumn('dvc_srl_no', onTable: 'Business'),
  DropColumn('adrs', onTable: 'Business'),
  DropColumn('tax_enabled', onTable: 'Business'),
  DropColumn('tax_server_url', onTable: 'Business'),
  DropColumn('is_default', onTable: 'Business'),
  DropColumn('business_type_id', onTable: 'Business'),
  DropColumn('last_touched', onTable: 'Business'),
  DropColumn('deleted_at', onTable: 'Business'),
  DropColumn('encryption_key', onTable: 'Business'),
  DropColumn('id', onTable: 'SKU'),
  DropColumn('sku', onTable: 'SKU'),
  DropColumn('branch_id', onTable: 'SKU'),
  DropColumn('business_id', onTable: 'SKU'),
  DropColumn('consumed', onTable: 'SKU'),
  DropColumn('id', onTable: 'IUnit'),
  DropColumn('branch_id', onTable: 'IUnit'),
  DropColumn('name', onTable: 'IUnit'),
  DropColumn('value', onTable: 'IUnit'),
  DropColumn('active', onTable: 'IUnit'),
  DropColumn('last_touched', onTable: 'IUnit'),
  DropColumn('created_at', onTable: 'IUnit'),
  DropColumn('deleted_at', onTable: 'IUnit'),
  DropColumn('id', onTable: 'Location'),
  DropColumn('server_id', onTable: 'Location'),
  DropColumn('active', onTable: 'Location'),
  DropColumn('description', onTable: 'Location'),
  DropColumn('name', onTable: 'Location'),
  DropColumn('business_id', onTable: 'Location'),
  DropColumn('longitude', onTable: 'Location'),
  DropColumn('latitude', onTable: 'Location'),
  DropColumn('location', onTable: 'Location'),
  DropColumn('is_default', onTable: 'Location'),
  DropColumn('last_touched', onTable: 'Location'),
  DropColumn('deleted_at', onTable: 'Location'),
  DropColumn('is_online', onTable: 'Location'),
  DropColumn('id', onTable: 'Receipt'),
  DropColumn('result_cd', onTable: 'Receipt'),
  DropColumn('result_msg', onTable: 'Receipt'),
  DropColumn('result_dt', onTable: 'Receipt'),
  DropColumn('rcpt_no', onTable: 'Receipt'),
  DropColumn('intrl_data', onTable: 'Receipt'),
  DropColumn('rcpt_sign', onTable: 'Receipt'),
  DropColumn('tot_rcpt_no', onTable: 'Receipt'),
  DropColumn('vsdc_rcpt_pbct_date', onTable: 'Receipt'),
  DropColumn('sdc_id', onTable: 'Receipt'),
  DropColumn('mrc_no', onTable: 'Receipt'),
  DropColumn('qr_code', onTable: 'Receipt'),
  DropColumn('receipt_type', onTable: 'Receipt'),
  DropColumn('branch_id', onTable: 'Receipt'),
  DropColumn('transaction_id', onTable: 'Receipt'),
  DropColumn('last_touched', onTable: 'Receipt'),
  DropColumn('invc_no', onTable: 'Receipt'),
  DropColumn('when_created', onTable: 'Receipt'),
  DropColumn('invoice_number', onTable: 'Receipt'),
  DropColumn('id', onTable: 'Drawers'),
  DropColumn('opening_balance', onTable: 'Drawers'),
  DropColumn('closing_balance', onTable: 'Drawers'),
  DropColumn('opening_date_time', onTable: 'Drawers'),
  DropColumn('closing_date_time', onTable: 'Drawers'),
  DropColumn('cs_sale_count', onTable: 'Drawers'),
  DropColumn('trade_name', onTable: 'Drawers'),
  DropColumn('total_ns_sale_income', onTable: 'Drawers'),
  DropColumn('total_cs_sale_income', onTable: 'Drawers'),
  DropColumn('nr_sale_count', onTable: 'Drawers'),
  DropColumn('ns_sale_count', onTable: 'Drawers'),
  DropColumn('tr_sale_count', onTable: 'Drawers'),
  DropColumn('ps_sale_count', onTable: 'Drawers'),
  DropColumn('incomplete_sale', onTable: 'Drawers'),
  DropColumn('other_transactions', onTable: 'Drawers'),
  DropColumn('payment_mode', onTable: 'Drawers'),
  DropColumn('cashier_id', onTable: 'Drawers'),
  DropColumn('open', onTable: 'Drawers'),
  DropColumn('deleted_at', onTable: 'Drawers'),
  DropColumn('business_id', onTable: 'Drawers'),
  DropColumn('branch_id', onTable: 'Drawers')
];

//
// DO NOT EDIT BELOW THIS LINE
//

@Migratable(
  version: '20241128141446',
  up: _migration_20241128141446_up,
  down: _migration_20241128141446_down,
)
class Migration20241128141446 extends Migration {
  const Migration20241128141446()
    : super(
        version: 20241128141446,
        up: _migration_20241128141446_up,
        down: _migration_20241128141446_down,
      );
}
