// GENERATED CODE EDIT WITH CAUTION
// THIS FILE **WILL NOT** BE REGENERATED
// This file should be version controlled and can be manually edited.
part of 'schema.g.dart';

// While migrations are intelligently created, the difference between some commands, such as
// DropTable vs. RenameTable, cannot be determined. For this reason, please review migrations after
// they are created to ensure the correct inference was made.

// The migration version must **always** mirror the file name

const List<MigrationCommand> _migration_20241128071810_up = [
  InsertTable('Variant'),
  InsertTable('Product'),
  InsertTable('Stock'),
  InsertTable('Composite'),
  InsertColumn('id', Column.integer, onTable: 'Variant', unique: true),
  InsertColumn('deleted_at', Column.datetime, onTable: 'Variant'),
  InsertColumn('name', Column.varchar, onTable: 'Variant'),
  InsertColumn('color', Column.varchar, onTable: 'Variant'),
  InsertColumn('sku', Column.varchar, onTable: 'Variant'),
  InsertColumn('product_id', Column.integer, onTable: 'Variant'),
  InsertColumn('unit', Column.varchar, onTable: 'Variant'),
  InsertColumn('product_name', Column.varchar, onTable: 'Variant'),
  InsertColumn('branch_id', Column.integer, onTable: 'Variant'),
  InsertColumn('tax_name', Column.varchar, onTable: 'Variant'),
  InsertColumn('tax_percentage', Column.Double, onTable: 'Variant'),
  InsertColumn('item_seq', Column.integer, onTable: 'Variant'),
  InsertColumn('isrcc_cd', Column.varchar, onTable: 'Variant'),
  InsertColumn('isrcc_nm', Column.varchar, onTable: 'Variant'),
  InsertColumn('isrc_rt', Column.integer, onTable: 'Variant'),
  InsertColumn('isrc_amt', Column.integer, onTable: 'Variant'),
  InsertColumn('tax_ty_cd', Column.varchar, onTable: 'Variant'),
  InsertColumn('bcd', Column.varchar, onTable: 'Variant'),
  InsertColumn('item_cls_cd', Column.varchar, onTable: 'Variant'),
  InsertColumn('item_ty_cd', Column.varchar, onTable: 'Variant'),
  InsertColumn('item_std_nm', Column.varchar, onTable: 'Variant'),
  InsertColumn('orgn_nat_cd', Column.varchar, onTable: 'Variant'),
  InsertColumn('pkg', Column.varchar, onTable: 'Variant'),
  InsertColumn('item_cd', Column.varchar, onTable: 'Variant'),
  InsertColumn('pkg_unit_cd', Column.varchar, onTable: 'Variant'),
  InsertColumn('qty_unit_cd', Column.varchar, onTable: 'Variant'),
  InsertColumn('item_nm', Column.varchar, onTable: 'Variant'),
  InsertColumn('qty', Column.Double, onTable: 'Variant'),
  InsertColumn('prc', Column.Double, onTable: 'Variant'),
  InsertColumn('sply_amt', Column.Double, onTable: 'Variant'),
  InsertColumn('tin', Column.integer, onTable: 'Variant'),
  InsertColumn('bhf_id', Column.varchar, onTable: 'Variant'),
  InsertColumn('dft_prc', Column.Double, onTable: 'Variant'),
  InsertColumn('add_info', Column.varchar, onTable: 'Variant'),
  InsertColumn('isrc_aplcb_yn', Column.varchar, onTable: 'Variant'),
  InsertColumn('use_yn', Column.varchar, onTable: 'Variant'),
  InsertColumn('regr_id', Column.varchar, onTable: 'Variant'),
  InsertColumn('regr_nm', Column.varchar, onTable: 'Variant'),
  InsertColumn('modr_id', Column.varchar, onTable: 'Variant'),
  InsertColumn('modr_nm', Column.varchar, onTable: 'Variant'),
  InsertColumn('rsd_qty', Column.Double, onTable: 'Variant'),
  InsertColumn('last_touched', Column.datetime, onTable: 'Variant'),
  InsertColumn('supply_price', Column.Double, onTable: 'Variant'),
  InsertColumn('retail_price', Column.Double, onTable: 'Variant'),
  InsertColumn('spplr_item_cls_cd', Column.varchar, onTable: 'Variant'),
  InsertColumn('spplr_item_cd', Column.varchar, onTable: 'Variant'),
  InsertColumn('spplr_item_nm', Column.varchar, onTable: 'Variant'),
  InsertColumn('ebm_synced', Column.boolean, onTable: 'Variant'),
  InsertColumn('branch_ids', Column.varchar, onTable: 'Variant'),
  InsertColumn('dc_rt', Column.Double, onTable: 'Variant'),
  InsertColumn('expiration_date', Column.datetime, onTable: 'Variant'),
  InsertColumn('id', Column.integer, onTable: 'Product', unique: true),
  InsertColumn('name', Column.varchar, onTable: 'Product'),
  InsertColumn('description', Column.varchar, onTable: 'Product'),
  InsertColumn('tax_id', Column.varchar, onTable: 'Product'),
  InsertColumn('color', Column.varchar, onTable: 'Product'),
  InsertColumn('business_id', Column.integer, onTable: 'Product'),
  InsertColumn('branch_id', Column.integer, onTable: 'Product'),
  InsertColumn('supplier_id', Column.varchar, onTable: 'Product'),
  InsertColumn('category_id', Column.integer, onTable: 'Product'),
  InsertColumn('created_at', Column.varchar, onTable: 'Product'),
  InsertColumn('unit', Column.varchar, onTable: 'Product'),
  InsertColumn('image_url', Column.varchar, onTable: 'Product'),
  InsertColumn('expiry_date', Column.varchar, onTable: 'Product'),
  InsertColumn('bar_code', Column.varchar, onTable: 'Product'),
  InsertColumn('nfc_enabled', Column.boolean, onTable: 'Product'),
  InsertColumn('binded_to_tenant_id', Column.integer, onTable: 'Product'),
  InsertColumn('is_favorite', Column.boolean, onTable: 'Product'),
  InsertColumn('last_touched', Column.datetime, onTable: 'Product'),
  InsertColumn('deleted_at', Column.datetime, onTable: 'Product'),
  InsertColumn('spplr_nm', Column.varchar, onTable: 'Product'),
  InsertColumn('is_composite', Column.boolean, onTable: 'Product'),
  InsertColumn('id', Column.integer, onTable: 'Stock', unique: true),
  InsertColumn('tin', Column.integer, onTable: 'Stock'),
  InsertColumn('bhf_id', Column.varchar, onTable: 'Stock'),
  InsertColumn('branch_id', Column.integer, onTable: 'Stock'),
  InsertColumn('variant_id', Column.integer, onTable: 'Stock'),
  InsertColumn('current_stock', Column.Double, onTable: 'Stock'),
  InsertColumn('low_stock', Column.Double, onTable: 'Stock'),
  InsertColumn('can_tracking_stock', Column.boolean, onTable: 'Stock'),
  InsertColumn('show_low_stock_alert', Column.boolean, onTable: 'Stock'),
  InsertColumn('product_id', Column.integer, onTable: 'Stock'),
  InsertColumn('active', Column.boolean, onTable: 'Stock'),
  InsertColumn('value', Column.Double, onTable: 'Stock'),
  InsertColumn('rsd_qty', Column.Double, onTable: 'Stock'),
  InsertColumn('last_touched', Column.datetime, onTable: 'Stock'),
  InsertColumn('deleted_at', Column.datetime, onTable: 'Stock'),
  InsertColumn('ebm_synced', Column.boolean, onTable: 'Stock'),
  InsertColumn('cloud_synced', Column.boolean, onTable: 'Stock'),
  InsertColumn('initial_stock', Column.Double, onTable: 'Stock'),
  InsertColumn('id', Column.integer, onTable: 'Composite', unique: true),
  InsertColumn('product_id', Column.integer, onTable: 'Composite'),
  InsertColumn('variant_id', Column.integer, onTable: 'Composite'),
  InsertColumn('qty', Column.Double, onTable: 'Composite'),
  InsertColumn('branch_id', Column.integer, onTable: 'Composite'),
  InsertColumn('business_id', Column.integer, onTable: 'Composite'),
  InsertColumn('actual_price', Column.Double, onTable: 'Composite')
];

const List<MigrationCommand> _migration_20241128071810_down = [
  DropTable('Variant'),
  DropTable('Product'),
  DropTable('Stock'),
  DropTable('Composite'),
  DropColumn('id', onTable: 'Variant'),
  DropColumn('deleted_at', onTable: 'Variant'),
  DropColumn('name', onTable: 'Variant'),
  DropColumn('color', onTable: 'Variant'),
  DropColumn('sku', onTable: 'Variant'),
  DropColumn('product_id', onTable: 'Variant'),
  DropColumn('unit', onTable: 'Variant'),
  DropColumn('product_name', onTable: 'Variant'),
  DropColumn('branch_id', onTable: 'Variant'),
  DropColumn('tax_name', onTable: 'Variant'),
  DropColumn('tax_percentage', onTable: 'Variant'),
  DropColumn('item_seq', onTable: 'Variant'),
  DropColumn('isrcc_cd', onTable: 'Variant'),
  DropColumn('isrcc_nm', onTable: 'Variant'),
  DropColumn('isrc_rt', onTable: 'Variant'),
  DropColumn('isrc_amt', onTable: 'Variant'),
  DropColumn('tax_ty_cd', onTable: 'Variant'),
  DropColumn('bcd', onTable: 'Variant'),
  DropColumn('item_cls_cd', onTable: 'Variant'),
  DropColumn('item_ty_cd', onTable: 'Variant'),
  DropColumn('item_std_nm', onTable: 'Variant'),
  DropColumn('orgn_nat_cd', onTable: 'Variant'),
  DropColumn('pkg', onTable: 'Variant'),
  DropColumn('item_cd', onTable: 'Variant'),
  DropColumn('pkg_unit_cd', onTable: 'Variant'),
  DropColumn('qty_unit_cd', onTable: 'Variant'),
  DropColumn('item_nm', onTable: 'Variant'),
  DropColumn('qty', onTable: 'Variant'),
  DropColumn('prc', onTable: 'Variant'),
  DropColumn('sply_amt', onTable: 'Variant'),
  DropColumn('tin', onTable: 'Variant'),
  DropColumn('bhf_id', onTable: 'Variant'),
  DropColumn('dft_prc', onTable: 'Variant'),
  DropColumn('add_info', onTable: 'Variant'),
  DropColumn('isrc_aplcb_yn', onTable: 'Variant'),
  DropColumn('use_yn', onTable: 'Variant'),
  DropColumn('regr_id', onTable: 'Variant'),
  DropColumn('regr_nm', onTable: 'Variant'),
  DropColumn('modr_id', onTable: 'Variant'),
  DropColumn('modr_nm', onTable: 'Variant'),
  DropColumn('rsd_qty', onTable: 'Variant'),
  DropColumn('last_touched', onTable: 'Variant'),
  DropColumn('supply_price', onTable: 'Variant'),
  DropColumn('retail_price', onTable: 'Variant'),
  DropColumn('spplr_item_cls_cd', onTable: 'Variant'),
  DropColumn('spplr_item_cd', onTable: 'Variant'),
  DropColumn('spplr_item_nm', onTable: 'Variant'),
  DropColumn('ebm_synced', onTable: 'Variant'),
  DropColumn('branch_ids', onTable: 'Variant'),
  DropColumn('dc_rt', onTable: 'Variant'),
  DropColumn('expiration_date', onTable: 'Variant'),
  DropColumn('id', onTable: 'Product'),
  DropColumn('name', onTable: 'Product'),
  DropColumn('description', onTable: 'Product'),
  DropColumn('tax_id', onTable: 'Product'),
  DropColumn('color', onTable: 'Product'),
  DropColumn('business_id', onTable: 'Product'),
  DropColumn('branch_id', onTable: 'Product'),
  DropColumn('supplier_id', onTable: 'Product'),
  DropColumn('category_id', onTable: 'Product'),
  DropColumn('created_at', onTable: 'Product'),
  DropColumn('unit', onTable: 'Product'),
  DropColumn('image_url', onTable: 'Product'),
  DropColumn('expiry_date', onTable: 'Product'),
  DropColumn('bar_code', onTable: 'Product'),
  DropColumn('nfc_enabled', onTable: 'Product'),
  DropColumn('binded_to_tenant_id', onTable: 'Product'),
  DropColumn('is_favorite', onTable: 'Product'),
  DropColumn('last_touched', onTable: 'Product'),
  DropColumn('deleted_at', onTable: 'Product'),
  DropColumn('spplr_nm', onTable: 'Product'),
  DropColumn('is_composite', onTable: 'Product'),
  DropColumn('id', onTable: 'Stock'),
  DropColumn('tin', onTable: 'Stock'),
  DropColumn('bhf_id', onTable: 'Stock'),
  DropColumn('branch_id', onTable: 'Stock'),
  DropColumn('variant_id', onTable: 'Stock'),
  DropColumn('current_stock', onTable: 'Stock'),
  DropColumn('low_stock', onTable: 'Stock'),
  DropColumn('can_tracking_stock', onTable: 'Stock'),
  DropColumn('show_low_stock_alert', onTable: 'Stock'),
  DropColumn('product_id', onTable: 'Stock'),
  DropColumn('active', onTable: 'Stock'),
  DropColumn('value', onTable: 'Stock'),
  DropColumn('rsd_qty', onTable: 'Stock'),
  DropColumn('last_touched', onTable: 'Stock'),
  DropColumn('deleted_at', onTable: 'Stock'),
  DropColumn('ebm_synced', onTable: 'Stock'),
  DropColumn('cloud_synced', onTable: 'Stock'),
  DropColumn('initial_stock', onTable: 'Stock'),
  DropColumn('id', onTable: 'Composite'),
  DropColumn('product_id', onTable: 'Composite'),
  DropColumn('variant_id', onTable: 'Composite'),
  DropColumn('qty', onTable: 'Composite'),
  DropColumn('branch_id', onTable: 'Composite'),
  DropColumn('business_id', onTable: 'Composite'),
  DropColumn('actual_price', onTable: 'Composite')
];

//
// DO NOT EDIT BELOW THIS LINE
//

@Migratable(
  version: '20241128071810',
  up: _migration_20241128071810_up,
  down: _migration_20241128071810_down,
)
class Migration20241128071810 extends Migration {
  const Migration20241128071810()
      : super(
          version: 20241128071810,
          up: _migration_20241128071810_up,
          down: _migration_20241128071810_down,
        );
}
