// GENERATED CODE EDIT WITH CAUTION
// THIS FILE **WILL NOT** BE REGENERATED
// This file should be version controlled and can be manually edited.
part of 'schema.g.dart';

// While migrations are intelligently created, the difference between some commands, such as
// DropTable vs. RenameTable, cannot be determined. For this reason, please review migrations after
// they are created to ensure the correct inference was made.

// The migration version must **always** mirror the file name

const List<MigrationCommand> _migration_20241221150100_up = [
  DropColumn('is_tax_exempted', onTable: 'TransactionItem'),
  DropColumn('tax_percentage', onTable: 'Variant'),
  DropColumn('prc', onTable: 'Variant'),
  DropColumn('sply_amt', onTable: 'Variant'),
  DropColumn('dft_prc', onTable: 'Variant'),
  DropColumn('supply_price', onTable: 'Variant'),
  DropColumn('retail_price', onTable: 'Variant'),
  DropColumn('dc_rt', onTable: 'Variant'),
  DropColumn('current_stock', onTable: 'Stock'),
  DropColumn('value', onTable: 'Stock'),
  DropColumn('rsd_qty', onTable: 'Stock'),
  DropColumn('sub_total', onTable: 'ITransaction'),
  DropColumn('customer_change_due', onTable: 'ITransaction'),
  DropColumn('cash_received', onTable: 'ITransaction'),
  InsertTable('Conversation'),
  InsertTable('LPermission'),
  InsertTable('Discount'),
  InsertTable('AppNotification'),
  InsertTable('Token'),
  InsertColumn('current_stock', Column.Double, onTable: 'Stock'),
  InsertColumn('value', Column.Double, onTable: 'Stock'),
  InsertColumn('rsd_qty', Column.Double, onTable: 'Stock'),
  InsertColumn('id', Column.integer, onTable: 'Conversation', unique: true),
  InsertColumn('user_name', Column.varchar, onTable: 'Conversation'),
  InsertColumn('body', Column.varchar, onTable: 'Conversation'),
  InsertColumn('avatar', Column.varchar, onTable: 'Conversation'),
  InsertColumn('channel_type', Column.varchar, onTable: 'Conversation'),
  InsertColumn('from_number', Column.varchar, onTable: 'Conversation'),
  InsertColumn('to_number', Column.varchar, onTable: 'Conversation'),
  InsertColumn('created_at', Column.varchar, onTable: 'Conversation'),
  InsertColumn('message_type', Column.varchar, onTable: 'Conversation'),
  InsertColumn('phone_number_id', Column.varchar, onTable: 'Conversation'),
  InsertColumn('message_id', Column.varchar, onTable: 'Conversation'),
  InsertColumn('responded_by', Column.varchar, onTable: 'Conversation'),
  InsertColumn('conversation_id', Column.varchar, onTable: 'Conversation'),
  InsertColumn('business_phone_number', Column.varchar, onTable: 'Conversation'),
  InsertColumn('business_id', Column.integer, onTable: 'Conversation'),
  InsertColumn('scheduled_at', Column.datetime, onTable: 'Conversation'),
  InsertColumn('delivered', Column.boolean, onTable: 'Conversation'),
  InsertColumn('last_touched', Column.datetime, onTable: 'Conversation'),
  InsertColumn('deleted_at', Column.datetime, onTable: 'Conversation'),
  InsertColumn('sub_total', Column.Double, onTable: 'ITransaction'),
  InsertColumn('cash_received', Column.Double, onTable: 'ITransaction'),
  InsertColumn('customer_change_due', Column.Double, onTable: 'ITransaction'),
  InsertColumn('id', Column.integer, onTable: 'LPermission', unique: true),
  InsertColumn('name', Column.varchar, onTable: 'LPermission'),
  InsertColumn('user_id', Column.integer, onTable: 'LPermission'),
  InsertColumn('tax_percentage', Column.Double, onTable: 'Variant'),
  InsertColumn('prc', Column.Double, onTable: 'Variant'),
  InsertColumn('sply_amt', Column.Double, onTable: 'Variant'),
  InsertColumn('dft_prc', Column.Double, onTable: 'Variant'),
  InsertColumn('supply_price', Column.Double, onTable: 'Variant'),
  InsertColumn('retail_price', Column.Double, onTable: 'Variant'),
  InsertColumn('dc_rt', Column.Double, onTable: 'Variant'),
  InsertColumn('id', Column.integer, onTable: 'Discount', unique: true),
  InsertColumn('name', Column.varchar, onTable: 'Discount'),
  InsertColumn('amount', Column.Double, onTable: 'Discount'),
  InsertColumn('branch_id', Column.integer, onTable: 'Discount'),
  InsertColumn('id', Column.integer, onTable: 'AppNotification', unique: true),
  InsertColumn('identifier', Column.varchar, onTable: 'AppNotification'),
  InsertColumn('type', Column.varchar, onTable: 'AppNotification'),
  InsertColumn('message', Column.varchar, onTable: 'AppNotification'),
  InsertColumn('created_at', Column.datetime, onTable: 'AppNotification'),
  InsertColumn('id', Column.integer, onTable: 'Token', unique: true),
  InsertColumn('name', Column.varchar, onTable: 'Token'),
  InsertColumn('type', Column.varchar, onTable: 'Token'),
  InsertColumn('token', Column.varchar, onTable: 'Token'),
  InsertColumn('valid_from', Column.datetime, onTable: 'Token'),
  InsertColumn('valid_until', Column.datetime, onTable: 'Token'),
  InsertColumn('business_id', Column.integer, onTable: 'Token'),
  InsertColumn('last_touched', Column.datetime, onTable: 'Token'),
  InsertColumn('search_match', Column.boolean, onTable: 'Product')
];

const List<MigrationCommand> _migration_20241221150100_down = [
  DropTable('Conversation'),
  DropTable('LPermission'),
  DropTable('Discount'),
  DropTable('AppNotification'),
  DropTable('Token'),
  DropColumn('current_stock', onTable: 'Stock'),
  DropColumn('value', onTable: 'Stock'),
  DropColumn('rsd_qty', onTable: 'Stock'),
  DropColumn('id', onTable: 'Conversation'),
  DropColumn('user_name', onTable: 'Conversation'),
  DropColumn('body', onTable: 'Conversation'),
  DropColumn('avatar', onTable: 'Conversation'),
  DropColumn('channel_type', onTable: 'Conversation'),
  DropColumn('from_number', onTable: 'Conversation'),
  DropColumn('to_number', onTable: 'Conversation'),
  DropColumn('created_at', onTable: 'Conversation'),
  DropColumn('message_type', onTable: 'Conversation'),
  DropColumn('phone_number_id', onTable: 'Conversation'),
  DropColumn('message_id', onTable: 'Conversation'),
  DropColumn('responded_by', onTable: 'Conversation'),
  DropColumn('conversation_id', onTable: 'Conversation'),
  DropColumn('business_phone_number', onTable: 'Conversation'),
  DropColumn('business_id', onTable: 'Conversation'),
  DropColumn('scheduled_at', onTable: 'Conversation'),
  DropColumn('delivered', onTable: 'Conversation'),
  DropColumn('last_touched', onTable: 'Conversation'),
  DropColumn('deleted_at', onTable: 'Conversation'),
  DropColumn('sub_total', onTable: 'ITransaction'),
  DropColumn('cash_received', onTable: 'ITransaction'),
  DropColumn('customer_change_due', onTable: 'ITransaction'),
  DropColumn('id', onTable: 'LPermission'),
  DropColumn('name', onTable: 'LPermission'),
  DropColumn('user_id', onTable: 'LPermission'),
  DropColumn('tax_percentage', onTable: 'Variant'),
  DropColumn('prc', onTable: 'Variant'),
  DropColumn('sply_amt', onTable: 'Variant'),
  DropColumn('dft_prc', onTable: 'Variant'),
  DropColumn('supply_price', onTable: 'Variant'),
  DropColumn('retail_price', onTable: 'Variant'),
  DropColumn('dc_rt', onTable: 'Variant'),
  DropColumn('id', onTable: 'Discount'),
  DropColumn('name', onTable: 'Discount'),
  DropColumn('amount', onTable: 'Discount'),
  DropColumn('branch_id', onTable: 'Discount'),
  DropColumn('id', onTable: 'AppNotification'),
  DropColumn('identifier', onTable: 'AppNotification'),
  DropColumn('type', onTable: 'AppNotification'),
  DropColumn('message', onTable: 'AppNotification'),
  DropColumn('created_at', onTable: 'AppNotification'),
  DropColumn('id', onTable: 'Token'),
  DropColumn('name', onTable: 'Token'),
  DropColumn('type', onTable: 'Token'),
  DropColumn('token', onTable: 'Token'),
  DropColumn('valid_from', onTable: 'Token'),
  DropColumn('valid_until', onTable: 'Token'),
  DropColumn('business_id', onTable: 'Token'),
  DropColumn('last_touched', onTable: 'Token'),
  DropColumn('search_match', onTable: 'Product')
];

//
// DO NOT EDIT BELOW THIS LINE
//

@Migratable(
  version: '20241221150100',
  up: _migration_20241221150100_up,
  down: _migration_20241221150100_down,
)
class Migration20241221150100 extends Migration {
  const Migration20241221150100()
    : super(
        version: 20241221150100,
        up: _migration_20241221150100_up,
        down: _migration_20241221150100_down,
      );
}
