// GENERATED CODE EDIT WITH CAUTION
// THIS FILE **WILL NOT** BE REGENERATED
// This file should be version controlled and can be manually edited.
part of 'schema.g.dart';

// While migrations are intelligently created, the difference between some commands, such as
// DropTable vs. RenameTable, cannot be determined. For this reason, please review migrations after
// they are created to ensure the correct inference was made.

// The migration version must **always** mirror the file name

const List<MigrationCommand> _migration_20250101092622_up = [
  InsertTable('ItemCode'),
  InsertTable('Stock'),
  InsertTable('Counter'),
  InsertTable('Category'),
  InsertTable('UnversalProduct'),
  InsertTable('Conversation'),
  InsertTable('ITransaction'),
  InsertTable('Configurations'),
  InsertTable('Branch'),
  InsertTable('PlanAddon'),
  InsertTable('PColor'),
  InsertTable('TransactionItem'),
  InsertTable('LPermission'),
  InsertTable('Variant'),
  InsertTable('Device'),
  InsertTable('Favorite'),
  InsertTable('Composite'),
  InsertTable('TransactionPaymentRecord'),
  InsertTable('Setting'),
  InsertTable('Tenant'),
  InsertTable('Pin'),
  InsertTable('Access'),
  InsertTable('Customer'),
  InsertTable('Report'),
  InsertTable('_brick_StockRequest_items'),
  InsertTable('StockRequest'),
  InsertTable('AppNotification'),
  InsertTable('Discount'),
  InsertTable('Business'),
  InsertTable('SKU'),
  InsertTable('IUnit'),
  InsertTable('Location'),
  InsertTable('Receipt'),
  InsertTable('Token'),
  InsertTable('Ebm'),
  InsertTable('_brick_Product_composites'),
  InsertTable('Product'),
  InsertTable('Assets'),
  InsertTable('_brick_Plan_addons'),
  InsertTable('Plan'),
  InsertTable('Drawers'),
  InsertColumn('id', Column.varchar, onTable: 'ItemCode', unique: true),
  InsertColumn('code', Column.varchar, onTable: 'ItemCode'),
  InsertColumn('created_at', Column.datetime, onTable: 'ItemCode'),
  InsertColumn('id', Column.varchar, onTable: 'Stock', unique: true),
  InsertColumn('tin', Column.integer, onTable: 'Stock'),
  InsertColumn('bhf_id', Column.varchar, onTable: 'Stock'),
  InsertColumn('branch_id', Column.integer, onTable: 'Stock'),
  InsertColumn('current_stock', Column.Double, onTable: 'Stock'),
  InsertColumn('low_stock', Column.Double, onTable: 'Stock'),
  InsertColumn('can_tracking_stock', Column.boolean, onTable: 'Stock'),
  InsertColumn('show_low_stock_alert', Column.boolean, onTable: 'Stock'),
  InsertColumn('active', Column.boolean, onTable: 'Stock'),
  InsertColumn('value', Column.Double, onTable: 'Stock'),
  InsertColumn('rsd_qty', Column.Double, onTable: 'Stock'),
  InsertColumn('last_touched', Column.datetime, onTable: 'Stock'),
  InsertColumn('ebm_synced', Column.boolean, onTable: 'Stock'),
  InsertColumn('initial_stock', Column.Double, onTable: 'Stock'),
  InsertColumn('id', Column.varchar, onTable: 'Counter', unique: true),
  InsertColumn('business_id', Column.integer, onTable: 'Counter'),
  InsertColumn('branch_id', Column.integer, onTable: 'Counter'),
  InsertColumn('receipt_type', Column.varchar, onTable: 'Counter'),
  InsertColumn('tot_rcpt_no', Column.integer, onTable: 'Counter'),
  InsertColumn('cur_rcpt_no', Column.integer, onTable: 'Counter'),
  InsertColumn('invc_no', Column.integer, onTable: 'Counter'),
  InsertColumn('last_touched', Column.datetime, onTable: 'Counter'),
  InsertColumn('created_at', Column.datetime, onTable: 'Counter'),
  InsertColumn('id', Column.varchar, onTable: 'Category', unique: true),
  InsertColumn('active', Column.boolean, onTable: 'Category'),
  InsertColumn('focused', Column.boolean, onTable: 'Category'),
  InsertColumn('name', Column.varchar, onTable: 'Category'),
  InsertColumn('branch_id', Column.integer, onTable: 'Category'),
  InsertColumn('deleted_at', Column.datetime, onTable: 'Category'),
  InsertColumn('last_touched', Column.datetime, onTable: 'Category'),
  InsertColumn('id', Column.varchar, onTable: 'UnversalProduct', unique: true),
  InsertColumn('item_cls_cd', Column.varchar, onTable: 'UnversalProduct'),
  InsertColumn('item_cls_nm', Column.varchar, onTable: 'UnversalProduct'),
  InsertColumn('item_cls_lvl', Column.integer, onTable: 'UnversalProduct'),
  InsertColumn('tax_ty_cd', Column.varchar, onTable: 'UnversalProduct'),
  InsertColumn('mjr_tg_yn', Column.varchar, onTable: 'UnversalProduct'),
  InsertColumn('use_yn', Column.varchar, onTable: 'UnversalProduct'),
  InsertColumn('business_id', Column.integer, onTable: 'UnversalProduct'),
  InsertColumn('branch_id', Column.integer, onTable: 'UnversalProduct'),
  InsertColumn('id', Column.varchar, onTable: 'Conversation', unique: true),
  InsertColumn('user_name', Column.varchar, onTable: 'Conversation'),
  InsertColumn('body', Column.varchar, onTable: 'Conversation'),
  InsertColumn('avatar', Column.varchar, onTable: 'Conversation'),
  InsertColumn('channel_type', Column.varchar, onTable: 'Conversation'),
  InsertColumn('from_number', Column.varchar, onTable: 'Conversation'),
  InsertColumn('to_number', Column.varchar, onTable: 'Conversation'),
  InsertColumn('created_at', Column.varchar, onTable: 'Conversation'),
  InsertColumn('message_type', Column.varchar, onTable: 'Conversation'),
  InsertColumn('phone_number_id', Column.varchar, onTable: 'Conversation'),
  InsertColumn('message_id', Column.varchar, onTable: 'Conversation'),
  InsertColumn('responded_by', Column.varchar, onTable: 'Conversation'),
  InsertColumn('conversation_id', Column.varchar, onTable: 'Conversation'),
  InsertColumn('business_phone_number', Column.varchar, onTable: 'Conversation'),
  InsertColumn('business_id', Column.integer, onTable: 'Conversation'),
  InsertColumn('scheduled_at', Column.datetime, onTable: 'Conversation'),
  InsertColumn('delivered', Column.boolean, onTable: 'Conversation'),
  InsertColumn('last_touched', Column.datetime, onTable: 'Conversation'),
  InsertColumn('deleted_at', Column.datetime, onTable: 'Conversation'),
  InsertColumn('id', Column.varchar, onTable: 'ITransaction', unique: true),
  InsertColumn('reference', Column.varchar, onTable: 'ITransaction'),
  InsertColumn('category_id', Column.varchar, onTable: 'ITransaction'),
  InsertColumn('transaction_number', Column.varchar, onTable: 'ITransaction'),
  InsertColumn('branch_id', Column.integer, onTable: 'ITransaction'),
  InsertColumn('status', Column.varchar, onTable: 'ITransaction'),
  InsertColumn('transaction_type', Column.varchar, onTable: 'ITransaction'),
  InsertColumn('sub_total', Column.Double, onTable: 'ITransaction'),
  InsertColumn('payment_type', Column.varchar, onTable: 'ITransaction'),
  InsertColumn('cash_received', Column.Double, onTable: 'ITransaction'),
  InsertColumn('customer_change_due', Column.Double, onTable: 'ITransaction'),
  InsertColumn('created_at', Column.varchar, onTable: 'ITransaction'),
  InsertColumn('receipt_type', Column.varchar, onTable: 'ITransaction'),
  InsertColumn('updated_at', Column.varchar, onTable: 'ITransaction'),
  InsertColumn('customer_id', Column.varchar, onTable: 'ITransaction'),
  InsertColumn('customer_type', Column.varchar, onTable: 'ITransaction'),
  InsertColumn('note', Column.varchar, onTable: 'ITransaction'),
  InsertColumn('last_touched', Column.datetime, onTable: 'ITransaction'),
  InsertColumn('ticket_name', Column.varchar, onTable: 'ITransaction'),
  InsertColumn('supplier_id', Column.integer, onTable: 'ITransaction'),
  InsertColumn('ebm_synced', Column.boolean, onTable: 'ITransaction'),
  InsertColumn('is_income', Column.boolean, onTable: 'ITransaction'),
  InsertColumn('is_expense', Column.boolean, onTable: 'ITransaction'),
  InsertColumn('is_refunded', Column.boolean, onTable: 'ITransaction'),
  InsertColumn('customer_name', Column.varchar, onTable: 'ITransaction'),
  InsertColumn('customer_tin', Column.varchar, onTable: 'ITransaction'),
  InsertColumn('remark', Column.varchar, onTable: 'ITransaction'),
  InsertColumn('customer_bhf_id', Column.varchar, onTable: 'ITransaction'),
  InsertColumn('sar_ty_cd', Column.varchar, onTable: 'ITransaction'),
  InsertColumn('receipt_number', Column.integer, onTable: 'ITransaction'),
  InsertColumn('total_receipt_number', Column.integer, onTable: 'ITransaction'),
  InsertColumn('invoice_number', Column.integer, onTable: 'ITransaction'),
  InsertColumn('id', Column.varchar, onTable: 'Configurations', unique: true),
  InsertColumn('tax_type', Column.varchar, onTable: 'Configurations'),
  InsertColumn('tax_percentage', Column.Double, onTable: 'Configurations'),
  InsertColumn('business_id', Column.integer, onTable: 'Configurations'),
  InsertColumn('branch_id', Column.integer, onTable: 'Configurations'),
  InsertColumn('id', Column.varchar, onTable: 'Branch', unique: true),
  InsertColumn('name', Column.varchar, onTable: 'Branch'),
  InsertColumn('server_id', Column.integer, onTable: 'Branch'),
  InsertColumn('location', Column.varchar, onTable: 'Branch'),
  InsertColumn('description', Column.varchar, onTable: 'Branch'),
  InsertColumn('active', Column.boolean, onTable: 'Branch'),
  InsertColumn('business_id', Column.integer, onTable: 'Branch'),
  InsertColumn('latitude', Column.varchar, onTable: 'Branch'),
  InsertColumn('longitude', Column.varchar, onTable: 'Branch'),
  InsertColumn('is_default', Column.boolean, onTable: 'Branch'),
  InsertColumn('is_online', Column.boolean, onTable: 'Branch'),
  InsertColumn('id', Column.varchar, onTable: 'PlanAddon', unique: true),
  InsertColumn('plan_id', Column.integer, onTable: 'PlanAddon'),
  InsertColumn('addon_name', Column.varchar, onTable: 'PlanAddon'),
  InsertColumn('created_at', Column.datetime, onTable: 'PlanAddon'),
  InsertColumn('id', Column.varchar, onTable: 'PColor', unique: true),
  InsertColumn('name', Column.varchar, onTable: 'PColor'),
  InsertColumn('branch_id', Column.integer, onTable: 'PColor'),
  InsertColumn('active', Column.boolean, onTable: 'PColor'),
  InsertColumn('last_touched', Column.datetime, onTable: 'PColor'),
  InsertColumn('deleted_at', Column.datetime, onTable: 'PColor'),
  InsertColumn('id', Column.varchar, onTable: 'TransactionItem', unique: true),
  InsertColumn('name', Column.varchar, onTable: 'TransactionItem'),
  InsertColumn('quantity_requested', Column.integer, onTable: 'TransactionItem'),
  InsertColumn('quantity_approved', Column.integer, onTable: 'TransactionItem'),
  InsertColumn('quantity_shipped', Column.integer, onTable: 'TransactionItem'),
  InsertColumn('transaction_id', Column.varchar, onTable: 'TransactionItem'),
  InsertColumn('variant_id', Column.varchar, onTable: 'TransactionItem'),
  InsertColumn('qty', Column.Double, onTable: 'TransactionItem'),
  InsertColumn('price', Column.Double, onTable: 'TransactionItem'),
  InsertColumn('discount', Column.Double, onTable: 'TransactionItem'),
  InsertColumn('type', Column.varchar, onTable: 'TransactionItem'),
  InsertColumn('remaining_stock', Column.Double, onTable: 'TransactionItem'),
  InsertColumn('created_at', Column.varchar, onTable: 'TransactionItem'),
  InsertColumn('updated_at', Column.varchar, onTable: 'TransactionItem'),
  InsertColumn('is_refunded', Column.boolean, onTable: 'TransactionItem'),
  InsertColumn('done_with_transaction', Column.boolean, onTable: 'TransactionItem'),
  InsertColumn('active', Column.boolean, onTable: 'TransactionItem'),
  InsertColumn('dc_rt', Column.Double, onTable: 'TransactionItem'),
  InsertColumn('dc_amt', Column.Double, onTable: 'TransactionItem'),
  InsertColumn('taxbl_amt', Column.Double, onTable: 'TransactionItem'),
  InsertColumn('tax_amt', Column.Double, onTable: 'TransactionItem'),
  InsertColumn('tot_amt', Column.Double, onTable: 'TransactionItem'),
  InsertColumn('item_seq', Column.integer, onTable: 'TransactionItem'),
  InsertColumn('isrcc_cd', Column.varchar, onTable: 'TransactionItem'),
  InsertColumn('isrcc_nm', Column.varchar, onTable: 'TransactionItem'),
  InsertColumn('isrc_rt', Column.integer, onTable: 'TransactionItem'),
  InsertColumn('isrc_amt', Column.integer, onTable: 'TransactionItem'),
  InsertColumn('tax_ty_cd', Column.varchar, onTable: 'TransactionItem'),
  InsertColumn('bcd', Column.varchar, onTable: 'TransactionItem'),
  InsertColumn('item_cls_cd', Column.varchar, onTable: 'TransactionItem'),
  InsertColumn('item_ty_cd', Column.varchar, onTable: 'TransactionItem'),
  InsertColumn('item_std_nm', Column.varchar, onTable: 'TransactionItem'),
  InsertColumn('orgn_nat_cd', Column.varchar, onTable: 'TransactionItem'),
  InsertColumn('pkg', Column.varchar, onTable: 'TransactionItem'),
  InsertColumn('item_cd', Column.varchar, onTable: 'TransactionItem'),
  InsertColumn('pkg_unit_cd', Column.varchar, onTable: 'TransactionItem'),
  InsertColumn('qty_unit_cd', Column.varchar, onTable: 'TransactionItem'),
  InsertColumn('item_nm', Column.varchar, onTable: 'TransactionItem'),
  InsertColumn('prc', Column.Double, onTable: 'TransactionItem'),
  InsertColumn('sply_amt', Column.Double, onTable: 'TransactionItem'),
  InsertColumn('tin', Column.integer, onTable: 'TransactionItem'),
  InsertColumn('bhf_id', Column.varchar, onTable: 'TransactionItem'),
  InsertColumn('dft_prc', Column.Double, onTable: 'TransactionItem'),
  InsertColumn('add_info', Column.varchar, onTable: 'TransactionItem'),
  InsertColumn('isrc_aplcb_yn', Column.varchar, onTable: 'TransactionItem'),
  InsertColumn('use_yn', Column.varchar, onTable: 'TransactionItem'),
  InsertColumn('regr_id', Column.varchar, onTable: 'TransactionItem'),
  InsertColumn('regr_nm', Column.varchar, onTable: 'TransactionItem'),
  InsertColumn('modr_id', Column.varchar, onTable: 'TransactionItem'),
  InsertColumn('modr_nm', Column.varchar, onTable: 'TransactionItem'),
  InsertColumn('last_touched', Column.datetime, onTable: 'TransactionItem'),
  InsertColumn('branch_id', Column.integer, onTable: 'TransactionItem'),
  InsertColumn('ebm_synced', Column.boolean, onTable: 'TransactionItem'),
  InsertColumn('part_of_composite', Column.boolean, onTable: 'TransactionItem'),
  InsertColumn('composite_price', Column.Double, onTable: 'TransactionItem'),
  InsertColumn('id', Column.varchar, onTable: 'LPermission', unique: true),
  InsertColumn('name', Column.varchar, onTable: 'LPermission'),
  InsertColumn('user_id', Column.integer, onTable: 'LPermission'),
  InsertColumn('id', Column.varchar, onTable: 'Variant', unique: true),
  InsertForeignKey('Variant', 'Stock', foreignKeyColumn: 'stock_Stock_brick_id', onDeleteCascade: false, onDeleteSetDefault: false),
  InsertColumn('stock_id', Column.varchar, onTable: 'Variant'),
  InsertColumn('tax_percentage', Column.num, onTable: 'Variant'),
  InsertColumn('name', Column.varchar, onTable: 'Variant'),
  InsertColumn('color', Column.varchar, onTable: 'Variant'),
  InsertColumn('sku', Column.varchar, onTable: 'Variant'),
  InsertColumn('product_id', Column.varchar, onTable: 'Variant'),
  InsertColumn('unit', Column.varchar, onTable: 'Variant'),
  InsertColumn('product_name', Column.varchar, onTable: 'Variant'),
  InsertColumn('branch_id', Column.integer, onTable: 'Variant'),
  InsertColumn('tax_name', Column.varchar, onTable: 'Variant'),
  InsertColumn('item_seq', Column.integer, onTable: 'Variant'),
  InsertColumn('isrcc_cd', Column.varchar, onTable: 'Variant'),
  InsertColumn('isrcc_nm', Column.varchar, onTable: 'Variant'),
  InsertColumn('isrc_rt', Column.integer, onTable: 'Variant'),
  InsertColumn('isrc_amt', Column.integer, onTable: 'Variant'),
  InsertColumn('tax_ty_cd', Column.varchar, onTable: 'Variant'),
  InsertColumn('bcd', Column.varchar, onTable: 'Variant'),
  InsertColumn('item_cls_cd', Column.varchar, onTable: 'Variant'),
  InsertColumn('item_ty_cd', Column.varchar, onTable: 'Variant'),
  InsertColumn('item_std_nm', Column.varchar, onTable: 'Variant'),
  InsertColumn('orgn_nat_cd', Column.varchar, onTable: 'Variant'),
  InsertColumn('pkg', Column.varchar, onTable: 'Variant'),
  InsertColumn('item_cd', Column.varchar, onTable: 'Variant'),
  InsertColumn('pkg_unit_cd', Column.varchar, onTable: 'Variant'),
  InsertColumn('qty_unit_cd', Column.varchar, onTable: 'Variant'),
  InsertColumn('item_nm', Column.varchar, onTable: 'Variant'),
  InsertColumn('prc', Column.Double, onTable: 'Variant'),
  InsertColumn('sply_amt', Column.Double, onTable: 'Variant'),
  InsertColumn('tin', Column.integer, onTable: 'Variant'),
  InsertColumn('bhf_id', Column.varchar, onTable: 'Variant'),
  InsertColumn('dft_prc', Column.Double, onTable: 'Variant'),
  InsertColumn('add_info', Column.varchar, onTable: 'Variant'),
  InsertColumn('isrc_aplcb_yn', Column.varchar, onTable: 'Variant'),
  InsertColumn('use_yn', Column.varchar, onTable: 'Variant'),
  InsertColumn('regr_id', Column.varchar, onTable: 'Variant'),
  InsertColumn('regr_nm', Column.varchar, onTable: 'Variant'),
  InsertColumn('modr_id', Column.varchar, onTable: 'Variant'),
  InsertColumn('modr_nm', Column.varchar, onTable: 'Variant'),
  InsertColumn('last_touched', Column.datetime, onTable: 'Variant'),
  InsertColumn('supply_price', Column.Double, onTable: 'Variant'),
  InsertColumn('retail_price', Column.Double, onTable: 'Variant'),
  InsertColumn('spplr_item_cls_cd', Column.varchar, onTable: 'Variant'),
  InsertColumn('spplr_item_cd', Column.varchar, onTable: 'Variant'),
  InsertColumn('spplr_item_nm', Column.varchar, onTable: 'Variant'),
  InsertColumn('ebm_synced', Column.boolean, onTable: 'Variant'),
  InsertColumn('dc_rt', Column.Double, onTable: 'Variant'),
  InsertColumn('expiration_date', Column.datetime, onTable: 'Variant'),
  InsertColumn('id', Column.varchar, onTable: 'Device', unique: true),
  InsertColumn('linking_code', Column.varchar, onTable: 'Device'),
  InsertColumn('device_name', Column.varchar, onTable: 'Device'),
  InsertColumn('device_version', Column.varchar, onTable: 'Device'),
  InsertColumn('pub_nub_published', Column.boolean, onTable: 'Device'),
  InsertColumn('phone', Column.varchar, onTable: 'Device'),
  InsertColumn('branch_id', Column.integer, onTable: 'Device'),
  InsertColumn('business_id', Column.integer, onTable: 'Device'),
  InsertColumn('user_id', Column.integer, onTable: 'Device'),
  InsertColumn('default_app', Column.varchar, onTable: 'Device'),
  InsertColumn('last_touched', Column.datetime, onTable: 'Device'),
  InsertColumn('deleted_at', Column.datetime, onTable: 'Device'),
  InsertColumn('id', Column.varchar, onTable: 'Favorite', unique: true),
  InsertColumn('fav_index', Column.varchar, onTable: 'Favorite'),
  InsertColumn('product_id', Column.varchar, onTable: 'Favorite'),
  InsertColumn('branch_id', Column.integer, onTable: 'Favorite'),
  InsertColumn('last_touched', Column.datetime, onTable: 'Favorite'),
  InsertColumn('deleted_at', Column.datetime, onTable: 'Favorite'),
  InsertColumn('id', Column.varchar, onTable: 'Composite', unique: true),
  InsertColumn('product_id', Column.varchar, onTable: 'Composite'),
  InsertColumn('variant_id', Column.varchar, onTable: 'Composite'),
  InsertColumn('qty', Column.Double, onTable: 'Composite'),
  InsertColumn('branch_id', Column.integer, onTable: 'Composite'),
  InsertColumn('business_id', Column.integer, onTable: 'Composite'),
  InsertColumn('actual_price', Column.Double, onTable: 'Composite'),
  InsertColumn('id', Column.varchar, onTable: 'TransactionPaymentRecord', unique: true),
  InsertColumn('transaction_id', Column.varchar, onTable: 'TransactionPaymentRecord'),
  InsertColumn('amount', Column.Double, onTable: 'TransactionPaymentRecord'),
  InsertColumn('payment_method', Column.varchar, onTable: 'TransactionPaymentRecord'),
  InsertColumn('created_at', Column.datetime, onTable: 'TransactionPaymentRecord'),
  InsertColumn('id', Column.varchar, onTable: 'Setting', unique: true),
  InsertColumn('email', Column.varchar, onTable: 'Setting'),
  InsertColumn('user_id', Column.integer, onTable: 'Setting'),
  InsertColumn('open_receipt_file_o_sale_complete', Column.boolean, onTable: 'Setting'),
  InsertColumn('auto_print', Column.boolean, onTable: 'Setting'),
  InsertColumn('send_daily_report', Column.boolean, onTable: 'Setting'),
  InsertColumn('default_language', Column.varchar, onTable: 'Setting'),
  InsertColumn('attendnace_doc_created', Column.boolean, onTable: 'Setting'),
  InsertColumn('is_attendance_enabled', Column.boolean, onTable: 'Setting'),
  InsertColumn('type', Column.varchar, onTable: 'Setting'),
  InsertColumn('enrolled_in_bot', Column.boolean, onTable: 'Setting'),
  InsertColumn('device_token', Column.varchar, onTable: 'Setting'),
  InsertColumn('business_phone_number', Column.varchar, onTable: 'Setting'),
  InsertColumn('auto_respond', Column.boolean, onTable: 'Setting'),
  InsertColumn('token', Column.varchar, onTable: 'Setting'),
  InsertColumn('has_pin', Column.boolean, onTable: 'Setting'),
  InsertColumn('business_id', Column.integer, onTable: 'Setting'),
  InsertColumn('created_at', Column.varchar, onTable: 'Setting'),
  InsertColumn('last_touched', Column.datetime, onTable: 'Setting'),
  InsertColumn('deleted_at', Column.datetime, onTable: 'Setting'),
  InsertColumn('id', Column.varchar, onTable: 'Tenant', unique: true),
  InsertColumn('name', Column.varchar, onTable: 'Tenant'),
  InsertColumn('phone_number', Column.varchar, onTable: 'Tenant'),
  InsertColumn('email', Column.varchar, onTable: 'Tenant'),
  InsertColumn('nfc_enabled', Column.boolean, onTable: 'Tenant'),
  InsertColumn('business_id', Column.integer, onTable: 'Tenant'),
  InsertColumn('user_id', Column.integer, onTable: 'Tenant'),
  InsertColumn('image_url', Column.varchar, onTable: 'Tenant'),
  InsertColumn('last_touched', Column.datetime, onTable: 'Tenant'),
  InsertColumn('deleted_at', Column.datetime, onTable: 'Tenant'),
  InsertColumn('pin', Column.integer, onTable: 'Tenant'),
  InsertColumn('session_active', Column.boolean, onTable: 'Tenant'),
  InsertColumn('is_default', Column.boolean, onTable: 'Tenant'),
  InsertColumn('is_long_pressed', Column.boolean, onTable: 'Tenant'),
  InsertColumn('type', Column.varchar, onTable: 'Tenant'),
  InsertColumn('id', Column.varchar, onTable: 'Pin', unique: true),
  InsertColumn('user_id', Column.integer, onTable: 'Pin'),
  InsertColumn('phone_number', Column.varchar, onTable: 'Pin'),
  InsertColumn('pin', Column.integer, onTable: 'Pin'),
  InsertColumn('branch_id', Column.integer, onTable: 'Pin'),
  InsertColumn('business_id', Column.integer, onTable: 'Pin'),
  InsertColumn('owner_name', Column.varchar, onTable: 'Pin'),
  InsertColumn('token_uid', Column.varchar, onTable: 'Pin'),
  InsertColumn('uid', Column.varchar, onTable: 'Pin'),
  InsertColumn('id', Column.varchar, onTable: 'Access', unique: true),
  InsertColumn('branch_id', Column.integer, onTable: 'Access'),
  InsertColumn('business_id', Column.integer, onTable: 'Access'),
  InsertColumn('user_id', Column.integer, onTable: 'Access'),
  InsertColumn('feature_name', Column.varchar, onTable: 'Access'),
  InsertColumn('user_type', Column.varchar, onTable: 'Access'),
  InsertColumn('access_level', Column.varchar, onTable: 'Access'),
  InsertColumn('created_at', Column.datetime, onTable: 'Access'),
  InsertColumn('expires_at', Column.datetime, onTable: 'Access'),
  InsertColumn('status', Column.varchar, onTable: 'Access'),
  InsertColumn('id', Column.varchar, onTable: 'Customer', unique: true),
  InsertColumn('cust_nm', Column.varchar, onTable: 'Customer'),
  InsertColumn('email', Column.varchar, onTable: 'Customer'),
  InsertColumn('tel_no', Column.varchar, onTable: 'Customer'),
  InsertColumn('adrs', Column.varchar, onTable: 'Customer'),
  InsertColumn('branch_id', Column.integer, onTable: 'Customer'),
  InsertColumn('updated_at', Column.datetime, onTable: 'Customer'),
  InsertColumn('cust_no', Column.varchar, onTable: 'Customer'),
  InsertColumn('cust_tin', Column.varchar, onTable: 'Customer'),
  InsertColumn('regr_nm', Column.varchar, onTable: 'Customer'),
  InsertColumn('regr_id', Column.varchar, onTable: 'Customer'),
  InsertColumn('modr_nm', Column.varchar, onTable: 'Customer'),
  InsertColumn('modr_id', Column.varchar, onTable: 'Customer'),
  InsertColumn('ebm_synced', Column.boolean, onTable: 'Customer'),
  InsertColumn('bhf_id', Column.varchar, onTable: 'Customer'),
  InsertColumn('use_yn', Column.varchar, onTable: 'Customer'),
  InsertColumn('customer_type', Column.varchar, onTable: 'Customer'),
  InsertColumn('id', Column.varchar, onTable: 'Report', unique: true),
  InsertColumn('branch_id', Column.integer, onTable: 'Report'),
  InsertColumn('business_id', Column.integer, onTable: 'Report'),
  InsertColumn('filename', Column.varchar, onTable: 'Report'),
  InsertColumn('s3_url', Column.varchar, onTable: 'Report'),
  InsertColumn('downloaded', Column.boolean, onTable: 'Report'),
  InsertForeignKey('_brick_StockRequest_items', 'StockRequest', foreignKeyColumn: 'l_StockRequest_brick_id', onDeleteCascade: true, onDeleteSetDefault: false),
  InsertForeignKey('_brick_StockRequest_items', 'TransactionItem', foreignKeyColumn: 'f_TransactionItem_brick_id', onDeleteCascade: true, onDeleteSetDefault: false),
  InsertColumn('id', Column.varchar, onTable: 'StockRequest', unique: true),
  InsertColumn('main_branch_id', Column.integer, onTable: 'StockRequest'),
  InsertColumn('sub_branch_id', Column.integer, onTable: 'StockRequest'),
  InsertColumn('created_at', Column.datetime, onTable: 'StockRequest'),
  InsertColumn('status', Column.varchar, onTable: 'StockRequest'),
  InsertColumn('delivery_date', Column.datetime, onTable: 'StockRequest'),
  InsertColumn('delivery_note', Column.varchar, onTable: 'StockRequest'),
  InsertColumn('order_note', Column.varchar, onTable: 'StockRequest'),
  InsertColumn('customer_received_order', Column.boolean, onTable: 'StockRequest'),
  InsertColumn('driver_request_delivery_confirmation', Column.boolean, onTable: 'StockRequest'),
  InsertColumn('driver_id', Column.integer, onTable: 'StockRequest'),
  InsertColumn('items', Column.varchar, onTable: 'StockRequest'),
  InsertColumn('updated_at', Column.datetime, onTable: 'StockRequest'),
  InsertColumn('id', Column.varchar, onTable: 'AppNotification', unique: true),
  InsertColumn('type', Column.varchar, onTable: 'AppNotification'),
  InsertColumn('message', Column.varchar, onTable: 'AppNotification'),
  InsertColumn('identifier', Column.integer, onTable: 'AppNotification'),
  InsertColumn('completed', Column.boolean, onTable: 'AppNotification'),
  InsertColumn('id', Column.varchar, onTable: 'Discount', unique: true),
  InsertColumn('name', Column.varchar, onTable: 'Discount'),
  InsertColumn('amount', Column.Double, onTable: 'Discount'),
  InsertColumn('branch_id', Column.integer, onTable: 'Discount'),
  InsertColumn('id', Column.varchar, onTable: 'Business', unique: true),
  InsertColumn('server_id', Column.integer, onTable: 'Business'),
  InsertColumn('name', Column.varchar, onTable: 'Business'),
  InsertColumn('currency', Column.varchar, onTable: 'Business'),
  InsertColumn('category_id', Column.varchar, onTable: 'Business'),
  InsertColumn('latitude', Column.varchar, onTable: 'Business'),
  InsertColumn('longitude', Column.varchar, onTable: 'Business'),
  InsertColumn('user_id', Column.integer, onTable: 'Business'),
  InsertColumn('time_zone', Column.varchar, onTable: 'Business'),
  InsertColumn('country', Column.varchar, onTable: 'Business'),
  InsertColumn('business_url', Column.varchar, onTable: 'Business'),
  InsertColumn('hex_color', Column.varchar, onTable: 'Business'),
  InsertColumn('image_url', Column.varchar, onTable: 'Business'),
  InsertColumn('type', Column.varchar, onTable: 'Business'),
  InsertColumn('active', Column.boolean, onTable: 'Business'),
  InsertColumn('chat_uid', Column.varchar, onTable: 'Business'),
  InsertColumn('metadata', Column.varchar, onTable: 'Business'),
  InsertColumn('role', Column.varchar, onTable: 'Business'),
  InsertColumn('last_seen', Column.integer, onTable: 'Business'),
  InsertColumn('first_name', Column.varchar, onTable: 'Business'),
  InsertColumn('last_name', Column.varchar, onTable: 'Business'),
  InsertColumn('created_at', Column.varchar, onTable: 'Business'),
  InsertColumn('device_token', Column.varchar, onTable: 'Business'),
  InsertColumn('back_up_enabled', Column.boolean, onTable: 'Business'),
  InsertColumn('subscription_plan', Column.varchar, onTable: 'Business'),
  InsertColumn('next_billing_date', Column.varchar, onTable: 'Business'),
  InsertColumn('previous_billing_date', Column.varchar, onTable: 'Business'),
  InsertColumn('is_last_subscription_payment_succeeded', Column.boolean, onTable: 'Business'),
  InsertColumn('backup_file_id', Column.varchar, onTable: 'Business'),
  InsertColumn('email', Column.varchar, onTable: 'Business'),
  InsertColumn('last_db_backup', Column.varchar, onTable: 'Business'),
  InsertColumn('full_name', Column.varchar, onTable: 'Business'),
  InsertColumn('tin_number', Column.integer, onTable: 'Business'),
  InsertColumn('bhf_id', Column.varchar, onTable: 'Business'),
  InsertColumn('dvc_srl_no', Column.varchar, onTable: 'Business'),
  InsertColumn('adrs', Column.varchar, onTable: 'Business'),
  InsertColumn('tax_enabled', Column.boolean, onTable: 'Business'),
  InsertColumn('tax_server_url', Column.varchar, onTable: 'Business'),
  InsertColumn('is_default', Column.boolean, onTable: 'Business'),
  InsertColumn('business_type_id', Column.integer, onTable: 'Business'),
  InsertColumn('last_touched', Column.datetime, onTable: 'Business'),
  InsertColumn('deleted_at', Column.datetime, onTable: 'Business'),
  InsertColumn('encryption_key', Column.varchar, onTable: 'Business'),
  InsertColumn('id', Column.varchar, onTable: 'SKU', unique: true),
  InsertColumn('sku', Column.integer, onTable: 'SKU'),
  InsertColumn('branch_id', Column.integer, onTable: 'SKU'),
  InsertColumn('business_id', Column.integer, onTable: 'SKU'),
  InsertColumn('consumed', Column.boolean, onTable: 'SKU'),
  InsertColumn('id', Column.varchar, onTable: 'IUnit', unique: true),
  InsertColumn('branch_id', Column.integer, onTable: 'IUnit'),
  InsertColumn('name', Column.varchar, onTable: 'IUnit'),
  InsertColumn('value', Column.varchar, onTable: 'IUnit'),
  InsertColumn('active', Column.boolean, onTable: 'IUnit'),
  InsertColumn('last_touched', Column.datetime, onTable: 'IUnit'),
  InsertColumn('created_at', Column.varchar, onTable: 'IUnit'),
  InsertColumn('id', Column.varchar, onTable: 'Location', unique: true),
  InsertColumn('server_id', Column.integer, onTable: 'Location'),
  InsertColumn('active', Column.boolean, onTable: 'Location'),
  InsertColumn('description', Column.varchar, onTable: 'Location'),
  InsertColumn('name', Column.varchar, onTable: 'Location'),
  InsertColumn('business_id', Column.integer, onTable: 'Location'),
  InsertColumn('longitude', Column.varchar, onTable: 'Location'),
  InsertColumn('latitude', Column.varchar, onTable: 'Location'),
  InsertColumn('location', Column.varchar, onTable: 'Location'),
  InsertColumn('is_default', Column.boolean, onTable: 'Location'),
  InsertColumn('last_touched', Column.datetime, onTable: 'Location'),
  InsertColumn('deleted_at', Column.datetime, onTable: 'Location'),
  InsertColumn('is_online', Column.boolean, onTable: 'Location'),
  InsertColumn('id', Column.varchar, onTable: 'Receipt', unique: true),
  InsertColumn('result_cd', Column.varchar, onTable: 'Receipt'),
  InsertColumn('result_msg', Column.varchar, onTable: 'Receipt'),
  InsertColumn('result_dt', Column.varchar, onTable: 'Receipt'),
  InsertColumn('rcpt_no', Column.integer, onTable: 'Receipt'),
  InsertColumn('intrl_data', Column.varchar, onTable: 'Receipt'),
  InsertColumn('rcpt_sign', Column.varchar, onTable: 'Receipt'),
  InsertColumn('tot_rcpt_no', Column.integer, onTable: 'Receipt'),
  InsertColumn('vsdc_rcpt_pbct_date', Column.varchar, onTable: 'Receipt'),
  InsertColumn('sdc_id', Column.varchar, onTable: 'Receipt'),
  InsertColumn('mrc_no', Column.varchar, onTable: 'Receipt'),
  InsertColumn('qr_code', Column.varchar, onTable: 'Receipt'),
  InsertColumn('receipt_type', Column.varchar, onTable: 'Receipt'),
  InsertColumn('branch_id', Column.integer, onTable: 'Receipt'),
  InsertColumn('transaction_id', Column.varchar, onTable: 'Receipt'),
  InsertColumn('last_touched', Column.datetime, onTable: 'Receipt'),
  InsertColumn('invc_no', Column.integer, onTable: 'Receipt'),
  InsertColumn('when_created', Column.datetime, onTable: 'Receipt'),
  InsertColumn('invoice_number', Column.integer, onTable: 'Receipt'),
  InsertColumn('id', Column.varchar, onTable: 'Token', unique: true),
  InsertColumn('name', Column.varchar, onTable: 'Token'),
  InsertColumn('type', Column.varchar, onTable: 'Token'),
  InsertColumn('token', Column.varchar, onTable: 'Token'),
  InsertColumn('valid_from', Column.datetime, onTable: 'Token'),
  InsertColumn('valid_until', Column.datetime, onTable: 'Token'),
  InsertColumn('business_id', Column.integer, onTable: 'Token'),
  InsertColumn('last_touched', Column.datetime, onTable: 'Token'),
  InsertColumn('id', Column.varchar, onTable: 'Ebm', unique: true),
  InsertColumn('bhf_id', Column.varchar, onTable: 'Ebm'),
  InsertColumn('tin_number', Column.integer, onTable: 'Ebm'),
  InsertColumn('dvc_srl_no', Column.varchar, onTable: 'Ebm'),
  InsertColumn('user_id', Column.integer, onTable: 'Ebm'),
  InsertColumn('tax_server_url', Column.varchar, onTable: 'Ebm'),
  InsertColumn('business_id', Column.integer, onTable: 'Ebm'),
  InsertColumn('branch_id', Column.integer, onTable: 'Ebm'),
  InsertColumn('last_touched', Column.datetime, onTable: 'Ebm'),
  InsertForeignKey('_brick_Product_composites', 'Product', foreignKeyColumn: 'l_Product_brick_id', onDeleteCascade: true, onDeleteSetDefault: false),
  InsertForeignKey('_brick_Product_composites', 'Composite', foreignKeyColumn: 'f_Composite_brick_id', onDeleteCascade: true, onDeleteSetDefault: false),
  InsertColumn('id', Column.varchar, onTable: 'Product', unique: true),
  InsertColumn('name', Column.varchar, onTable: 'Product'),
  InsertColumn('description', Column.varchar, onTable: 'Product'),
  InsertColumn('tax_id', Column.varchar, onTable: 'Product'),
  InsertColumn('color', Column.varchar, onTable: 'Product'),
  InsertColumn('business_id', Column.integer, onTable: 'Product'),
  InsertColumn('branch_id', Column.integer, onTable: 'Product'),
  InsertColumn('supplier_id', Column.varchar, onTable: 'Product'),
  InsertColumn('category_id', Column.integer, onTable: 'Product'),
  InsertColumn('created_at', Column.varchar, onTable: 'Product'),
  InsertColumn('unit', Column.varchar, onTable: 'Product'),
  InsertColumn('image_url', Column.varchar, onTable: 'Product'),
  InsertColumn('expiry_date', Column.varchar, onTable: 'Product'),
  InsertColumn('bar_code', Column.varchar, onTable: 'Product'),
  InsertColumn('nfc_enabled', Column.boolean, onTable: 'Product'),
  InsertColumn('binded_to_tenant_id', Column.integer, onTable: 'Product'),
  InsertColumn('is_favorite', Column.boolean, onTable: 'Product'),
  InsertColumn('last_touched', Column.datetime, onTable: 'Product'),
  InsertColumn('spplr_nm', Column.varchar, onTable: 'Product'),
  InsertColumn('is_composite', Column.boolean, onTable: 'Product'),
  InsertColumn('search_match', Column.boolean, onTable: 'Product'),
  InsertColumn('id', Column.varchar, onTable: 'Assets', unique: true),
  InsertColumn('branch_id', Column.integer, onTable: 'Assets'),
  InsertColumn('business_id', Column.integer, onTable: 'Assets'),
  InsertColumn('asset_name', Column.varchar, onTable: 'Assets'),
  InsertColumn('product_id', Column.varchar, onTable: 'Assets'),
  InsertForeignKey('_brick_Plan_addons', 'Plan', foreignKeyColumn: 'l_Plan_brick_id', onDeleteCascade: true, onDeleteSetDefault: false),
  InsertForeignKey('_brick_Plan_addons', 'PlanAddon', foreignKeyColumn: 'f_PlanAddon_brick_id', onDeleteCascade: true, onDeleteSetDefault: false),
  InsertColumn('id', Column.varchar, onTable: 'Plan', unique: true),
  InsertColumn('business_id', Column.integer, onTable: 'Plan'),
  InsertColumn('selected_plan', Column.varchar, onTable: 'Plan'),
  InsertColumn('additional_devices', Column.integer, onTable: 'Plan'),
  InsertColumn('is_yearly_plan', Column.boolean, onTable: 'Plan'),
  InsertColumn('total_price', Column.integer, onTable: 'Plan'),
  InsertColumn('created_at', Column.datetime, onTable: 'Plan'),
  InsertColumn('payment_completed_by_user', Column.boolean, onTable: 'Plan'),
  InsertColumn('rule', Column.varchar, onTable: 'Plan'),
  InsertColumn('payment_method', Column.varchar, onTable: 'Plan'),
  InsertColumn('next_billing_date', Column.datetime, onTable: 'Plan'),
  InsertColumn('number_of_payments', Column.integer, onTable: 'Plan'),
  InsertColumn('id', Column.varchar, onTable: 'Drawers', unique: true),
  InsertColumn('opening_balance', Column.Double, onTable: 'Drawers'),
  InsertColumn('closing_balance', Column.Double, onTable: 'Drawers'),
  InsertColumn('opening_date_time', Column.varchar, onTable: 'Drawers'),
  InsertColumn('closing_date_time', Column.varchar, onTable: 'Drawers'),
  InsertColumn('cs_sale_count', Column.integer, onTable: 'Drawers'),
  InsertColumn('trade_name', Column.varchar, onTable: 'Drawers'),
  InsertColumn('total_ns_sale_income', Column.Double, onTable: 'Drawers'),
  InsertColumn('total_cs_sale_income', Column.Double, onTable: 'Drawers'),
  InsertColumn('nr_sale_count', Column.integer, onTable: 'Drawers'),
  InsertColumn('ns_sale_count', Column.integer, onTable: 'Drawers'),
  InsertColumn('tr_sale_count', Column.integer, onTable: 'Drawers'),
  InsertColumn('ps_sale_count', Column.integer, onTable: 'Drawers'),
  InsertColumn('incomplete_sale', Column.integer, onTable: 'Drawers'),
  InsertColumn('other_transactions', Column.integer, onTable: 'Drawers'),
  InsertColumn('payment_mode', Column.varchar, onTable: 'Drawers'),
  InsertColumn('cashier_id', Column.integer, onTable: 'Drawers'),
  InsertColumn('open', Column.boolean, onTable: 'Drawers'),
  InsertColumn('deleted_at', Column.datetime, onTable: 'Drawers'),
  InsertColumn('business_id', Column.integer, onTable: 'Drawers'),
  InsertColumn('branch_id', Column.integer, onTable: 'Drawers'),
  CreateIndex(columns: ['id'], onTable: 'ItemCode', unique: true),
  CreateIndex(columns: ['code'], onTable: 'ItemCode', unique: false),
  CreateIndex(columns: ['id'], onTable: 'Stock', unique: true),
  CreateIndex(columns: ['id'], onTable: 'Counter', unique: true),
  CreateIndex(columns: ['id'], onTable: 'Category', unique: true),
  CreateIndex(columns: ['id'], onTable: 'UnversalProduct', unique: true),
  CreateIndex(columns: ['id'], onTable: 'Conversation', unique: true),
  CreateIndex(columns: ['id'], onTable: 'ITransaction', unique: true),
  CreateIndex(columns: ['id'], onTable: 'Configurations', unique: true),
  CreateIndex(columns: ['id'], onTable: 'Branch', unique: true),
  CreateIndex(columns: ['id'], onTable: 'PlanAddon', unique: true),
  CreateIndex(columns: ['id'], onTable: 'PColor', unique: true),
  CreateIndex(columns: ['id'], onTable: 'TransactionItem', unique: true),
  CreateIndex(columns: ['id'], onTable: 'LPermission', unique: true),
  CreateIndex(columns: ['id'], onTable: 'Variant', unique: true),
  CreateIndex(columns: ['id'], onTable: 'Device', unique: true),
  CreateIndex(columns: ['id'], onTable: 'Favorite', unique: true),
  CreateIndex(columns: ['id'], onTable: 'Composite', unique: true),
  CreateIndex(columns: ['id'], onTable: 'TransactionPaymentRecord', unique: true),
  CreateIndex(columns: ['id'], onTable: 'Setting', unique: true),
  CreateIndex(columns: ['id'], onTable: 'Tenant', unique: true),
  CreateIndex(columns: ['id'], onTable: 'Pin', unique: true),
  CreateIndex(columns: ['id'], onTable: 'Access', unique: true),
  CreateIndex(columns: ['id'], onTable: 'Customer', unique: true),
  CreateIndex(columns: ['id'], onTable: 'Report', unique: true),
  CreateIndex(columns: ['l_StockRequest_brick_id', 'f_TransactionItem_brick_id'], onTable: '_brick_StockRequest_items', unique: true),
  CreateIndex(columns: ['id'], onTable: 'StockRequest', unique: true),
  CreateIndex(columns: ['id'], onTable: 'AppNotification', unique: true),
  CreateIndex(columns: ['id'], onTable: 'Discount', unique: true),
  CreateIndex(columns: ['id'], onTable: 'Business', unique: true),
  CreateIndex(columns: ['id'], onTable: 'SKU', unique: true),
  CreateIndex(columns: ['id'], onTable: 'IUnit', unique: true),
  CreateIndex(columns: ['id'], onTable: 'Location', unique: true),
  CreateIndex(columns: ['id'], onTable: 'Receipt', unique: true),
  CreateIndex(columns: ['id'], onTable: 'Token', unique: true),
  CreateIndex(columns: ['id'], onTable: 'Ebm', unique: true),
  CreateIndex(columns: ['l_Product_brick_id', 'f_Composite_brick_id'], onTable: '_brick_Product_composites', unique: true),
  CreateIndex(columns: ['id'], onTable: 'Product', unique: true),
  CreateIndex(columns: ['id'], onTable: 'Assets', unique: true),
  CreateIndex(columns: ['l_Plan_brick_id', 'f_PlanAddon_brick_id'], onTable: '_brick_Plan_addons', unique: true),
  CreateIndex(columns: ['id'], onTable: 'Plan', unique: true),
  CreateIndex(columns: ['id'], onTable: 'Drawers', unique: true)
];

const List<MigrationCommand> _migration_20250101092622_down = [
  DropTable('ItemCode'),
  DropTable('Stock'),
  DropTable('Counter'),
  DropTable('Category'),
  DropTable('UnversalProduct'),
  DropTable('Conversation'),
  DropTable('ITransaction'),
  DropTable('Configurations'),
  DropTable('Branch'),
  DropTable('PlanAddon'),
  DropTable('PColor'),
  DropTable('TransactionItem'),
  DropTable('LPermission'),
  DropTable('Variant'),
  DropTable('Device'),
  DropTable('Favorite'),
  DropTable('Composite'),
  DropTable('TransactionPaymentRecord'),
  DropTable('Setting'),
  DropTable('Tenant'),
  DropTable('Pin'),
  DropTable('Access'),
  DropTable('Customer'),
  DropTable('Report'),
  DropTable('_brick_StockRequest_items'),
  DropTable('StockRequest'),
  DropTable('AppNotification'),
  DropTable('Discount'),
  DropTable('Business'),
  DropTable('SKU'),
  DropTable('IUnit'),
  DropTable('Location'),
  DropTable('Receipt'),
  DropTable('Token'),
  DropTable('Ebm'),
  DropTable('_brick_Product_composites'),
  DropTable('Product'),
  DropTable('Assets'),
  DropTable('_brick_Plan_addons'),
  DropTable('Plan'),
  DropTable('Drawers'),
  DropColumn('id', onTable: 'ItemCode'),
  DropColumn('code', onTable: 'ItemCode'),
  DropColumn('created_at', onTable: 'ItemCode'),
  DropColumn('id', onTable: 'Stock'),
  DropColumn('tin', onTable: 'Stock'),
  DropColumn('bhf_id', onTable: 'Stock'),
  DropColumn('branch_id', onTable: 'Stock'),
  DropColumn('current_stock', onTable: 'Stock'),
  DropColumn('low_stock', onTable: 'Stock'),
  DropColumn('can_tracking_stock', onTable: 'Stock'),
  DropColumn('show_low_stock_alert', onTable: 'Stock'),
  DropColumn('active', onTable: 'Stock'),
  DropColumn('value', onTable: 'Stock'),
  DropColumn('rsd_qty', onTable: 'Stock'),
  DropColumn('last_touched', onTable: 'Stock'),
  DropColumn('ebm_synced', onTable: 'Stock'),
  DropColumn('initial_stock', onTable: 'Stock'),
  DropColumn('id', onTable: 'Counter'),
  DropColumn('business_id', onTable: 'Counter'),
  DropColumn('branch_id', onTable: 'Counter'),
  DropColumn('receipt_type', onTable: 'Counter'),
  DropColumn('tot_rcpt_no', onTable: 'Counter'),
  DropColumn('cur_rcpt_no', onTable: 'Counter'),
  DropColumn('invc_no', onTable: 'Counter'),
  DropColumn('last_touched', onTable: 'Counter'),
  DropColumn('created_at', onTable: 'Counter'),
  DropColumn('id', onTable: 'Category'),
  DropColumn('active', onTable: 'Category'),
  DropColumn('focused', onTable: 'Category'),
  DropColumn('name', onTable: 'Category'),
  DropColumn('branch_id', onTable: 'Category'),
  DropColumn('deleted_at', onTable: 'Category'),
  DropColumn('last_touched', onTable: 'Category'),
  DropColumn('id', onTable: 'UnversalProduct'),
  DropColumn('item_cls_cd', onTable: 'UnversalProduct'),
  DropColumn('item_cls_nm', onTable: 'UnversalProduct'),
  DropColumn('item_cls_lvl', onTable: 'UnversalProduct'),
  DropColumn('tax_ty_cd', onTable: 'UnversalProduct'),
  DropColumn('mjr_tg_yn', onTable: 'UnversalProduct'),
  DropColumn('use_yn', onTable: 'UnversalProduct'),
  DropColumn('business_id', onTable: 'UnversalProduct'),
  DropColumn('branch_id', onTable: 'UnversalProduct'),
  DropColumn('id', onTable: 'Conversation'),
  DropColumn('user_name', onTable: 'Conversation'),
  DropColumn('body', onTable: 'Conversation'),
  DropColumn('avatar', onTable: 'Conversation'),
  DropColumn('channel_type', onTable: 'Conversation'),
  DropColumn('from_number', onTable: 'Conversation'),
  DropColumn('to_number', onTable: 'Conversation'),
  DropColumn('created_at', onTable: 'Conversation'),
  DropColumn('message_type', onTable: 'Conversation'),
  DropColumn('phone_number_id', onTable: 'Conversation'),
  DropColumn('message_id', onTable: 'Conversation'),
  DropColumn('responded_by', onTable: 'Conversation'),
  DropColumn('conversation_id', onTable: 'Conversation'),
  DropColumn('business_phone_number', onTable: 'Conversation'),
  DropColumn('business_id', onTable: 'Conversation'),
  DropColumn('scheduled_at', onTable: 'Conversation'),
  DropColumn('delivered', onTable: 'Conversation'),
  DropColumn('last_touched', onTable: 'Conversation'),
  DropColumn('deleted_at', onTable: 'Conversation'),
  DropColumn('id', onTable: 'ITransaction'),
  DropColumn('reference', onTable: 'ITransaction'),
  DropColumn('category_id', onTable: 'ITransaction'),
  DropColumn('transaction_number', onTable: 'ITransaction'),
  DropColumn('branch_id', onTable: 'ITransaction'),
  DropColumn('status', onTable: 'ITransaction'),
  DropColumn('transaction_type', onTable: 'ITransaction'),
  DropColumn('sub_total', onTable: 'ITransaction'),
  DropColumn('payment_type', onTable: 'ITransaction'),
  DropColumn('cash_received', onTable: 'ITransaction'),
  DropColumn('customer_change_due', onTable: 'ITransaction'),
  DropColumn('created_at', onTable: 'ITransaction'),
  DropColumn('receipt_type', onTable: 'ITransaction'),
  DropColumn('updated_at', onTable: 'ITransaction'),
  DropColumn('customer_id', onTable: 'ITransaction'),
  DropColumn('customer_type', onTable: 'ITransaction'),
  DropColumn('note', onTable: 'ITransaction'),
  DropColumn('last_touched', onTable: 'ITransaction'),
  DropColumn('ticket_name', onTable: 'ITransaction'),
  DropColumn('supplier_id', onTable: 'ITransaction'),
  DropColumn('ebm_synced', onTable: 'ITransaction'),
  DropColumn('is_income', onTable: 'ITransaction'),
  DropColumn('is_expense', onTable: 'ITransaction'),
  DropColumn('is_refunded', onTable: 'ITransaction'),
  DropColumn('customer_name', onTable: 'ITransaction'),
  DropColumn('customer_tin', onTable: 'ITransaction'),
  DropColumn('remark', onTable: 'ITransaction'),
  DropColumn('customer_bhf_id', onTable: 'ITransaction'),
  DropColumn('sar_ty_cd', onTable: 'ITransaction'),
  DropColumn('receipt_number', onTable: 'ITransaction'),
  DropColumn('total_receipt_number', onTable: 'ITransaction'),
  DropColumn('invoice_number', onTable: 'ITransaction'),
  DropColumn('id', onTable: 'Configurations'),
  DropColumn('tax_type', onTable: 'Configurations'),
  DropColumn('tax_percentage', onTable: 'Configurations'),
  DropColumn('business_id', onTable: 'Configurations'),
  DropColumn('branch_id', onTable: 'Configurations'),
  DropColumn('id', onTable: 'Branch'),
  DropColumn('name', onTable: 'Branch'),
  DropColumn('server_id', onTable: 'Branch'),
  DropColumn('location', onTable: 'Branch'),
  DropColumn('description', onTable: 'Branch'),
  DropColumn('active', onTable: 'Branch'),
  DropColumn('business_id', onTable: 'Branch'),
  DropColumn('latitude', onTable: 'Branch'),
  DropColumn('longitude', onTable: 'Branch'),
  DropColumn('is_default', onTable: 'Branch'),
  DropColumn('is_online', onTable: 'Branch'),
  DropColumn('id', onTable: 'PlanAddon'),
  DropColumn('plan_id', onTable: 'PlanAddon'),
  DropColumn('addon_name', onTable: 'PlanAddon'),
  DropColumn('created_at', onTable: 'PlanAddon'),
  DropColumn('id', onTable: 'PColor'),
  DropColumn('name', onTable: 'PColor'),
  DropColumn('branch_id', onTable: 'PColor'),
  DropColumn('active', onTable: 'PColor'),
  DropColumn('last_touched', onTable: 'PColor'),
  DropColumn('deleted_at', onTable: 'PColor'),
  DropColumn('id', onTable: 'TransactionItem'),
  DropColumn('name', onTable: 'TransactionItem'),
  DropColumn('quantity_requested', onTable: 'TransactionItem'),
  DropColumn('quantity_approved', onTable: 'TransactionItem'),
  DropColumn('quantity_shipped', onTable: 'TransactionItem'),
  DropColumn('transaction_id', onTable: 'TransactionItem'),
  DropColumn('variant_id', onTable: 'TransactionItem'),
  DropColumn('qty', onTable: 'TransactionItem'),
  DropColumn('price', onTable: 'TransactionItem'),
  DropColumn('discount', onTable: 'TransactionItem'),
  DropColumn('type', onTable: 'TransactionItem'),
  DropColumn('remaining_stock', onTable: 'TransactionItem'),
  DropColumn('created_at', onTable: 'TransactionItem'),
  DropColumn('updated_at', onTable: 'TransactionItem'),
  DropColumn('is_refunded', onTable: 'TransactionItem'),
  DropColumn('done_with_transaction', onTable: 'TransactionItem'),
  DropColumn('active', onTable: 'TransactionItem'),
  DropColumn('dc_rt', onTable: 'TransactionItem'),
  DropColumn('dc_amt', onTable: 'TransactionItem'),
  DropColumn('taxbl_amt', onTable: 'TransactionItem'),
  DropColumn('tax_amt', onTable: 'TransactionItem'),
  DropColumn('tot_amt', onTable: 'TransactionItem'),
  DropColumn('item_seq', onTable: 'TransactionItem'),
  DropColumn('isrcc_cd', onTable: 'TransactionItem'),
  DropColumn('isrcc_nm', onTable: 'TransactionItem'),
  DropColumn('isrc_rt', onTable: 'TransactionItem'),
  DropColumn('isrc_amt', onTable: 'TransactionItem'),
  DropColumn('tax_ty_cd', onTable: 'TransactionItem'),
  DropColumn('bcd', onTable: 'TransactionItem'),
  DropColumn('item_cls_cd', onTable: 'TransactionItem'),
  DropColumn('item_ty_cd', onTable: 'TransactionItem'),
  DropColumn('item_std_nm', onTable: 'TransactionItem'),
  DropColumn('orgn_nat_cd', onTable: 'TransactionItem'),
  DropColumn('pkg', onTable: 'TransactionItem'),
  DropColumn('item_cd', onTable: 'TransactionItem'),
  DropColumn('pkg_unit_cd', onTable: 'TransactionItem'),
  DropColumn('qty_unit_cd', onTable: 'TransactionItem'),
  DropColumn('item_nm', onTable: 'TransactionItem'),
  DropColumn('prc', onTable: 'TransactionItem'),
  DropColumn('sply_amt', onTable: 'TransactionItem'),
  DropColumn('tin', onTable: 'TransactionItem'),
  DropColumn('bhf_id', onTable: 'TransactionItem'),
  DropColumn('dft_prc', onTable: 'TransactionItem'),
  DropColumn('add_info', onTable: 'TransactionItem'),
  DropColumn('isrc_aplcb_yn', onTable: 'TransactionItem'),
  DropColumn('use_yn', onTable: 'TransactionItem'),
  DropColumn('regr_id', onTable: 'TransactionItem'),
  DropColumn('regr_nm', onTable: 'TransactionItem'),
  DropColumn('modr_id', onTable: 'TransactionItem'),
  DropColumn('modr_nm', onTable: 'TransactionItem'),
  DropColumn('last_touched', onTable: 'TransactionItem'),
  DropColumn('branch_id', onTable: 'TransactionItem'),
  DropColumn('ebm_synced', onTable: 'TransactionItem'),
  DropColumn('part_of_composite', onTable: 'TransactionItem'),
  DropColumn('composite_price', onTable: 'TransactionItem'),
  DropColumn('id', onTable: 'LPermission'),
  DropColumn('name', onTable: 'LPermission'),
  DropColumn('user_id', onTable: 'LPermission'),
  DropColumn('id', onTable: 'Variant'),
  DropColumn('stock_Stock_brick_id', onTable: 'Variant'),
  DropColumn('stock_id', onTable: 'Variant'),
  DropColumn('tax_percentage', onTable: 'Variant'),
  DropColumn('name', onTable: 'Variant'),
  DropColumn('color', onTable: 'Variant'),
  DropColumn('sku', onTable: 'Variant'),
  DropColumn('product_id', onTable: 'Variant'),
  DropColumn('unit', onTable: 'Variant'),
  DropColumn('product_name', onTable: 'Variant'),
  DropColumn('branch_id', onTable: 'Variant'),
  DropColumn('tax_name', onTable: 'Variant'),
  DropColumn('item_seq', onTable: 'Variant'),
  DropColumn('isrcc_cd', onTable: 'Variant'),
  DropColumn('isrcc_nm', onTable: 'Variant'),
  DropColumn('isrc_rt', onTable: 'Variant'),
  DropColumn('isrc_amt', onTable: 'Variant'),
  DropColumn('tax_ty_cd', onTable: 'Variant'),
  DropColumn('bcd', onTable: 'Variant'),
  DropColumn('item_cls_cd', onTable: 'Variant'),
  DropColumn('item_ty_cd', onTable: 'Variant'),
  DropColumn('item_std_nm', onTable: 'Variant'),
  DropColumn('orgn_nat_cd', onTable: 'Variant'),
  DropColumn('pkg', onTable: 'Variant'),
  DropColumn('item_cd', onTable: 'Variant'),
  DropColumn('pkg_unit_cd', onTable: 'Variant'),
  DropColumn('qty_unit_cd', onTable: 'Variant'),
  DropColumn('item_nm', onTable: 'Variant'),
  DropColumn('prc', onTable: 'Variant'),
  DropColumn('sply_amt', onTable: 'Variant'),
  DropColumn('tin', onTable: 'Variant'),
  DropColumn('bhf_id', onTable: 'Variant'),
  DropColumn('dft_prc', onTable: 'Variant'),
  DropColumn('add_info', onTable: 'Variant'),
  DropColumn('isrc_aplcb_yn', onTable: 'Variant'),
  DropColumn('use_yn', onTable: 'Variant'),
  DropColumn('regr_id', onTable: 'Variant'),
  DropColumn('regr_nm', onTable: 'Variant'),
  DropColumn('modr_id', onTable: 'Variant'),
  DropColumn('modr_nm', onTable: 'Variant'),
  DropColumn('last_touched', onTable: 'Variant'),
  DropColumn('supply_price', onTable: 'Variant'),
  DropColumn('retail_price', onTable: 'Variant'),
  DropColumn('spplr_item_cls_cd', onTable: 'Variant'),
  DropColumn('spplr_item_cd', onTable: 'Variant'),
  DropColumn('spplr_item_nm', onTable: 'Variant'),
  DropColumn('ebm_synced', onTable: 'Variant'),
  DropColumn('dc_rt', onTable: 'Variant'),
  DropColumn('expiration_date', onTable: 'Variant'),
  DropColumn('id', onTable: 'Device'),
  DropColumn('linking_code', onTable: 'Device'),
  DropColumn('device_name', onTable: 'Device'),
  DropColumn('device_version', onTable: 'Device'),
  DropColumn('pub_nub_published', onTable: 'Device'),
  DropColumn('phone', onTable: 'Device'),
  DropColumn('branch_id', onTable: 'Device'),
  DropColumn('business_id', onTable: 'Device'),
  DropColumn('user_id', onTable: 'Device'),
  DropColumn('default_app', onTable: 'Device'),
  DropColumn('last_touched', onTable: 'Device'),
  DropColumn('deleted_at', onTable: 'Device'),
  DropColumn('id', onTable: 'Favorite'),
  DropColumn('fav_index', onTable: 'Favorite'),
  DropColumn('product_id', onTable: 'Favorite'),
  DropColumn('branch_id', onTable: 'Favorite'),
  DropColumn('last_touched', onTable: 'Favorite'),
  DropColumn('deleted_at', onTable: 'Favorite'),
  DropColumn('id', onTable: 'Composite'),
  DropColumn('product_id', onTable: 'Composite'),
  DropColumn('variant_id', onTable: 'Composite'),
  DropColumn('qty', onTable: 'Composite'),
  DropColumn('branch_id', onTable: 'Composite'),
  DropColumn('business_id', onTable: 'Composite'),
  DropColumn('actual_price', onTable: 'Composite'),
  DropColumn('id', onTable: 'TransactionPaymentRecord'),
  DropColumn('transaction_id', onTable: 'TransactionPaymentRecord'),
  DropColumn('amount', onTable: 'TransactionPaymentRecord'),
  DropColumn('payment_method', onTable: 'TransactionPaymentRecord'),
  DropColumn('created_at', onTable: 'TransactionPaymentRecord'),
  DropColumn('id', onTable: 'Setting'),
  DropColumn('email', onTable: 'Setting'),
  DropColumn('user_id', onTable: 'Setting'),
  DropColumn('open_receipt_file_o_sale_complete', onTable: 'Setting'),
  DropColumn('auto_print', onTable: 'Setting'),
  DropColumn('send_daily_report', onTable: 'Setting'),
  DropColumn('default_language', onTable: 'Setting'),
  DropColumn('attendnace_doc_created', onTable: 'Setting'),
  DropColumn('is_attendance_enabled', onTable: 'Setting'),
  DropColumn('type', onTable: 'Setting'),
  DropColumn('enrolled_in_bot', onTable: 'Setting'),
  DropColumn('device_token', onTable: 'Setting'),
  DropColumn('business_phone_number', onTable: 'Setting'),
  DropColumn('auto_respond', onTable: 'Setting'),
  DropColumn('token', onTable: 'Setting'),
  DropColumn('has_pin', onTable: 'Setting'),
  DropColumn('business_id', onTable: 'Setting'),
  DropColumn('created_at', onTable: 'Setting'),
  DropColumn('last_touched', onTable: 'Setting'),
  DropColumn('deleted_at', onTable: 'Setting'),
  DropColumn('id', onTable: 'Tenant'),
  DropColumn('name', onTable: 'Tenant'),
  DropColumn('phone_number', onTable: 'Tenant'),
  DropColumn('email', onTable: 'Tenant'),
  DropColumn('nfc_enabled', onTable: 'Tenant'),
  DropColumn('business_id', onTable: 'Tenant'),
  DropColumn('user_id', onTable: 'Tenant'),
  DropColumn('image_url', onTable: 'Tenant'),
  DropColumn('last_touched', onTable: 'Tenant'),
  DropColumn('deleted_at', onTable: 'Tenant'),
  DropColumn('pin', onTable: 'Tenant'),
  DropColumn('session_active', onTable: 'Tenant'),
  DropColumn('is_default', onTable: 'Tenant'),
  DropColumn('is_long_pressed', onTable: 'Tenant'),
  DropColumn('type', onTable: 'Tenant'),
  DropColumn('id', onTable: 'Pin'),
  DropColumn('user_id', onTable: 'Pin'),
  DropColumn('phone_number', onTable: 'Pin'),
  DropColumn('pin', onTable: 'Pin'),
  DropColumn('branch_id', onTable: 'Pin'),
  DropColumn('business_id', onTable: 'Pin'),
  DropColumn('owner_name', onTable: 'Pin'),
  DropColumn('token_uid', onTable: 'Pin'),
  DropColumn('uid', onTable: 'Pin'),
  DropColumn('id', onTable: 'Access'),
  DropColumn('branch_id', onTable: 'Access'),
  DropColumn('business_id', onTable: 'Access'),
  DropColumn('user_id', onTable: 'Access'),
  DropColumn('feature_name', onTable: 'Access'),
  DropColumn('user_type', onTable: 'Access'),
  DropColumn('access_level', onTable: 'Access'),
  DropColumn('created_at', onTable: 'Access'),
  DropColumn('expires_at', onTable: 'Access'),
  DropColumn('status', onTable: 'Access'),
  DropColumn('id', onTable: 'Customer'),
  DropColumn('cust_nm', onTable: 'Customer'),
  DropColumn('email', onTable: 'Customer'),
  DropColumn('tel_no', onTable: 'Customer'),
  DropColumn('adrs', onTable: 'Customer'),
  DropColumn('branch_id', onTable: 'Customer'),
  DropColumn('updated_at', onTable: 'Customer'),
  DropColumn('cust_no', onTable: 'Customer'),
  DropColumn('cust_tin', onTable: 'Customer'),
  DropColumn('regr_nm', onTable: 'Customer'),
  DropColumn('regr_id', onTable: 'Customer'),
  DropColumn('modr_nm', onTable: 'Customer'),
  DropColumn('modr_id', onTable: 'Customer'),
  DropColumn('ebm_synced', onTable: 'Customer'),
  DropColumn('bhf_id', onTable: 'Customer'),
  DropColumn('use_yn', onTable: 'Customer'),
  DropColumn('customer_type', onTable: 'Customer'),
  DropColumn('id', onTable: 'Report'),
  DropColumn('branch_id', onTable: 'Report'),
  DropColumn('business_id', onTable: 'Report'),
  DropColumn('filename', onTable: 'Report'),
  DropColumn('s3_url', onTable: 'Report'),
  DropColumn('downloaded', onTable: 'Report'),
  DropColumn('l_StockRequest_brick_id', onTable: '_brick_StockRequest_items'),
  DropColumn('f_TransactionItem_brick_id', onTable: '_brick_StockRequest_items'),
  DropColumn('id', onTable: 'StockRequest'),
  DropColumn('main_branch_id', onTable: 'StockRequest'),
  DropColumn('sub_branch_id', onTable: 'StockRequest'),
  DropColumn('created_at', onTable: 'StockRequest'),
  DropColumn('status', onTable: 'StockRequest'),
  DropColumn('delivery_date', onTable: 'StockRequest'),
  DropColumn('delivery_note', onTable: 'StockRequest'),
  DropColumn('order_note', onTable: 'StockRequest'),
  DropColumn('customer_received_order', onTable: 'StockRequest'),
  DropColumn('driver_request_delivery_confirmation', onTable: 'StockRequest'),
  DropColumn('driver_id', onTable: 'StockRequest'),
  DropColumn('items', onTable: 'StockRequest'),
  DropColumn('updated_at', onTable: 'StockRequest'),
  DropColumn('id', onTable: 'AppNotification'),
  DropColumn('type', onTable: 'AppNotification'),
  DropColumn('message', onTable: 'AppNotification'),
  DropColumn('identifier', onTable: 'AppNotification'),
  DropColumn('completed', onTable: 'AppNotification'),
  DropColumn('id', onTable: 'Discount'),
  DropColumn('name', onTable: 'Discount'),
  DropColumn('amount', onTable: 'Discount'),
  DropColumn('branch_id', onTable: 'Discount'),
  DropColumn('id', onTable: 'Business'),
  DropColumn('server_id', onTable: 'Business'),
  DropColumn('name', onTable: 'Business'),
  DropColumn('currency', onTable: 'Business'),
  DropColumn('category_id', onTable: 'Business'),
  DropColumn('latitude', onTable: 'Business'),
  DropColumn('longitude', onTable: 'Business'),
  DropColumn('user_id', onTable: 'Business'),
  DropColumn('time_zone', onTable: 'Business'),
  DropColumn('country', onTable: 'Business'),
  DropColumn('business_url', onTable: 'Business'),
  DropColumn('hex_color', onTable: 'Business'),
  DropColumn('image_url', onTable: 'Business'),
  DropColumn('type', onTable: 'Business'),
  DropColumn('active', onTable: 'Business'),
  DropColumn('chat_uid', onTable: 'Business'),
  DropColumn('metadata', onTable: 'Business'),
  DropColumn('role', onTable: 'Business'),
  DropColumn('last_seen', onTable: 'Business'),
  DropColumn('first_name', onTable: 'Business'),
  DropColumn('last_name', onTable: 'Business'),
  DropColumn('created_at', onTable: 'Business'),
  DropColumn('device_token', onTable: 'Business'),
  DropColumn('back_up_enabled', onTable: 'Business'),
  DropColumn('subscription_plan', onTable: 'Business'),
  DropColumn('next_billing_date', onTable: 'Business'),
  DropColumn('previous_billing_date', onTable: 'Business'),
  DropColumn('is_last_subscription_payment_succeeded', onTable: 'Business'),
  DropColumn('backup_file_id', onTable: 'Business'),
  DropColumn('email', onTable: 'Business'),
  DropColumn('last_db_backup', onTable: 'Business'),
  DropColumn('full_name', onTable: 'Business'),
  DropColumn('tin_number', onTable: 'Business'),
  DropColumn('bhf_id', onTable: 'Business'),
  DropColumn('dvc_srl_no', onTable: 'Business'),
  DropColumn('adrs', onTable: 'Business'),
  DropColumn('tax_enabled', onTable: 'Business'),
  DropColumn('tax_server_url', onTable: 'Business'),
  DropColumn('is_default', onTable: 'Business'),
  DropColumn('business_type_id', onTable: 'Business'),
  DropColumn('last_touched', onTable: 'Business'),
  DropColumn('deleted_at', onTable: 'Business'),
  DropColumn('encryption_key', onTable: 'Business'),
  DropColumn('id', onTable: 'SKU'),
  DropColumn('sku', onTable: 'SKU'),
  DropColumn('branch_id', onTable: 'SKU'),
  DropColumn('business_id', onTable: 'SKU'),
  DropColumn('consumed', onTable: 'SKU'),
  DropColumn('id', onTable: 'IUnit'),
  DropColumn('branch_id', onTable: 'IUnit'),
  DropColumn('name', onTable: 'IUnit'),
  DropColumn('value', onTable: 'IUnit'),
  DropColumn('active', onTable: 'IUnit'),
  DropColumn('last_touched', onTable: 'IUnit'),
  DropColumn('created_at', onTable: 'IUnit'),
  DropColumn('id', onTable: 'Location'),
  DropColumn('server_id', onTable: 'Location'),
  DropColumn('active', onTable: 'Location'),
  DropColumn('description', onTable: 'Location'),
  DropColumn('name', onTable: 'Location'),
  DropColumn('business_id', onTable: 'Location'),
  DropColumn('longitude', onTable: 'Location'),
  DropColumn('latitude', onTable: 'Location'),
  DropColumn('location', onTable: 'Location'),
  DropColumn('is_default', onTable: 'Location'),
  DropColumn('last_touched', onTable: 'Location'),
  DropColumn('deleted_at', onTable: 'Location'),
  DropColumn('is_online', onTable: 'Location'),
  DropColumn('id', onTable: 'Receipt'),
  DropColumn('result_cd', onTable: 'Receipt'),
  DropColumn('result_msg', onTable: 'Receipt'),
  DropColumn('result_dt', onTable: 'Receipt'),
  DropColumn('rcpt_no', onTable: 'Receipt'),
  DropColumn('intrl_data', onTable: 'Receipt'),
  DropColumn('rcpt_sign', onTable: 'Receipt'),
  DropColumn('tot_rcpt_no', onTable: 'Receipt'),
  DropColumn('vsdc_rcpt_pbct_date', onTable: 'Receipt'),
  DropColumn('sdc_id', onTable: 'Receipt'),
  DropColumn('mrc_no', onTable: 'Receipt'),
  DropColumn('qr_code', onTable: 'Receipt'),
  DropColumn('receipt_type', onTable: 'Receipt'),
  DropColumn('branch_id', onTable: 'Receipt'),
  DropColumn('transaction_id', onTable: 'Receipt'),
  DropColumn('last_touched', onTable: 'Receipt'),
  DropColumn('invc_no', onTable: 'Receipt'),
  DropColumn('when_created', onTable: 'Receipt'),
  DropColumn('invoice_number', onTable: 'Receipt'),
  DropColumn('id', onTable: 'Token'),
  DropColumn('name', onTable: 'Token'),
  DropColumn('type', onTable: 'Token'),
  DropColumn('token', onTable: 'Token'),
  DropColumn('valid_from', onTable: 'Token'),
  DropColumn('valid_until', onTable: 'Token'),
  DropColumn('business_id', onTable: 'Token'),
  DropColumn('last_touched', onTable: 'Token'),
  DropColumn('id', onTable: 'Ebm'),
  DropColumn('bhf_id', onTable: 'Ebm'),
  DropColumn('tin_number', onTable: 'Ebm'),
  DropColumn('dvc_srl_no', onTable: 'Ebm'),
  DropColumn('user_id', onTable: 'Ebm'),
  DropColumn('tax_server_url', onTable: 'Ebm'),
  DropColumn('business_id', onTable: 'Ebm'),
  DropColumn('branch_id', onTable: 'Ebm'),
  DropColumn('last_touched', onTable: 'Ebm'),
  DropColumn('l_Product_brick_id', onTable: '_brick_Product_composites'),
  DropColumn('f_Composite_brick_id', onTable: '_brick_Product_composites'),
  DropColumn('id', onTable: 'Product'),
  DropColumn('name', onTable: 'Product'),
  DropColumn('description', onTable: 'Product'),
  DropColumn('tax_id', onTable: 'Product'),
  DropColumn('color', onTable: 'Product'),
  DropColumn('business_id', onTable: 'Product'),
  DropColumn('branch_id', onTable: 'Product'),
  DropColumn('supplier_id', onTable: 'Product'),
  DropColumn('category_id', onTable: 'Product'),
  DropColumn('created_at', onTable: 'Product'),
  DropColumn('unit', onTable: 'Product'),
  DropColumn('image_url', onTable: 'Product'),
  DropColumn('expiry_date', onTable: 'Product'),
  DropColumn('bar_code', onTable: 'Product'),
  DropColumn('nfc_enabled', onTable: 'Product'),
  DropColumn('binded_to_tenant_id', onTable: 'Product'),
  DropColumn('is_favorite', onTable: 'Product'),
  DropColumn('last_touched', onTable: 'Product'),
  DropColumn('spplr_nm', onTable: 'Product'),
  DropColumn('is_composite', onTable: 'Product'),
  DropColumn('search_match', onTable: 'Product'),
  DropColumn('id', onTable: 'Assets'),
  DropColumn('branch_id', onTable: 'Assets'),
  DropColumn('business_id', onTable: 'Assets'),
  DropColumn('asset_name', onTable: 'Assets'),
  DropColumn('product_id', onTable: 'Assets'),
  DropColumn('l_Plan_brick_id', onTable: '_brick_Plan_addons'),
  DropColumn('f_PlanAddon_brick_id', onTable: '_brick_Plan_addons'),
  DropColumn('id', onTable: 'Plan'),
  DropColumn('business_id', onTable: 'Plan'),
  DropColumn('selected_plan', onTable: 'Plan'),
  DropColumn('additional_devices', onTable: 'Plan'),
  DropColumn('is_yearly_plan', onTable: 'Plan'),
  DropColumn('total_price', onTable: 'Plan'),
  DropColumn('created_at', onTable: 'Plan'),
  DropColumn('payment_completed_by_user', onTable: 'Plan'),
  DropColumn('rule', onTable: 'Plan'),
  DropColumn('payment_method', onTable: 'Plan'),
  DropColumn('next_billing_date', onTable: 'Plan'),
  DropColumn('number_of_payments', onTable: 'Plan'),
  DropColumn('id', onTable: 'Drawers'),
  DropColumn('opening_balance', onTable: 'Drawers'),
  DropColumn('closing_balance', onTable: 'Drawers'),
  DropColumn('opening_date_time', onTable: 'Drawers'),
  DropColumn('closing_date_time', onTable: 'Drawers'),
  DropColumn('cs_sale_count', onTable: 'Drawers'),
  DropColumn('trade_name', onTable: 'Drawers'),
  DropColumn('total_ns_sale_income', onTable: 'Drawers'),
  DropColumn('total_cs_sale_income', onTable: 'Drawers'),
  DropColumn('nr_sale_count', onTable: 'Drawers'),
  DropColumn('ns_sale_count', onTable: 'Drawers'),
  DropColumn('tr_sale_count', onTable: 'Drawers'),
  DropColumn('ps_sale_count', onTable: 'Drawers'),
  DropColumn('incomplete_sale', onTable: 'Drawers'),
  DropColumn('other_transactions', onTable: 'Drawers'),
  DropColumn('payment_mode', onTable: 'Drawers'),
  DropColumn('cashier_id', onTable: 'Drawers'),
  DropColumn('open', onTable: 'Drawers'),
  DropColumn('deleted_at', onTable: 'Drawers'),
  DropColumn('business_id', onTable: 'Drawers'),
  DropColumn('branch_id', onTable: 'Drawers'),
  DropIndex('index_ItemCode_on_id'),
  DropIndex('index_ItemCode_on_code'),
  DropIndex('index_Stock_on_id'),
  DropIndex('index_Counter_on_id'),
  DropIndex('index_Category_on_id'),
  DropIndex('index_UnversalProduct_on_id'),
  DropIndex('index_Conversation_on_id'),
  DropIndex('index_ITransaction_on_id'),
  DropIndex('index_Configurations_on_id'),
  DropIndex('index_Branch_on_id'),
  DropIndex('index_PlanAddon_on_id'),
  DropIndex('index_PColor_on_id'),
  DropIndex('index_TransactionItem_on_id'),
  DropIndex('index_LPermission_on_id'),
  DropIndex('index_Variant_on_id'),
  DropIndex('index_Device_on_id'),
  DropIndex('index_Favorite_on_id'),
  DropIndex('index_Composite_on_id'),
  DropIndex('index_TransactionPaymentRecord_on_id'),
  DropIndex('index_Setting_on_id'),
  DropIndex('index_Tenant_on_id'),
  DropIndex('index_Pin_on_id'),
  DropIndex('index_Access_on_id'),
  DropIndex('index_Customer_on_id'),
  DropIndex('index_Report_on_id'),
  DropIndex('index__brick_StockRequest_items_on_l_StockRequest_brick_id_f_TransactionItem_brick_id'),
  DropIndex('index_StockRequest_on_id'),
  DropIndex('index_AppNotification_on_id'),
  DropIndex('index_Discount_on_id'),
  DropIndex('index_Business_on_id'),
  DropIndex('index_SKU_on_id'),
  DropIndex('index_IUnit_on_id'),
  DropIndex('index_Location_on_id'),
  DropIndex('index_Receipt_on_id'),
  DropIndex('index_Token_on_id'),
  DropIndex('index_Ebm_on_id'),
  DropIndex('index__brick_Product_composites_on_l_Product_brick_id_f_Composite_brick_id'),
  DropIndex('index_Product_on_id'),
  DropIndex('index_Assets_on_id'),
  DropIndex('index__brick_Plan_addons_on_l_Plan_brick_id_f_PlanAddon_brick_id'),
  DropIndex('index_Plan_on_id'),
  DropIndex('index_Drawers_on_id')
];

//
// DO NOT EDIT BELOW THIS LINE
//

@Migratable(
  version: '20250101092622',
  up: _migration_20250101092622_up,
  down: _migration_20250101092622_down,
)
class Migration20250101092622 extends Migration {
  const Migration20250101092622()
    : super(
        version: 20250101092622,
        up: _migration_20250101092622_up,
        down: _migration_20250101092622_down,
      );
}
