import 'package:realm/realm.dart';

part 'realmProduct.g.dart'; // Generated by Realm

@RealmModel()
class _RealmProduct {
  late String id;
  @PrimaryKey()
  @MapTo('_id')
  late ObjectId realmId;

  late String name;
  String? description;
  String? taxId;
  late String color;
  late int businessId;
  late int branchId;
  String? supplierId;
  String? categoryId;
  String? createdAt;
  String? unit;
  String? imageUrl;
  String? expiryDate;

  String? barCode;
  bool? nfcEnabled;
  int? bindedToTenantId;
  bool? isFavorite;

  DateTime? lastTouched;

  late String action;

  DateTime? deletedAt;

  bool? searchMatch;
}
