import 'package:realm/realm.dart';

part 'realmVariant.g.dart'; // Generated by Realm

@RealmModel()
class _RealmVariant {
  late String id;
  @PrimaryKey()
  @MapTo('_id')
  late ObjectId realmId;
  late String name;

  late String color;
  late String sku;
  late String productId;
  late String unit;
  late String productName;
  late int branchId;
  late String? taxName;
  double? taxPercentage;
  late bool isTaxExempted;

  // Additional RRA fields
  String? itemSeq;
  String? isrccCd;
  String? isrccNm;
  String? isrcRt;
  String? isrcAmt;
  String? taxTyCd;
  String? bcd;
  String? itemClsCd;
  String? itemTyCd;
  String? itemStdNm;
  String? orgnNatCd;
  String? pkg;
  String? itemCd;
  String? pkgUnitCd;
  String? qtyUnitCd;
  String? itemNm;
  double? qty;
  double? prc;
  double? splyAmt;
  int? tin;
  String? bhfId;
  double? dftPrc;
  String? addInfo;
  String? isrcAplcbYn;
  String? useYn;
  String? regrId;
  String? regrNm;
  String? modrId;
  String? modrNm;
  double? rsdQty;

  DateTime? lastTouched;

  late double supplyPrice;
  late double retailPrice;

  late String action;

  DateTime? deletedAt;

  // ... constructors and other methods remain the same
}
