import 'package:realm/realm.dart';

part 'realmProduct.realm.dart'; // Generated by Realm

@RealmModel()
class _RealmProduct {
  late int id;
  @PrimaryKey()
  @MapTo('_id')
  late ObjectId realmId;

  late String name;
  String? description;
  String? taxId;
  late String color;
  late int businessId;
  late int branchId;
  String? supplierId;
  int? categoryId;
  String? createdAt;
  String? unit;
  String? imageUrl;
  String? expiryDate;

  String? barCode;
  bool? nfcEnabled;
  int? bindedToTenantId;
  bool? isFavorite;

  DateTime? lastTouched;

  late String action;

  DateTime? deletedAt;

  bool? searchMatch;

  void updateProperties(RealmProduct other) {
    id = other.id;
    name = other.name;
    description = other.description;
    taxId = other.taxId;
    color = other.color;
    businessId = other.businessId;
    branchId = other.branchId;
    supplierId = other.supplierId;
    categoryId = other.categoryId;
    createdAt = other.createdAt;
    unit = other.unit;
    imageUrl = other.imageUrl;
    expiryDate = other.expiryDate;
    barCode = other.barCode;
    nfcEnabled = other.nfcEnabled;
    bindedToTenantId = other.bindedToTenantId;
    isFavorite = other.isFavorite;
    lastTouched = other.lastTouched;
    action = other.action;
    deletedAt = other.deletedAt;
    searchMatch = other.searchMatch;
  }
}
