// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpnbw9i23T0237jgd2ladtPgsGYbmioqA',
    appId: '1:672237316015:web:e289bfb5c92506c1c2715a',
    messagingSenderId: '672237316015',
    projectId: 'yegobox-2ee43',
    authDomain: 'yegobox-2ee43.firebaseapp.com',
    databaseURL: 'https://yegobox-2ee43.firebaseio.com',
    storageBucket: 'yegobox-2ee43.appspot.com',
    measurementId: 'G-88GKL70K3K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCr5bRe4Xi7e-bs6hLpFNWhI76KZLUJBFM',
    appId: '1:672237316015:android:91a268289c17c5a3c2715a',
    messagingSenderId: '672237316015',
    projectId: 'yegobox-2ee43',
    databaseURL: 'https://yegobox-2ee43.firebaseio.com',
    storageBucket: 'yegobox-2ee43.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvEHuiHE_qdeG_QRCV5T__PBjkSkQ-848',
    appId: '1:672237316015:ios:55d0855187d50bfec2715a',
    messagingSenderId: '672237316015',
    projectId: 'yegobox-2ee43',
    databaseURL: 'https://yegobox-2ee43.firebaseio.com',
    storageBucket: 'yegobox-2ee43.appspot.com',
    androidClientId: '672237316015-58kfg9qqcpu1u2iddupui1taf9fsb613.apps.googleusercontent.com',
    iosClientId: '672237316015-9i1pjt8cqo9n0m3lv81tvafbtr6utj9p.apps.googleusercontent.com',
    iosBundleId: 'com.example.flipperAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvEHuiHE_qdeG_QRCV5T__PBjkSkQ-848',
    appId: '1:672237316015:ios:23dcec7a3450cf16c2715a',
    messagingSenderId: '672237316015',
    projectId: 'yegobox-2ee43',
    databaseURL: 'https://yegobox-2ee43.firebaseio.com',
    storageBucket: 'yegobox-2ee43.appspot.com',
    androidClientId: '672237316015-58kfg9qqcpu1u2iddupui1taf9fsb613.apps.googleusercontent.com',
    iosClientId: '672237316015-88tf95e8oacetuenvoaa64tvk1l9r1re.apps.googleusercontent.com',
    iosBundleId: 'rw.flipper',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBq1-prPYQu5MGZerFN2h7OaRYiteSg9e4',
    appId: '1:672237316015:web:e3325a147549a1a1c2715a',
    messagingSenderId: '672237316015',
    projectId: 'yegobox-2ee43',
    authDomain: 'yegobox-2ee43.firebaseapp.com',
    databaseURL: 'https://yegobox-2ee43.firebaseio.com',
    storageBucket: 'yegobox-2ee43.appspot.com',
    measurementId: 'G-SF851KEG51',
  );
}
