import 'package:powersync/powersync.dart';

const String branch_table = 'branch';
const String business_table = 'business';
const String category_table = 'category';
const String counter_table = 'counter';
const String customer_table = 'customer';
const String device_table = 'device';
const String discount_table = 'discount';
const String drawers_table = 'drawers';
const String ebm_table = 'ebm';
const String favorite_table = 'favorite';
const String location_table = 'location';
const String pcolor_table = 'pcolor';
const String product_table = 'product';
const String receipt_table = 'receipt';
const String setting_table = 'setting';
const String stock_table = 'stock';
const String stock_request_table = 'stockRequest';
const String transaction_item_table = 'transactionItem';
const String itransaction_table = 'iTransaction';
const String iunit_table = 'iUnit';
const String voucher_table = 'voucher';
const String tenant_table = 'tenant';
const String pin_table = 'pin';
const String lpermission_table = 'lPermission';
const String token_table = 'token';
const String conversation_table = 'conversation';
const String activity_table = 'activity';
const String unversal_product_table = 'unversalProduct';
const String configurations_table = 'configurations';
const String app_notification_table = 'appNotification';
const String assets_table = 'assets';
const String composite_table = 'composite';
const String sku_table = 'sku';
const String report_table = 'report';
const String computed_table = 'computed';
const String access_table = 'access';
const String payment_plan_table = 'paymentPlan';
const String flipper_sale_compaign_table = 'flipperSaleCompaign';

Schema schema = Schema([
  Table(branch_table, [
    Column.text('name'),
    Column.text('description'),
    Column.integer('business_id'),
    Column.text('longitude'),
    Column.text('latitude'),
    Column.text('location'),
    Column.integer('is_default'),
    Column.text('last_touched'),
    Column.text('action'),
    Column.integer('serverId'),
    Column.text('deleted_at'),
    Column.integer('is_online'),
    Column.text(
      'created_at',
    ),
  ]),
  Table(business_table, [
    Column.text('name'),
    Column.text('currency'),
    Column.text('category_id'),
    Column.text('latitude'),
    Column.text('longitude'),
    Column.integer('user_id'),
    Column.text('time_zone'),
    Column.text('country'),
    Column.text('business_url'),
    Column.text('hex_color'),
    Column.text('image_url'),
    Column.text('type'),
    Column.integer('active'),
    Column.text('chat_uid'),
    Column.text('metadata'),
    Column.text('role'),
    Column.integer('last_seen'),
    Column.text('first_name'),
    Column.text('last_name'),
    Column.text(
      'created_at',
    ),
    Column.text('device_token'),
    Column.integer('back_up_enabled'),
    Column.text('subscription_plan'),
    Column.text('next_billing_date'),
    Column.text('previous_billing_date'),
    Column.integer('is_last_subscription_payment_succeeded'),
    Column.text('backup_file_id'),
    Column.text('email'),
    Column.text('last_db_backup'),
    Column.text('full_name'),
    Column.integer('tin_number'),
    Column.text('bhf_id'),
    Column.text('dvc_srl_no'),
    Column.text('adrs'),
    Column.integer('tax_enabled'),
    Column.text('tax_server_url'),
    Column.integer('is_default'),
    Column.integer('business_type_id'),
    Column.text('last_touched'),
    Column.text('action'),
    Column.text('deleted_at'),
    Column.text('encryption_key'),
  ]),
  Table(category_table, [
    Column.integer('active'),
    Column.integer('focused'),
    Column.text('name'),
    Column.integer('branch_id'),
    Column.text('deleted_at'),
    Column.text('last_touched'),
    Column.text('action'),
    Column.text(
      'created_at',
    ),
  ]),
  Table(counter_table, [
    Column.integer('business_id'),
    Column.integer('branch_id'),
    Column.text('receipt_type'),
    Column.integer('tot_rcpt_no'),
    Column.integer('cur_rcpt_no'),
    Column.integer('invc_no'),
    Column.text('last_touched'),
    Column.text('action'),
    Column.text(
      'created_at',
    ),
  ]),
  Table(customer_table, [
    Column.text('cust_nm'),
    Column.text('email'),
    Column.text('tel_no'),
    Column.text('adrs'),
    Column.integer('branch_id'),
    Column.text('updated_at'),
    Column.text('cust_no'),
    Column.text('cust_tin'),
    Column.text('regn_nm'),
    Column.text('regn_id'),
    Column.text('modr_nm'),
    Column.text('modr_id'),
    Column.integer('ebm_synced'),
    Column.text('last_touched'),
    Column.text('action'),
    Column.text('deleted_at'),
    Column.integer('tin'),
    Column.text('bhf_id'),
    Column.text('use_yn'),
    Column.text('customer_type'),
    Column.text(
      'created_at',
    ),
  ]),
  Table(device_table, [
    Column.text('linking_code'),
    Column.text('device_name'),
    Column.text('device_version'),
    Column.integer('pub_nub_published'),
    Column.text('phone'),
    Column.integer('branch_id'),
    Column.integer('business_id'),
    Column.integer('user_id'),
    Column.text('default_app'),
    Column.text('last_touched'),
    Column.text('deleted_at'),
    Column.text('action'),
    Column.text(
      'created_at',
    ),
  ]),
  Table(discount_table, [
    Column.text('name'),
    Column.real('amount'),
    Column.integer('branch_id'),
    Column.text(
      'created_at',
    ),
  ]),
  Table(drawers_table, [
    Column.real('opening_balance'),
    Column.real('closing_balance'),
    Column.text('opening_date_time'),
    Column.text('closing_date_time'),
    Column.integer('cs_sale_count'),
    Column.text('trade_name'),
    Column.real('total_ns_sale_income'),
    Column.real('total_cs_sale_income'),
    Column.integer('nr_sale_count'),
    Column.integer('ns_sale_count'),
    Column.integer('tr_sale_count'),
    Column.integer('ps_sale_count'),
    Column.integer('incomplete_sale'),
    Column.integer('other_transactions'),
    Column.text('payment_mode'),
    Column.integer('cashier_id'),
    Column.integer('open'),
    Column.text('deleted_at'),
    Column.integer('business_id'),
    Column.integer('branch_id'),
    Column.text(
      'created_at',
    ),
  ]),
  Table(ebm_table, [
    Column.text('bhf_id'),
    Column.integer('tin_number'),
    Column.text('dvc_srl_no'),
    Column.integer('user_id'),
    Column.text('tax_server_url'),
    Column.integer('business_id'),
    Column.integer('branch_id'),
    Column.text('last_touched'),
    Column.text('action'),
    Column.text(
      'created_at',
    ),
  ]),
  Table(favorite_table, [
    Column.integer('fav_index'),
    Column.integer('product_id'),
    Column.integer('branch_id'),
    Column.text('last_touched'),
    Column.text('action'),
    Column.text('deleted_at'),
    Column.text(
      'created_at',
    ),
  ]),
  Table(location_table, [
    Column.integer('server_id'),
    Column.integer('active'),
    Column.text('description'),
    Column.text('name'),
    Column.integer('business_id'),
    Column.text('longitude'),
    Column.text('latitude'),
    Column.text('location'),
    Column.integer('is_default'),
    Column.text('last_touched'),
    Column.text('action'),
    Column.text('deleted_at'),
    Column.integer('is_online'),
    Column.text(
      'created_at',
    ),
  ]),
  Table(pcolor_table, [
    Column.text('name'),
    Column.text('colors'),
    Column.integer('branch_id'),
    Column.integer('active'),
    Column.text('last_touched'),
    Column.text('action'),
    Column.text('deleted_at'),
    Column.text(
      'created_at',
    ),
  ]),
  Table(product_table, [
    Column.text('name'),
    Column.text('description'),
    Column.text('tax_id'),
    Column.text('color'),
    Column.integer('business_id'),
    Column.integer('branch_id'),
    Column.text('supplier_id'),
    Column.integer('category_id'),
    Column.text('unit'),
    Column.text('image_url'),
    Column.text('expiry_date'),
    Column.text('bar_code'),
    Column.integer('nfc_enabled'),
    Column.integer('binded_to_tenant_id'),
    Column.integer('is_favorite'),
    Column.text('last_touched'),
    Column.text('action'),
    Column.text('deleted_at'),
    Column.text('spplr_nm'),
    Column.integer('is_composite'),
    Column.text(
      'created_at',
    ),
  ]),
  Table(receipt_table, [
    Column.text('result_cd'),
    Column.text('result_msg'),
    Column.text('result_dt'),
    Column.integer('rcpt_no'),
    Column.text('intrl_data'),
    Column.text('rcpt_sign'),
    Column.integer('tot_rcpt_no'),
    Column.text('vsdc_rcpt_pbct_date'),
    Column.text('sdc_id'),
    Column.text('mrc_no'),
    Column.text('qr_code'),
    Column.text('receipt_type'),
    Column.integer('branch_id'),
    Column.integer('transaction_id'),
    Column.text('last_touched'),
    Column.text('action'),
    Column.integer('invc_no'),
    Column.text(
      'created_at',
    ),
  ]),
  Table(setting_table, [
    Column.text('email'),
    Column.integer('user_id'),
    Column.integer('open_receipt_file_o_sale_complete'),
    Column.integer('auto_print'),
    Column.integer('send_daily_report'),
    Column.text('default_language'),
    Column.integer('attendnace_doc_created'),
    Column.integer('is_attendance_enabled'),
    Column.text('type'),
    Column.integer('enrolled_in_bot'),
    Column.text('device_token'),
    Column.text('business_phone_number'),
    Column.integer('auto_respond'),
    Column.text('token'),
    Column.integer('has_pin'),
    Column.integer('business_id'),
    Column.text('created_at'),
    Column.text('last_touched'),
    Column.text('deleted_at'),
    Column.text('action'),
  ]),
  Table(stock_table, [
    Column.integer('tin'),
    Column.text('bhf_id'),
    Column.integer('branch_id'),
    Column.integer('variant_id'),
    Column.real('current_stock'),
    Column.real('sold'),
    Column.real('low_stock'),
    Column.integer('can_tracking_stock'),
    Column.integer('show_low_stock_alert'),
    Column.integer('product_id'),
    Column.integer('active'),
    Column.real('value'),
    Column.real('rsd_qty'),
    Column.real('supply_price'),
    Column.real('retail_price'),
    Column.text('last_touched'),
    Column.text('action'),
    Column.text('deleted_at'),
    Column.integer('ebm_synced'),
    Column.text(
      'created_at',
    ),
  ]),
  Table(stock_request_table, [
    Column.integer('main_branch_id'),
    Column.integer('sub_branch_id'),
    Column.text('created_at'),
    Column.text('status'),
    Column.text('delivery_date'),
    Column.text('delivery_note'),
    Column.text('order_note'),
    Column.integer('customer_received_order'),
    Column.integer('driver_request_delivery_confirmation'),
    Column.integer('driver_id'),
    Column.text('updated_at'),
  ]),
  Table(transaction_item_table, [
    Column.text('name'),
    Column.integer('quantity_requested'),
    Column.integer('quantity_approved'),
    Column.integer('quantity_shipped'),
    Column.integer('transaction_id'),
    Column.integer('variant_id'),
    Column.real('qty'),
    Column.real('price'),
    Column.real('discount'),
    Column.text('type'),
    Column.real('remaining_stock'),
    Column.text('updated_at'),
    Column.integer('is_tax_exempted'),
    Column.integer('is_refunded'),
    Column.integer('done_with_transaction'),
    Column.integer('active'),
    Column.real('dc_rt'),
    Column.real('dc_amt'),
    Column.real('taxbl_amt'),
    Column.real('tax_amt'),
    Column.real('tot_amt'),
    Column.integer('item_seq'),
    Column.text('isrcc_cd'),
    Column.text('isrcc_nm'),
    Column.integer('isrc_rt'),
    Column.integer('isrc_amt'),
    Column.text('tax_ty_cd'),
    Column.text('bcd'),
    Column.text('item_cls_cd'),
    Column.text('item_ty_cd'),
    Column.text('item_std_nm'),
    Column.text('orgn_nat_cd'),
    Column.text('pkg'),
    Column.text('item_cd'),
    Column.text('pkg_unit_cd'),
    Column.text('qty_unit_cd'),
    Column.text('item_nm'),
    Column.real('prc'),
    Column.real('sply_amt'),
    Column.integer('tin'),
    Column.text('bhf_id'),
    Column.real('dft_prc'),
    Column.text('add_info'),
    Column.text('isrc_aplcby_yn'),
    Column.text('use_yn'),
    Column.text('regn_id'),
    Column.text('regn_nm'),
    Column.text('modr_id'),
    Column.text('modr_nm'),
    Column.text('last_touched'),
    Column.text('deleted_at'),
    Column.text('action'),
    Column.integer('branch_id'),
    Column.integer('ebm_synced'),
    Column.integer('part_of_composite'),
    Column.real('composite_price'),
    Column.text(
      'created_at',
    ),
  ]),
  Table(itransaction_table, [
    Column.text('reference'),
    Column.text('category_id'),
    Column.text('transaction_number'),
    Column.integer('branch_id'),
    Column.text('status'),
    Column.text('transaction_type'),
    Column.real('sub_total'),
    Column.text('payment_type'),
    Column.real('cash_received'),
    Column.real('customer_change_due'),
    Column.text('receipt_type'),
    Column.text('updated_at'),
    Column.integer('customer_id'),
    Column.text('customer_type'),
    Column.text('note'),
    Column.text('last_touched'),
    Column.text('action'),
    Column.text('ticket_name'),
    Column.text('deleted_at'),
    Column.integer('supplier_id'),
    Column.integer('ebm_synced'),
    Column.text(
      'created_at',
    ),
  ]),
  Table(iunit_table, [
    Column.integer('branch_id'),
    Column.text('name'),
    Column.text('value'),
    Column.integer('active'),
    Column.text('last_touched'),
    Column.text('action'),
    Column.text('created_at'),
    Column.text('deleted_at'),
  ]),
  Table(voucher_table, [
    Column.integer('value'),
    Column.integer('interval'),
    Column.integer('used'),
    Column.integer('used_at'),
    Column.text('descriptor'),
    Column.text(
      'created_at',
    ),
  ]),
  Table(tenant_table, [
    Column.text('name'),
    Column.text('phone_number'),
    Column.text('email'),
    Column.integer('nfc_enabled'),
    Column.integer('business_id'),
    Column.integer('user_id'),
    Column.text('image_url'),
    Column.text('last_touched'),
    Column.text('deleted_at'),
    Column.integer('pin'),
    Column.integer('session_active'),
    Column.integer('is_default'),
    Column.text(
      'created_at',
    ),
  ]),
  Table(pin_table, [
    Column.text('user_id'),
    Column.text('phone_number'),
    Column.integer('pin'),
    Column.integer('branch_id'),
    Column.integer('business_id'),
    Column.text(
      'created_at',
    ),
  ]),
  Table(lpermission_table, [
    Column.text('name'),
    Column.integer('user_id'),
    Column.text(
      'created_at',
    ),
  ]),
  Table(token_table, [
    Column.text('type'),
    Column.text('token'),
    Column.text('valid_from'),
    Column.text('valid_until'),
    Column.integer('business_id'),
    Column.text('last_touched'),
    Column.text('deleted_at'),
    Column.text(
      'created_at',
    ),
  ]),
  Table(conversation_table, [
    Column.text('user_name'),
    Column.text('body'),
    Column.text('avatar'),
    Column.text('channel_type'),
    Column.text('from_number'),
    Column.text('to_number'),
    Column.text('message_type'),
    Column.text('phone_number_id'),
    Column.text('message_id'),
    Column.text('responded_by'),
    Column.text('conversation_id'),
    Column.text('business_phone_number'),
    Column.integer('business_id'),
    Column.text('scheduled_at'),
    Column.integer('delivered'),
    Column.text('last_touched'),
    Column.text('deleted_at'),
    Column.text(
      'created_at',
    ),
  ]),
  Table(activity_table, [
    Column.text('timestamp'),
    Column.text('last_touched'),
    Column.integer('user_id'),
    Column.text('event'),
    // Column.jsonb('details'),
    Column.text('action'),
    Column.text(
      'created_at',
    ),
  ]),
  Table(unversal_product_table, [
    Column.text('item_cls_cd'),
    Column.text('item_cls_nm'),
    Column.integer('item_cls_lvl'),
    Column.text('tax_ty_cd'),
    Column.text('mjr_tg_yn'),
    Column.text('use_yn'),
    Column.integer('business_id'),
    Column.integer('branch_id'),
    Column.text(
      'created_at',
    ),
  ]),
  Table(configurations_table, [
    Column.text('tax_type'),
    Column.real('tax_percentage'),
    Column.integer('business_id'),
    Column.integer('branch_id'),
    Column.text(
      'created_at',
    ),
  ]),
  Table(app_notification_table, [
    Column.integer('completed'),
    Column.text('type'),
    Column.text('message'),
    Column.integer('identifier'),
    Column.text(
      'created_at',
    ),
  ]),
  Table(assets_table, [
    Column.integer('branch_id'),
    Column.integer('business_id'),
    Column.text('asset_name'),
    Column.integer('product_id'),
    Column.text(
      'created_at',
    ),
  ]),
  Table(composite_table, [
    Column.integer('product_id'),
    Column.integer('variant_id'),
    Column.real('qty'),
    Column.integer('branch_id'),
    Column.integer('business_id'),
    Column.real('actual_price'),
    Column.text(
      'created_at',
    ),
  ]),
  Table(sku_table, [
    Column.integer('sku'),
    Column.integer('branch_id'),
    Column.integer('business_id'),
    Column.integer('consumed'),
    Column.text(
      'created_at',
    ),
  ]),
  Table(report_table, [
    Column.integer('branch_id'),
    Column.integer('business_id'),
    Column.text('filename'),
    Column.text('s3_url'),
    Column.integer('downloaded'),
    Column.text(
      'created_at',
    ),
  ]),
  Table(computed_table, [
    Column.integer('branch_id'),
    Column.integer('business_id'),
    Column.real('gross_profit'),
    Column.real('net_profit'),
    Column.real('total_stock_value'),
    Column.real('total_stock_sold_value'),
    Column.real('total_stock_items'),
    Column.text('created_at'),
  ]),
  Table(access_table, [
    Column.integer('branch_id'),
    Column.integer('business_id'),
    Column.integer('user_id'),
    Column.text('feature_name'),
    Column.text('user_type'),
    Column.text('access_level'),
    Column.text('created_at'),
    Column.text('expires_at'),
    Column.text('status'),
  ]),
  Table(payment_plan_table, [
    Column.integer('business_id'),
    Column.text('selected_plan'),
    Column.integer('additional_devices'),
    Column.integer('is_yearly_plan'),
    Column.real('total_price'),
    Column.integer('payment_completed_by_user'),
    Column.integer('paystack_customer_id'),
    Column.text('rule'),
    Column.text('payment_method'),
    Column.text('customer_code'),
    Column.text('paystack_plan_id'),
    Column.text(
      'created_at',
    ),
  ]),
  Table(flipper_sale_compaign_table, [
    Column.integer('compaign_id'),
    Column.integer('discount_rate'),
    Column.text('created_at'),
    Column.text('coupon_code'),
  ]),
]);
