// Mocks generated by Mockito 5.0.8 from annotations
// in flipper/test/helpers/test_helpers.dart.
// Do not manually edit this file.

import 'dart:async' as _i16;
import 'dart:ui' as _i9;

import 'package:firebase_core/firebase_core.dart' as _i10;
import 'package:firebase_messaging/firebase_messaging.dart' as _i31;
import 'package:firebase_messaging_platform_interface/src/notification_settings.dart'
    as _i11;
import 'package:firebase_messaging_platform_interface/src/remote_message.dart'
    as _i32;
import 'package:flipper/stack.dart' as _i13;
import 'package:flipper_models/models/io/branch.dart' as _i17;
import 'package:flipper_models/models/io/business.dart' as _i8;
import 'package:flipper_models/models/io/category.dart' as _i19;
import 'package:flipper_models/models/io/color.dart' as _i18;
import 'package:flipper_models/models/io/customer.dart' as _i25;
import 'package:flipper_models/models/io/discount.dart' as _i26;
import 'package:flipper_models/models/io/login.dart' as _i2;
import 'package:flipper_models/models/io/message.dart' as _i24;
import 'package:flipper_models/models/io/order.dart' as _i6;
import 'package:flipper_models/models/io/order_item.dart' as _i22;
import 'package:flipper_models/models/io/product_sync.dart' as _i5;
import 'package:flipper_models/models/io/profile.dart' as _i28;
import 'package:flipper_models/models/io/setting.dart' as _i23;
import 'package:flipper_models/models/io/spenn.dart' as _i7;
import 'package:flipper_models/models/io/stock_sync.dart' as _i4;
import 'package:flipper_models/models/io/sync.dart' as _i3;
import 'package:flipper_models/models/io/tenant.dart' as _i27;
import 'package:flipper_models/models/io/unit.dart' as _i20;
import 'package:flipper_models/models/io/variant_sync.dart' as _i21;
import 'package:flipper_services/abstractions/api.dart' as _i15;
import 'package:flipper_services/abstractions/location.dart' as _i39;
import 'package:flipper_services/abstractions/remote.dart' as _i30;
import 'package:flipper_services/abstractions/storage.dart' as _i37;
import 'package:flipper_services/app_service.dart' as _i38;
import 'package:flipper_services/keypad_service.dart' as _i34;
import 'package:flipper_services/language_service.dart' as _i29;
import 'package:flipper_services/product_service.dart' as _i33;
import 'package:flipper_services/setting_service.dart' as _i35;
import 'package:flutter/src/animation/curves.dart' as _i43;
import 'package:flutter/src/material/app.dart' as _i36;
import 'package:flutter/src/widgets/framework.dart' as _i41;
import 'package:flutter/src/widgets/navigator.dart' as _i42;
import 'package:get/get_instance/src/bindings_interface.dart' as _i44;
import 'package:get/get_navigation/src/routes/transitions_type.dart' as _i45;
import 'package:logger/src/logger.dart' as _i12;
import 'package:mockito/mockito.dart' as _i1;
import 'package:stacked/src/reactive/reactive_value/reactive_value.dart'
    as _i14;
import 'package:stacked_services/src/navigation_service.dart' as _i40;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeLogin extends _i1.Fake implements _i2.Login {}

class _FakeSyncF extends _i1.Fake implements _i3.SyncF {}

class _FakeStockSync extends _i1.Fake implements _i4.StockSync {}

class _FakeProductSync extends _i1.Fake implements _i5.ProductSync {}

class _FakeOrderFSync extends _i1.Fake implements _i6.OrderFSync {}

class _FakeSpenn extends _i1.Fake implements _i7.Spenn {}

class _FakeBusinessSync extends _i1.Fake implements _i8.BusinessSync {}

class _FakeLocale extends _i1.Fake implements _i9.Locale {}

class _FakeFirebaseApp extends _i1.Fake implements _i10.FirebaseApp {}

class _FakeNotificationSettings extends _i1.Fake
    implements _i11.NotificationSettings {}

class _FakeLogger extends _i1.Fake implements _i12.Logger {}

class _FakeStack<T> extends _i1.Fake implements _i13.Stack<T> {}

class _FakeReactiveValue<T> extends _i1.Fake implements _i14.ReactiveValue<T> {}

/// A class which mocks [Api].
///
/// See the documentation for Mockito's code generation for more information.
class MockApi<T> extends _i1.Mock implements _i15.Api<T> {
  @override
  _i16.Future<_i2.Login> login({String? phone}) =>
      (super.noSuchMethod(Invocation.method(#login, [], {#phone: phone}),
              returnValue: Future<_i2.Login>.value(_FakeLogin()))
          as _i16.Future<_i2.Login>);
  @override
  _i16.Future<List<_i5.ProductSync>> products({int? branchId}) => (super
          .noSuchMethod(Invocation.method(#products, [], {#branchId: branchId}),
              returnValue:
                  Future<List<_i5.ProductSync>>.value(<_i5.ProductSync>[]))
      as _i16.Future<List<_i5.ProductSync>>);
  @override
  _i16.Future<int> signup({Map<dynamic, dynamic>? business}) =>
      (super.noSuchMethod(Invocation.method(#signup, [], {#business: business}),
          returnValue: Future<int>.value(0)) as _i16.Future<int>);
  @override
  _i16.Future<_i3.SyncF> authenticateWithOfflineDb({String? authId}) =>
      (super.noSuchMethod(
          Invocation.method(#authenticateWithOfflineDb, [], {#authId: authId}),
          returnValue:
              Future<_i3.SyncF>.value(_FakeSyncF())) as _i16.Future<_i3.SyncF>);
  @override
  _i16.Future<List<_i8.BusinessSync>> getOnlineBusiness({String? userId}) =>
      (super.noSuchMethod(
              Invocation.method(#getOnlineBusiness, [], {#userId: userId}),
              returnValue:
                  Future<List<_i8.BusinessSync>>.value(<_i8.BusinessSync>[]))
          as _i16.Future<List<_i8.BusinessSync>>);
  @override
  _i16.Future<List<_i8.BusinessSync>> getLocalOrOnlineBusiness(
          {String? userId}) =>
      (super.noSuchMethod(
          Invocation.method(#getLocalOrOnlineBusiness, [], {#userId: userId}),
          returnValue: Future<List<_i8.BusinessSync>>.value(
              <_i8.BusinessSync>[])) as _i16.Future<List<_i8.BusinessSync>>);
  @override
  _i16.Future<List<_i17.BranchSync>> branches({int? businessId}) => (super
      .noSuchMethod(Invocation.method(#branches, [], {#businessId: businessId}),
          returnValue:
              Future<List<_i17.BranchSync>>.value(<_i17.BranchSync>[])) as _i16
      .Future<List<_i17.BranchSync>>);
  @override
  _i16.Future<List<_i17.BranchSync>> getLocalBranches({int? businessId}) =>
      (super.noSuchMethod(
          Invocation.method(#getLocalBranches, [], {#businessId: businessId}),
          returnValue:
              Future<List<_i17.BranchSync>>.value(<_i17.BranchSync>[])) as _i16
          .Future<List<_i17.BranchSync>>);
  @override
  List<_i4.StockSync> stocks({int? productId}) => (super.noSuchMethod(
      Invocation.method(#stocks, [], {#productId: productId}),
      returnValue: <_i4.StockSync>[]) as List<_i4.StockSync>);
  @override
  _i16.Stream<_i4.StockSync> stockByVariantIdStream({int? variantId}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #stockByVariantIdStream, [], {#variantId: variantId}),
              returnValue: Stream<_i4.StockSync>.empty())
          as _i16.Stream<_i4.StockSync>);
  @override
  _i16.Stream<List<_i5.ProductSync>> productStreams({int? branchId}) =>
      (super.noSuchMethod(
              Invocation.method(#productStreams, [], {#branchId: branchId}),
              returnValue: Stream<List<_i5.ProductSync>>.empty())
          as _i16.Stream<List<_i5.ProductSync>>);
  @override
  _i16.Future<_i4.StockSync> stockByVariantId({int? variantId}) =>
      (super.noSuchMethod(
              Invocation.method(#stockByVariantId, [], {#variantId: variantId}),
              returnValue: Future<_i4.StockSync>.value(_FakeStockSync()))
          as _i16.Future<_i4.StockSync>);
  @override
  _i16.Future<List<_i18.PColor>> colors({int? branchId}) =>
      (super.noSuchMethod(Invocation.method(#colors, [], {#branchId: branchId}),
              returnValue: Future<List<_i18.PColor>>.value(<_i18.PColor>[]))
          as _i16.Future<List<_i18.PColor>>);
  @override
  _i16.Future<List<_i19.Category>> categories({int? branchId}) =>
      (super.noSuchMethod(
              Invocation.method(#categories, [], {#branchId: branchId}),
              returnValue: Future<List<_i19.Category>>.value(<_i19.Category>[]))
          as _i16.Future<List<_i19.Category>>);
  @override
  _i16.Future<List<_i20.Unit>> units({int? branchId}) =>
      (super.noSuchMethod(Invocation.method(#units, [], {#branchId: branchId}),
              returnValue: Future<List<_i20.Unit>>.value(<_i20.Unit>[]))
          as _i16.Future<List<_i20.Unit>>);
  @override
  _i16.Future<int> create<T>({Map<dynamic, dynamic>? data, String? endPoint}) =>
      (super.noSuchMethod(
          Invocation.method(#create, [], {#data: data, #endPoint: endPoint}),
          returnValue: Future<int>.value(0)) as _i16.Future<int>);
  @override
  _i16.Future<int> update<T>({Map<dynamic, dynamic>? data, String? endPoint}) =>
      (super.noSuchMethod(
          Invocation.method(#update, [], {#data: data, #endPoint: endPoint}),
          returnValue: Future<int>.value(0)) as _i16.Future<int>);
  @override
  _i16.Future<bool> delete({dynamic id, String? endPoint}) =>
      (super.noSuchMethod(
          Invocation.method(#delete, [], {#id: id, #endPoint: endPoint}),
          returnValue: Future<bool>.value(false)) as _i16.Future<bool>);
  @override
  _i16.Future<_i18.PColor?> getColor({int? id, String? endPoint}) =>
      (super.noSuchMethod(
              Invocation.method(#getColor, [], {#id: id, #endPoint: endPoint}),
              returnValue: Future<_i18.PColor?>.value())
          as _i16.Future<_i18.PColor?>);
  @override
  _i16.Future<_i4.StockSync?> getStock({int? branchId, int? variantId}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #getStock, [], {#branchId: branchId, #variantId: variantId}),
              returnValue: Future<_i4.StockSync?>.value())
          as _i16.Future<_i4.StockSync?>);
  @override
  _i16.Future<List<_i21.VariantSync>> variants(
          {int? branchId, int? productId}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #variants, [], {#branchId: branchId, #productId: productId}),
              returnValue:
                  Future<List<_i21.VariantSync>>.value(<_i21.VariantSync>[]))
          as _i16.Future<List<_i21.VariantSync>>);
  @override
  _i16.Future<_i21.VariantSync?> variant({int? variantId}) =>
      (super.noSuchMethod(
              Invocation.method(#variant, [], {#variantId: variantId}),
              returnValue: Future<_i21.VariantSync?>.value())
          as _i16.Future<_i21.VariantSync?>);
  @override
  _i16.Future<int> addUnits({Map<dynamic, dynamic>? data}) =>
      (super.noSuchMethod(Invocation.method(#addUnits, [], {#data: data}),
          returnValue: Future<int>.value(0)) as _i16.Future<int>);
  @override
  _i16.Future<int> addVariant(
          {List<_i21.VariantSync>? data,
          double? retailPrice,
          double? supplyPrice}) =>
      (super.noSuchMethod(
          Invocation.method(#addVariant, [], {
            #data: data,
            #retailPrice: retailPrice,
            #supplyPrice: supplyPrice
          }),
          returnValue: Future<int>.value(0)) as _i16.Future<int>);
  @override
  _i16.Future<_i5.ProductSync?> getProduct({int? id}) =>
      (super.noSuchMethod(Invocation.method(#getProduct, [], {#id: id}),
              returnValue: Future<_i5.ProductSync?>.value())
          as _i16.Future<_i5.ProductSync?>);
  @override
  _i16.Future<_i5.ProductSync?> getProductByBarCode({String? barCode}) =>
      (super.noSuchMethod(
              Invocation.method(#getProductByBarCode, [], {#barCode: barCode}),
              returnValue: Future<_i5.ProductSync?>.value())
          as _i16.Future<_i5.ProductSync?>);
  @override
  _i16.Future<_i5.ProductSync> createProduct({_i5.ProductSync? product}) =>
      (super.noSuchMethod(
              Invocation.method(#createProduct, [], {#product: product}),
              returnValue: Future<_i5.ProductSync>.value(_FakeProductSync()))
          as _i16.Future<_i5.ProductSync>);
  @override
  _i16.Future<List<_i5.ProductSync>> isTempProductExist({int? branchId}) =>
      (super.noSuchMethod(
              Invocation.method(#isTempProductExist, [], {#branchId: branchId}),
              returnValue:
                  Future<List<_i5.ProductSync>>.value(<_i5.ProductSync>[]))
          as _i16.Future<List<_i5.ProductSync>>);
  @override
  _i16.Future<bool> logOut() =>
      (super.noSuchMethod(Invocation.method(#logOut, []),
          returnValue: Future<bool>.value(false)) as _i16.Future<bool>);
  @override
  _i16.Future<_i6.OrderFSync> createOrder(
          {double? customAmount,
          _i21.VariantSync? variation,
          double? price,
          bool? useProductName = false,
          String? orderType = r'custom',
          double? quantity = 1.0}) =>
      (super.noSuchMethod(
              Invocation.method(#createOrder, [], {
                #customAmount: customAmount,
                #variation: variation,
                #price: price,
                #useProductName: useProductName,
                #orderType: orderType,
                #quantity: quantity
              }),
              returnValue: Future<_i6.OrderFSync>.value(_FakeOrderFSync()))
          as _i16.Future<_i6.OrderFSync>);
  @override
  _i16.Future<List<_i6.OrderFSync>> orders({int? branchId}) =>
      (super.noSuchMethod(Invocation.method(#orders, [], {#branchId: branchId}),
              returnValue:
                  Future<List<_i6.OrderFSync>>.value(<_i6.OrderFSync>[]))
          as _i16.Future<List<_i6.OrderFSync>>);
  @override
  _i16.Future<_i6.OrderFSync?> order({int? branchId}) =>
      (super.noSuchMethod(Invocation.method(#order, [], {#branchId: branchId}),
              returnValue: Future<_i6.OrderFSync?>.value())
          as _i16.Future<_i6.OrderFSync?>);
  @override
  _i16.Future<_i22.OrderItemSync?> getOrderItem({int? id}) =>
      (super.noSuchMethod(Invocation.method(#getOrderItem, [], {#id: id}),
              returnValue: Future<_i22.OrderItemSync?>.value())
          as _i16.Future<_i22.OrderItemSync?>);
  @override
  _i16.Future<_i21.VariantSync?> getCustomProductVariant() =>
      (super.noSuchMethod(Invocation.method(#getCustomProductVariant, []),
              returnValue: Future<_i21.VariantSync?>.value())
          as _i16.Future<_i21.VariantSync?>);
  @override
  _i16.Future<_i7.Spenn> spennPayment({double? amount, dynamic phoneNumber}) =>
      (super.noSuchMethod(
          Invocation.method(
              #spennPayment, [], {#amount: amount, #phoneNumber: phoneNumber}),
          returnValue:
              Future<_i7.Spenn>.value(_FakeSpenn())) as _i16.Future<_i7.Spenn>);
  @override
  _i16.Future<void> collectCashPayment(
          {double? cashReceived, _i6.OrderFSync? order}) =>
      (super.noSuchMethod(
          Invocation.method(#collectCashPayment, [],
              {#cashReceived: cashReceived, #order: order}),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future.value()) as _i16.Future<void>);
  @override
  _i23.Setting? getSetting({int? userId}) =>
      (super.noSuchMethod(Invocation.method(#getSetting, [], {#userId: userId}))
          as _i23.Setting?);
  @override
  _i16.Future<_i23.Setting?> createSetting({_i23.Setting? setting}) =>
      (super.noSuchMethod(
              Invocation.method(#createSetting, [], {#setting: setting}),
              returnValue: Future<_i23.Setting?>.value())
          as _i16.Future<_i23.Setting?>);
  @override
  void sendMessage({int? receiverId, _i24.Message? message}) =>
      super.noSuchMethod(
          Invocation.method(
              #sendMessage, [], {#receiverId: receiverId, #message: message}),
          returnValueForMissingStub: null);
  @override
  _i16.Stream<List<_i24.Message>> messages({int? conversationId}) => (super
      .noSuchMethod(
          Invocation.method(#messages, [], {#conversationId: conversationId}),
          returnValue: Stream<List<_i24.Message>>.empty()) as _i16
      .Stream<List<_i24.Message>>);
  @override
  _i16.Stream<List<_i8.BusinessSync>> users() =>
      (super.noSuchMethod(Invocation.method(#users, []),
              returnValue: Stream<List<_i8.BusinessSync>>.empty())
          as _i16.Stream<List<_i8.BusinessSync>>);
  @override
  _i16.Stream<List<_i8.BusinessSync>> contacts() =>
      (super.noSuchMethod(Invocation.method(#contacts, []),
              returnValue: Stream<List<_i8.BusinessSync>>.empty())
          as _i16.Stream<List<_i8.BusinessSync>>);
  @override
  _i16.Future<List<_i8.BusinessSync>> getContacts() =>
      (super.noSuchMethod(Invocation.method(#getContacts, []),
              returnValue:
                  Future<List<_i8.BusinessSync>>.value(<_i8.BusinessSync>[]))
          as _i16.Future<List<_i8.BusinessSync>>);
  @override
  _i8.BusinessSync getBusiness() =>
      (super.noSuchMethod(Invocation.method(#getBusiness, []),
          returnValue: _FakeBusinessSync()) as _i8.BusinessSync);
  @override
  _i25.CustomerSync? addCustomer(
          {Map<dynamic, dynamic>? customer, int? orderId}) =>
      (super.noSuchMethod(Invocation.method(
              #addCustomer, [], {#customer: customer, #orderId: orderId}))
          as _i25.CustomerSync?);
  @override
  _i16.Future<dynamic> assingOrderToCustomer({int? customerId, int? orderId}) =>
      (super.noSuchMethod(
          Invocation.method(#assingOrderToCustomer, [],
              {#customerId: customerId, #orderId: orderId}),
          returnValue: Future<dynamic>.value()) as _i16.Future<dynamic>);
  @override
  _i16.Stream<_i25.CustomerSync?> getCustomer({String? key}) =>
      (super.noSuchMethod(Invocation.method(#getCustomer, [], {#key: key}),
              returnValue: Stream<_i25.CustomerSync?>.empty())
          as _i16.Stream<_i25.CustomerSync?>);
  @override
  _i16.Stream<_i25.CustomerSync?> getCustomerByOrderId({int? id}) => (super
          .noSuchMethod(Invocation.method(#getCustomerByOrderId, [], {#id: id}),
              returnValue: Stream<_i25.CustomerSync?>.empty())
      as _i16.Stream<_i25.CustomerSync?>);
  @override
  _i16.Future<_i6.OrderFSync> getOrderById({int? id}) =>
      (super.noSuchMethod(Invocation.method(#getOrderById, [], {#id: id}),
              returnValue: Future<_i6.OrderFSync>.value(_FakeOrderFSync()))
          as _i16.Future<_i6.OrderFSync>);
  @override
  _i16.Future<List<_i6.OrderFSync>> tickets() => (super.noSuchMethod(
          Invocation.method(#tickets, []),
          returnValue: Future<List<_i6.OrderFSync>>.value(<_i6.OrderFSync>[]))
      as _i16.Future<List<_i6.OrderFSync>>);
  @override
  List<_i21.VariantSync> getVariantByProductId({int? productId}) =>
      (super.noSuchMethod(
          Invocation.method(
              #getVariantByProductId, [], {#productId: productId}),
          returnValue: <_i21.VariantSync>[]) as List<_i21.VariantSync>);
  @override
  _i16.Future<List<_i6.OrderFSync>> getOrderByStatus({String? status}) => (super
      .noSuchMethod(Invocation.method(#getOrderByStatus, [], {#status: status}),
          returnValue:
              Future<List<_i6.OrderFSync>>.value(<_i6.OrderFSync>[])) as _i16
      .Future<List<_i6.OrderFSync>>);
  @override
  _i16.Future<int> sendReport({List<_i22.OrderItemSync>? orderItems}) =>
      (super.noSuchMethod(
          Invocation.method(#sendReport, [], {#orderItems: orderItems}),
          returnValue: Future<int>.value(0)) as _i16.Future<int>);
  @override
  _i16.Future<void> createGoogleSheetDoc({String? email}) =>
      (super.noSuchMethod(
          Invocation.method(#createGoogleSheetDoc, [], {#email: email}),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future.value()) as _i16.Future<void>);
  @override
  _i8.BusinessSync getBusinessById({int? id}) =>
      (super.noSuchMethod(Invocation.method(#getBusinessById, [], {#id: id}),
          returnValue: _FakeBusinessSync()) as _i8.BusinessSync);
  @override
  _i22.OrderItemSync? getOrderItemByVariantId({int? variantId, int? orderId}) =>
      (super.noSuchMethod(Invocation.method(#getOrderItemByVariantId, [],
          {#variantId: variantId, #orderId: orderId})) as _i22.OrderItemSync?);
  @override
  _i16.Future<void> updateBusiness(
          {int? id, Map<dynamic, dynamic>? business}) =>
      (super.noSuchMethod(
          Invocation.method(
              #updateBusiness, [], {#id: id, #business: business}),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future.value()) as _i16.Future<void>);
  @override
  int lifeTimeCustomersForbranch({int? branchId}) => (super.noSuchMethod(
      Invocation.method(#lifeTimeCustomersForbranch, [], {#branchId: branchId}),
      returnValue: 0) as int);
  @override
  List<_i6.OrderFSync> weeklyOrdersReport(
          {DateTime? weekStartDate, DateTime? weekEndDate, int? branchId}) =>
      (super.noSuchMethod(
          Invocation.method(#weeklyOrdersReport, [], {
            #weekStartDate: weekStartDate,
            #weekEndDate: weekEndDate,
            #branchId: branchId
          }),
          returnValue: <_i6.OrderFSync>[]) as List<_i6.OrderFSync>);
  @override
  _i16.Future<void> saveDiscount(
          {int? branchId, dynamic name, double? amount}) =>
      (super.noSuchMethod(
          Invocation.method(#saveDiscount, [],
              {#branchId: branchId, #name: name, #amount: amount}),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future.value()) as _i16.Future<void>);
  @override
  _i16.Future<List<_i26.DiscountSync>> getDiscounts({int? branchId}) => (super
          .noSuchMethod(
              Invocation.method(#getDiscounts, [], {#branchId: branchId}),
              returnValue:
                  Future<List<_i26.DiscountSync>>.value(<_i26.DiscountSync>[]))
      as _i16.Future<List<_i26.DiscountSync>>);
  @override
  _i6.OrderFSync addOrderItem(
          {_i6.OrderFSync? order, Map<dynamic, dynamic>? data}) =>
      (super.noSuchMethod(
          Invocation.method(#addOrderItem, [], {#order: order, #data: data}),
          returnValue: _FakeOrderFSync()) as _i6.OrderFSync);
  @override
  void emptySentMessageQueue() =>
      super.noSuchMethod(Invocation.method(#emptySentMessageQueue, []),
          returnValueForMissingStub: null);
  @override
  bool suggestRestore() =>
      (super.noSuchMethod(Invocation.method(#suggestRestore, []),
          returnValue: false) as bool);
  @override
  _i16.Future<int> userNameAvailable({String? name}) => (super.noSuchMethod(
      Invocation.method(#userNameAvailable, [], {#name: name}),
      returnValue: Future<int>.value(0)) as _i16.Future<int>);
  @override
  _i27.TenantSync? isTenant({String? phoneNumber}) => (super.noSuchMethod(
          Invocation.method(#isTenant, [], {#phoneNumber: phoneNumber}))
      as _i27.TenantSync?);
  @override
  _i16.Future<_i8.BusinessSync> getBusinessFromOnlineGivenId({int? id}) =>
      (super.noSuchMethod(
              Invocation.method(#getBusinessFromOnlineGivenId, [], {#id: id}),
              returnValue: Future<_i8.BusinessSync>.value(_FakeBusinessSync()))
          as _i16.Future<_i8.BusinessSync>);
  @override
  _i16.Future<void> syncProduct(
          {_i5.ProductSync? product,
          _i21.VariantSync? variant,
          _i4.StockSync? stock}) =>
      (super.noSuchMethod(
          Invocation.method(#syncProduct, [],
              {#product: product, #variant: variant, #stock: stock}),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future.value()) as _i16.Future<void>);
  @override
  void migrateToSync() =>
      super.noSuchMethod(Invocation.method(#migrateToSync, []),
          returnValueForMissingStub: null);
  @override
  bool isSubscribed({String? feature, int? businessId}) => (super.noSuchMethod(
      Invocation.method(
          #isSubscribed, [], {#feature: feature, #businessId: businessId}),
      returnValue: false) as bool);
  @override
  bool subscribe({String? feature, int? businessId, int? agentCode}) =>
      (super.noSuchMethod(
          Invocation.method(#subscribe, [], {
            #feature: feature,
            #businessId: businessId,
            #agentCode: agentCode
          }),
          returnValue: false) as bool);
  @override
  _i16.Future<bool> checkIn({String? checkInCode}) => (super.noSuchMethod(
      Invocation.method(#checkIn, [], {#checkInCode: checkInCode}),
      returnValue: Future<bool>.value(false)) as _i16.Future<bool>);
  @override
  _i16.Future<bool> enableAttendance({int? businessId, String? email}) =>
      (super.noSuchMethod(
          Invocation.method(
              #enableAttendance, [], {#businessId: businessId, #email: email}),
          returnValue: Future<bool>.value(false)) as _i16.Future<bool>);
  @override
  _i28.Profile? profile({int? businessId}) => (super.noSuchMethod(
          Invocation.method(#profile, [], {#businessId: businessId}))
      as _i28.Profile?);
  @override
  _i28.Profile? updateProfile({_i28.Profile? profile}) => (super.noSuchMethod(
          Invocation.method(#updateProfile, [], {#profile: profile}))
      as _i28.Profile?);
  @override
  void saveTenant({String? phoneNumber}) => super.noSuchMethod(
      Invocation.method(#saveTenant, [], {#phoneNumber: phoneNumber}),
      returnValueForMissingStub: null);
}

/// A class which mocks [Language].
///
/// See the documentation for Mockito's code generation for more information.
class MockLanguage extends _i1.Mock implements _i29.Language {
  @override
  void setLocale({String? lang}) =>
      super.noSuchMethod(Invocation.method(#setLocale, [], {#lang: lang}),
          returnValueForMissingStub: null);
}

/// A class which mocks [LanguageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLanguageService extends _i1.Mock implements _i29.LanguageService {
  @override
  _i9.Locale get locale => (super.noSuchMethod(Invocation.getter(#locale),
      returnValue: _FakeLocale()) as _i9.Locale);
  @override
  void setLocale({String? lang}) =>
      super.noSuchMethod(Invocation.method(#setLocale, [], {#lang: lang}),
          returnValueForMissingStub: null);
  @override
  void listenToReactiveValues(List<dynamic>? reactiveValues) =>
      super.noSuchMethod(
          Invocation.method(#listenToReactiveValues, [reactiveValues]),
          returnValueForMissingStub: null);
  @override
  void addListener(void Function()? listener) =>
      super.noSuchMethod(Invocation.method(#addListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void removeListener(void Function()? listener) =>
      super.noSuchMethod(Invocation.method(#removeListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void notifyListeners() =>
      super.noSuchMethod(Invocation.method(#notifyListeners, []),
          returnValueForMissingStub: null);
}

/// A class which mocks [Remote].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemote extends _i1.Mock implements _i30.Remote {
  @override
  void setDefault() => super.noSuchMethod(Invocation.method(#setDefault, []),
      returnValueForMissingStub: null);
  @override
  void fetch() => super.noSuchMethod(Invocation.method(#fetch, []),
      returnValueForMissingStub: null);
  @override
  bool isChatAvailable() =>
      (super.noSuchMethod(Invocation.method(#isChatAvailable, []),
          returnValue: false) as bool);
  @override
  bool isSpennPaymentAvailable() =>
      (super.noSuchMethod(Invocation.method(#isSpennPaymentAvailable, []),
          returnValue: false) as bool);
  @override
  bool isEmailReceiptAvailable() =>
      (super.noSuchMethod(Invocation.method(#isEmailReceiptAvailable, []),
          returnValue: false) as bool);
  @override
  bool isAddCustomerToSaleAvailable() =>
      (super.noSuchMethod(Invocation.method(#isAddCustomerToSaleAvailable, []),
          returnValue: false) as bool);
  @override
  bool isPrinterAvailable() =>
      (super.noSuchMethod(Invocation.method(#isPrinterAvailable, []),
          returnValue: false) as bool);
  @override
  bool forceDateEntry() =>
      (super.noSuchMethod(Invocation.method(#forceDateEntry, []),
          returnValue: false) as bool);
  @override
  bool isAnalyticFeatureAvailable() =>
      (super.noSuchMethod(Invocation.method(#isAnalyticFeatureAvailable, []),
          returnValue: false) as bool);
  @override
  bool isSubmitDeviceTokenEnabled() =>
      (super.noSuchMethod(Invocation.method(#isSubmitDeviceTokenEnabled, []),
          returnValue: false) as bool);
  @override
  bool scann_selling() =>
      (super.noSuchMethod(Invocation.method(#scann_selling, []),
          returnValue: false) as bool);
  @override
  void config() => super.noSuchMethod(Invocation.method(#config, []),
      returnValueForMissingStub: null);
  @override
  bool isMenuAvailable() =>
      (super.noSuchMethod(Invocation.method(#isMenuAvailable, []),
          returnValue: false) as bool);
  @override
  bool isDiscountAvailable() =>
      (super.noSuchMethod(Invocation.method(#isDiscountAvailable, []),
          returnValue: false) as bool);
  @override
  bool isOrderAvailable() =>
      (super.noSuchMethod(Invocation.method(#isOrderAvailable, []),
          returnValue: false) as bool);
  @override
  bool isBackupAvailable() =>
      (super.noSuchMethod(Invocation.method(#isBackupAvailable, []),
          returnValue: false) as bool);
  @override
  bool isRemoteLoggingDynamicLinkEnabled() => (super.noSuchMethod(
      Invocation.method(#isRemoteLoggingDynamicLinkEnabled, []),
      returnValue: false) as bool);
  @override
  bool isAccessiblityFeatureAvailable() => (super.noSuchMethod(
      Invocation.method(#isAccessiblityFeatureAvailable, []),
      returnValue: false) as bool);
  @override
  bool isMapAvailable() =>
      (super.noSuchMethod(Invocation.method(#isMapAvailable, []),
          returnValue: false) as bool);
  @override
  bool isAInvitingMembersAvailable() =>
      (super.noSuchMethod(Invocation.method(#isAInvitingMembersAvailable, []),
          returnValue: false) as bool);
  @override
  bool isSyncAvailable() =>
      (super.noSuchMethod(Invocation.method(#isSyncAvailable, []),
          returnValue: false) as bool);
}

/// A class which mocks [FirebaseMessaging].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseMessaging extends _i1.Mock implements _i31.FirebaseMessaging {
  @override
  _i10.FirebaseApp get app => (super.noSuchMethod(Invocation.getter(#app),
      returnValue: _FakeFirebaseApp()) as _i10.FirebaseApp);
  @override
  set app(_i10.FirebaseApp? _app) =>
      super.noSuchMethod(Invocation.setter(#app, _app),
          returnValueForMissingStub: null);
  @override
  bool get isAutoInitEnabled =>
      (super.noSuchMethod(Invocation.getter(#isAutoInitEnabled),
          returnValue: false) as bool);
  @override
  _i16.Stream<String> get onTokenRefresh =>
      (super.noSuchMethod(Invocation.getter(#onTokenRefresh),
          returnValue: Stream<String>.empty()) as _i16.Stream<String>);
  @override
  Map<dynamic, dynamic> get pluginConstants =>
      (super.noSuchMethod(Invocation.getter(#pluginConstants),
          returnValue: <dynamic, dynamic>{}) as Map<dynamic, dynamic>);
  @override
  _i16.Future<_i32.RemoteMessage?> getInitialMessage() =>
      (super.noSuchMethod(Invocation.method(#getInitialMessage, []),
              returnValue: Future<_i32.RemoteMessage?>.value())
          as _i16.Future<_i32.RemoteMessage?>);
  @override
  _i16.Future<void> deleteToken() =>
      (super.noSuchMethod(Invocation.method(#deleteToken, []),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future.value()) as _i16.Future<void>);
  @override
  _i16.Future<String?> getAPNSToken() =>
      (super.noSuchMethod(Invocation.method(#getAPNSToken, []),
          returnValue: Future<String?>.value()) as _i16.Future<String?>);
  @override
  _i16.Future<String?> getToken({String? vapidKey}) => (super.noSuchMethod(
      Invocation.method(#getToken, [], {#vapidKey: vapidKey}),
      returnValue: Future<String?>.value()) as _i16.Future<String?>);
  @override
  bool isSupported() => (super.noSuchMethod(Invocation.method(#isSupported, []),
      returnValue: false) as bool);
  @override
  _i16.Future<_i11.NotificationSettings> getNotificationSettings() =>
      (super.noSuchMethod(Invocation.method(#getNotificationSettings, []),
              returnValue: Future<_i11.NotificationSettings>.value(
                  _FakeNotificationSettings()))
          as _i16.Future<_i11.NotificationSettings>);
  @override
  _i16.Future<_i11.NotificationSettings> requestPermission(
          {bool? alert = true,
          bool? announcement = false,
          bool? badge = true,
          bool? carPlay = false,
          bool? criticalAlert = false,
          bool? provisional = false,
          bool? sound = true}) =>
      (super.noSuchMethod(
              Invocation.method(#requestPermission, [], {
                #alert: alert,
                #announcement: announcement,
                #badge: badge,
                #carPlay: carPlay,
                #criticalAlert: criticalAlert,
                #provisional: provisional,
                #sound: sound
              }),
              returnValue: Future<_i11.NotificationSettings>.value(
                  _FakeNotificationSettings()))
          as _i16.Future<_i11.NotificationSettings>);
  @override
  _i16.Future<void> sendMessage(
          {String? to,
          Map<String, String>? data,
          String? collapseKey,
          String? messageId,
          String? messageType,
          int? ttl}) =>
      (super.noSuchMethod(
          Invocation.method(#sendMessage, [], {
            #to: to,
            #data: data,
            #collapseKey: collapseKey,
            #messageId: messageId,
            #messageType: messageType,
            #ttl: ttl
          }),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future.value()) as _i16.Future<void>);
  @override
  _i16.Future<void> setAutoInitEnabled(bool? enabled) =>
      (super.noSuchMethod(Invocation.method(#setAutoInitEnabled, [enabled]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future.value()) as _i16.Future<void>);
  @override
  _i16.Future<void> setForegroundNotificationPresentationOptions(
          {bool? alert = false, bool? badge = false, bool? sound = false}) =>
      (super.noSuchMethod(
          Invocation.method(#setForegroundNotificationPresentationOptions, [],
              {#alert: alert, #badge: badge, #sound: sound}),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future.value()) as _i16.Future<void>);
  @override
  _i16.Future<void> subscribeToTopic(String? topic) =>
      (super.noSuchMethod(Invocation.method(#subscribeToTopic, [topic]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future.value()) as _i16.Future<void>);
  @override
  _i16.Future<void> unsubscribeFromTopic(String? topic) =>
      (super.noSuchMethod(Invocation.method(#unsubscribeFromTopic, [topic]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future.value()) as _i16.Future<void>);
}

/// A class which mocks [ProductService].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductService extends _i1.Mock implements _i33.ProductService {
  @override
  _i12.Logger get log =>
      (super.noSuchMethod(Invocation.getter(#log), returnValue: _FakeLogger())
          as _i12.Logger);
  @override
  List<_i26.DiscountSync> get discounts =>
      (super.noSuchMethod(Invocation.getter(#discounts),
          returnValue: <_i26.DiscountSync>[]) as List<_i26.DiscountSync>);
  @override
  List<_i5.ProductSync> get products =>
      (super.noSuchMethod(Invocation.getter(#products),
          returnValue: <_i5.ProductSync>[]) as List<_i5.ProductSync>);
  @override
  List<_i4.StockSync> get stocks =>
      (super.noSuchMethod(Invocation.getter(#stocks),
          returnValue: <_i4.StockSync>[]) as List<_i4.StockSync>);
  @override
  void setBarcode(String? value) =>
      super.noSuchMethod(Invocation.method(#setBarcode, [value]),
          returnValueForMissingStub: null);
  @override
  dynamic setProductUnit({String? unit}) =>
      super.noSuchMethod(Invocation.method(#setProductUnit, [], {#unit: unit}));
  @override
  dynamic setCurrentProduct({_i5.ProductSync? product}) => super.noSuchMethod(
      Invocation.method(#setCurrentProduct, [], {#product: product}));
  @override
  _i16.Future<void> variantsProduct({int? productId}) => (super.noSuchMethod(
      Invocation.method(#variantsProduct, [], {#productId: productId}),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future.value()) as _i16.Future<void>);
  @override
  _i16.Future<List<_i5.ProductSync>> loadProducts({int? branchId}) => (super
      .noSuchMethod(Invocation.method(#loadProducts, [], {#branchId: branchId}),
          returnValue:
              Future<List<_i5.ProductSync>>.value(<_i5.ProductSync>[])) as _i16
      .Future<List<_i5.ProductSync>>);
  @override
  _i16.Future<void> filtterProduct({String? searchKey, int? branchId}) =>
      (super.noSuchMethod(
          Invocation.method(#filtterProduct, [],
              {#searchKey: searchKey, #branchId: branchId}),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future.value()) as _i16.Future<void>);
  @override
  _i16.Future<_i5.ProductSync?> getProductByBarCode({String? code}) =>
      (super.noSuchMethod(
              Invocation.method(#getProductByBarCode, [], {#code: code}),
              returnValue: Future<_i5.ProductSync?>.value())
          as _i16.Future<_i5.ProductSync?>);
  @override
  List<_i4.StockSync> loadStockByProductId({int? productId}) =>
      (super.noSuchMethod(
          Invocation.method(#loadStockByProductId, [], {#productId: productId}),
          returnValue: <_i4.StockSync>[]) as List<_i4.StockSync>);
  @override
  void listenToReactiveValues(List<dynamic>? reactiveValues) =>
      super.noSuchMethod(
          Invocation.method(#listenToReactiveValues, [reactiveValues]),
          returnValueForMissingStub: null);
  @override
  void addListener(void Function()? listener) =>
      super.noSuchMethod(Invocation.method(#addListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void removeListener(void Function()? listener) =>
      super.noSuchMethod(Invocation.method(#removeListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void notifyListeners() =>
      super.noSuchMethod(Invocation.method(#notifyListeners, []),
          returnValueForMissingStub: null);
}

/// A class which mocks [KeyPadService].
///
/// See the documentation for Mockito's code generation for more information.
class MockKeyPadService extends _i1.Mock implements _i34.KeyPadService {
  @override
  _i12.Logger get log =>
      (super.noSuchMethod(Invocation.getter(#log), returnValue: _FakeLogger())
          as _i12.Logger);
  @override
  _i13.Stack<dynamic> get stack =>
      (super.noSuchMethod(Invocation.getter(#stack),
          returnValue: _FakeStack<dynamic>()) as _i13.Stack<dynamic>);
  @override
  set stack(_i13.Stack<dynamic>? _stack) =>
      super.noSuchMethod(Invocation.setter(#stack, _stack),
          returnValueForMissingStub: null);
  @override
  String get key =>
      (super.noSuchMethod(Invocation.getter(#key), returnValue: '') as String);
  @override
  int get countOrderItems =>
      (super.noSuchMethod(Invocation.getter(#countOrderItems), returnValue: 0)
          as int);
  @override
  double get amountTotal =>
      (super.noSuchMethod(Invocation.getter(#amountTotal), returnValue: 0.0)
          as double);
  @override
  int get check =>
      (super.noSuchMethod(Invocation.getter(#check), returnValue: 0) as int);
  @override
  List<_i6.OrderFSync> get tickets =>
      (super.noSuchMethod(Invocation.getter(#tickets),
          returnValue: <_i6.OrderFSync>[]) as List<_i6.OrderFSync>);
  @override
  double get totalPayable =>
      (super.noSuchMethod(Invocation.getter(#totalPayable), returnValue: 0.0)
          as double);
  @override
  double get totalDiscount =>
      (super.noSuchMethod(Invocation.getter(#totalDiscount), returnValue: 0.0)
          as double);
  @override
  void addKey(String? key) =>
      super.noSuchMethod(Invocation.method(#addKey, [key]),
          returnValueForMissingStub: null);
  @override
  dynamic setAmount({double? amount}) =>
      super.noSuchMethod(Invocation.method(#setAmount, [], {#amount: amount}));
  @override
  dynamic setCashReceived({double? amount}) => super
      .noSuchMethod(Invocation.method(#setCashReceived, [], {#amount: amount}));
  @override
  void toggleCheckbox({int? variantId}) => super.noSuchMethod(
      Invocation.method(#toggleCheckbox, [], {#variantId: variantId}),
      returnValueForMissingStub: null);
  @override
  dynamic setCount({int? count}) =>
      super.noSuchMethod(Invocation.method(#setCount, [], {#count: count}));
  @override
  _i16.Future<List<_i6.OrderFSync>> getTickets() => (super.noSuchMethod(
          Invocation.method(#getTickets, []),
          returnValue: Future<List<_i6.OrderFSync>>.value(<_i6.OrderFSync>[]))
      as _i16.Future<List<_i6.OrderFSync>>);
  @override
  void setTotalPayable({double? amount}) => super.noSuchMethod(
      Invocation.method(#setTotalPayable, [], {#amount: amount}),
      returnValueForMissingStub: null);
  @override
  void setTotalDiscount({double? amount}) => super.noSuchMethod(
      Invocation.method(#setTotalDiscount, [], {#amount: amount}),
      returnValueForMissingStub: null);
  @override
  void setOrderInProgress(_i6.OrderFSync? order) =>
      super.noSuchMethod(Invocation.method(#setOrderInProgress, [order]),
          returnValueForMissingStub: null);
  @override
  _i16.Future<_i6.OrderFSync?> getOrder({int? branchId}) => (super.noSuchMethod(
          Invocation.method(#getOrder, [], {#branchId: branchId}),
          returnValue: Future<_i6.OrderFSync?>.value())
      as _i16.Future<_i6.OrderFSync?>);
  @override
  _i16.Future<_i6.OrderFSync?> getOrderById({int? id}) =>
      (super.noSuchMethod(Invocation.method(#getOrderById, [], {#id: id}),
              returnValue: Future<_i6.OrderFSync?>.value())
          as _i16.Future<_i6.OrderFSync?>);
  @override
  void reset() => super.noSuchMethod(Invocation.method(#reset, []),
      returnValueForMissingStub: null);
  @override
  void customQtyIncrease({int? qty}) =>
      super.noSuchMethod(Invocation.method(#customQtyIncrease, [], {#qty: qty}),
          returnValueForMissingStub: null);
  @override
  void increaseQty() => super.noSuchMethod(Invocation.method(#increaseQty, []),
      returnValueForMissingStub: null);
  @override
  void decreaseQty() => super.noSuchMethod(Invocation.method(#decreaseQty, []),
      returnValueForMissingStub: null);
  @override
  void pop() => super.noSuchMethod(Invocation.method(#pop, []),
      returnValueForMissingStub: null);
  @override
  void listenToReactiveValues(List<dynamic>? reactiveValues) =>
      super.noSuchMethod(
          Invocation.method(#listenToReactiveValues, [reactiveValues]),
          returnValueForMissingStub: null);
  @override
  void addListener(void Function()? listener) =>
      super.noSuchMethod(Invocation.method(#addListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void removeListener(void Function()? listener) =>
      super.noSuchMethod(Invocation.method(#removeListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void notifyListeners() =>
      super.noSuchMethod(Invocation.method(#notifyListeners, []),
          returnValueForMissingStub: null);
}

/// A class which mocks [SettingsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsService extends _i1.Mock implements _i35.SettingsService {
  @override
  _i12.Logger get log =>
      (super.noSuchMethod(Invocation.getter(#log), returnValue: _FakeLogger())
          as _i12.Logger);
  @override
  _i14.ReactiveValue<_i36.ThemeMode> get themeMode =>
      (super.noSuchMethod(Invocation.getter(#themeMode),
              returnValue: _FakeReactiveValue<_i36.ThemeMode>())
          as _i14.ReactiveValue<_i36.ThemeMode>);
  @override
  bool get enablePrinter =>
      (super.noSuchMethod(Invocation.getter(#enablePrinter), returnValue: false)
          as bool);
  @override
  bool get sendDailReport => (super
          .noSuchMethod(Invocation.getter(#sendDailReport), returnValue: false)
      as bool);
  @override
  bool get isAttendanceEnabled =>
      (super.noSuchMethod(Invocation.getter(#isAttendanceEnabled),
          returnValue: false) as bool);
  @override
  void setThemeMode(_i36.ThemeMode? mode) =>
      super.noSuchMethod(Invocation.method(#setThemeMode, [mode]),
          returnValueForMissingStub: null);
  @override
  _i16.Future<bool> updateSettings({Map<dynamic, dynamic>? map}) =>
      (super.noSuchMethod(Invocation.method(#updateSettings, [], {#map: map}),
          returnValue: Future<bool>.value(false)) as _i16.Future<bool>);
  @override
  bool isDailyReportEnabled() =>
      (super.noSuchMethod(Invocation.method(#isDailyReportEnabled, []),
          returnValue: false) as bool);
  @override
  bool enabledPrint() =>
      (super.noSuchMethod(Invocation.method(#enabledPrint, []),
          returnValue: false) as bool);
  @override
  void enablePrint({bool? bool}) =>
      super.noSuchMethod(Invocation.method(#enablePrint, [], {#bool: bool}),
          returnValueForMissingStub: null);
  @override
  void getEnableReportToggleState() =>
      super.noSuchMethod(Invocation.method(#getEnableReportToggleState, []),
          returnValueForMissingStub: null);
  @override
  void getEnableAttendanceToggleState() =>
      super.noSuchMethod(Invocation.method(#getEnableAttendanceToggleState, []),
          returnValueForMissingStub: null);
  @override
  void toggleAttendanceSetting() =>
      super.noSuchMethod(Invocation.method(#toggleAttendanceSetting, []),
          returnValueForMissingStub: null);
  @override
  void toggleDailyReportSetting() =>
      super.noSuchMethod(Invocation.method(#toggleDailyReportSetting, []),
          returnValueForMissingStub: null);
  @override
  _i16.Future<Function?> enableAttendance({bool? bool, Function? callback}) =>
      (super.noSuchMethod(
          Invocation.method(
              #enableAttendance, [], {#bool: bool, #callback: callback}),
          returnValue: Future<Function?>.value()) as _i16.Future<Function?>);
  @override
  void listenToReactiveValues(List<dynamic>? reactiveValues) =>
      super.noSuchMethod(
          Invocation.method(#listenToReactiveValues, [reactiveValues]),
          returnValueForMissingStub: null);
  @override
  void addListener(void Function()? listener) =>
      super.noSuchMethod(Invocation.method(#addListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void removeListener(void Function()? listener) =>
      super.noSuchMethod(Invocation.method(#removeListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void notifyListeners() =>
      super.noSuchMethod(Invocation.method(#notifyListeners, []),
          returnValueForMissingStub: null);
}

/// A class which mocks [LocalStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalStorage extends _i1.Mock implements _i37.LocalStorage {
  @override
  dynamic read({String? key}) =>
      super.noSuchMethod(Invocation.method(#read, [], {#key: key}));
  @override
  dynamic remove({String? key}) =>
      super.noSuchMethod(Invocation.method(#remove, [], {#key: key}));
  @override
  bool write({String? key, dynamic value}) => (super.noSuchMethod(
      Invocation.method(#write, [], {#key: key, #value: value}),
      returnValue: false) as bool);
  @override
  int getBusinessId() =>
      (super.noSuchMethod(Invocation.method(#getBusinessId, []), returnValue: 0)
          as int);
  @override
  int getBranchId() =>
      (super.noSuchMethod(Invocation.method(#getBranchId, []), returnValue: 0)
          as int);
  @override
  String getUserPhone() =>
      (super.noSuchMethod(Invocation.method(#getUserPhone, []), returnValue: '')
          as String);
  @override
  String getUserId() =>
      (super.noSuchMethod(Invocation.method(#getUserId, []), returnValue: '')
          as String);
}

/// A class which mocks [AppService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppService extends _i1.Mock implements _i38.AppService {
  @override
  _i12.Logger get log =>
      (super.noSuchMethod(Invocation.getter(#log), returnValue: _FakeLogger())
          as _i12.Logger);
  @override
  List<_i19.Category> get categories =>
      (super.noSuchMethod(Invocation.getter(#categories),
          returnValue: <_i19.Category>[]) as List<_i19.Category>);
  @override
  List<_i8.BusinessSync> get businesses =>
      (super.noSuchMethod(Invocation.getter(#businesses),
          returnValue: <_i8.BusinessSync>[]) as List<_i8.BusinessSync>);
  @override
  List<_i20.Unit> get units =>
      (super.noSuchMethod(Invocation.getter(#units), returnValue: <_i20.Unit>[])
          as List<_i20.Unit>);
  @override
  List<_i18.PColor> get colors =>
      (super.noSuchMethod(Invocation.getter(#colors),
          returnValue: <_i18.PColor>[]) as List<_i18.PColor>);
  @override
  String get currentColor =>
      (super.noSuchMethod(Invocation.getter(#currentColor), returnValue: '')
          as String);
  @override
  bool get hasLoggedInUser => (super
          .noSuchMethod(Invocation.getter(#hasLoggedInUser), returnValue: false)
      as bool);
  @override
  List<_i8.BusinessSync> get contacts =>
      (super.noSuchMethod(Invocation.getter(#contacts),
          returnValue: <_i8.BusinessSync>[]) as List<_i8.BusinessSync>);
  @override
  dynamic setCurrentColor({String? color}) => super
      .noSuchMethod(Invocation.method(#setCurrentColor, [], {#color: color}));
  @override
  dynamic setBusiness({List<_i8.BusinessSync>? businesses}) =>
      super.noSuchMethod(
          Invocation.method(#setBusiness, [], {#businesses: businesses}));
  @override
  void loadCategories() =>
      super.noSuchMethod(Invocation.method(#loadCategories, []),
          returnValueForMissingStub: null);
  @override
  _i16.Future<void> loadUnits() =>
      (super.noSuchMethod(Invocation.method(#loadUnits, []),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future.value()) as _i16.Future<void>);
  @override
  _i16.Future<void> loadColors() =>
      (super.noSuchMethod(Invocation.method(#loadColors, []),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future.value()) as _i16.Future<void>);
  @override
  bool isLoggedIn() => (super.noSuchMethod(Invocation.method(#isLoggedIn, []),
      returnValue: false) as bool);
  @override
  _i16.Future<void> loadContacts() =>
      (super.noSuchMethod(Invocation.method(#loadContacts, []),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future.value()) as _i16.Future<void>);
  @override
  void listenToReactiveValues(List<dynamic>? reactiveValues) =>
      super.noSuchMethod(
          Invocation.method(#listenToReactiveValues, [reactiveValues]),
          returnValueForMissingStub: null);
  @override
  void addListener(void Function()? listener) =>
      super.noSuchMethod(Invocation.method(#addListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void removeListener(void Function()? listener) =>
      super.noSuchMethod(Invocation.method(#removeListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void notifyListeners() =>
      super.noSuchMethod(Invocation.method(#notifyListeners, []),
          returnValueForMissingStub: null);
}

/// A class which mocks [FlipperLocation].
///
/// See the documentation for Mockito's code generation for more information.
class MockFlipperLocation extends _i1.Mock implements _i39.FlipperLocation {
  @override
  _i16.Future<Map<String, String>> getLocation() => (super.noSuchMethod(
          Invocation.method(#getLocation, []),
          returnValue: Future<Map<String, String>>.value(<String, String>{}))
      as _i16.Future<Map<String, String>>);
  @override
  _i16.Future<bool> doWeHaveLocationPermission() =>
      (super.noSuchMethod(Invocation.method(#doWeHaveLocationPermission, []),
          returnValue: Future<bool>.value(false)) as _i16.Future<bool>);
}

/// A class which mocks [NavigationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNavigationService extends _i1.Mock implements _i40.NavigationService {
  @override
  String get previousRoute =>
      (super.noSuchMethod(Invocation.getter(#previousRoute), returnValue: '')
          as String);
  @override
  String get currentRoute =>
      (super.noSuchMethod(Invocation.getter(#currentRoute), returnValue: '')
          as String);
  @override
  _i41.GlobalKey<_i42.NavigatorState>? nestedNavigationKey(int? index) =>
      (super.noSuchMethod(Invocation.method(#nestedNavigationKey, [index]))
          as _i41.GlobalKey<_i42.NavigatorState>?);
  @override
  void config(
          {bool? enableLog,
          bool? defaultPopGesture,
          bool? defaultOpaqueRoute,
          Duration? defaultDurationTransition,
          bool? defaultGlobalState,
          String? defaultTransition}) =>
      super.noSuchMethod(
          Invocation.method(#config, [], {
            #enableLog: enableLog,
            #defaultPopGesture: defaultPopGesture,
            #defaultOpaqueRoute: defaultOpaqueRoute,
            #defaultDurationTransition: defaultDurationTransition,
            #defaultGlobalState: defaultGlobalState,
            #defaultTransition: defaultTransition
          }),
          returnValueForMissingStub: null);
  @override
  _i16.Future<T?>? navigateWithTransition<T>(_i41.Widget? page,
          {bool? opaque,
          String? transition = r'',
          Duration? duration,
          bool? popGesture,
          int? id,
          _i43.Curve? curve,
          _i44.Bindings? binding,
          bool? fullscreenDialog = false,
          bool? preventDuplicates = true,
          _i45.Transition? transitionClass}) =>
      (super.noSuchMethod(Invocation.method(#navigateWithTransition, [
        page
      ], {
        #opaque: opaque,
        #transition: transition,
        #duration: duration,
        #popGesture: popGesture,
        #id: id,
        #curve: curve,
        #binding: binding,
        #fullscreenDialog: fullscreenDialog,
        #preventDuplicates: preventDuplicates,
        #transitionClass: transitionClass
      })) as _i16.Future<T?>?);
  @override
  _i16.Future<T?>? replaceWithTransition<T>(_i41.Widget? page,
          {bool? opaque,
          String? transition = r'',
          Duration? duration,
          bool? popGesture,
          int? id,
          _i43.Curve? curve,
          _i44.Bindings? binding,
          bool? fullscreenDialog = false,
          bool? preventDuplicates = true,
          _i45.Transition? transitionClass}) =>
      (super.noSuchMethod(Invocation.method(#replaceWithTransition, [
        page
      ], {
        #opaque: opaque,
        #transition: transition,
        #duration: duration,
        #popGesture: popGesture,
        #id: id,
        #curve: curve,
        #binding: binding,
        #fullscreenDialog: fullscreenDialog,
        #preventDuplicates: preventDuplicates,
        #transitionClass: transitionClass
      })) as _i16.Future<T?>?);
  @override
  bool back<T>({dynamic result, int? id}) => (super.noSuchMethod(
      Invocation.method(#back, [], {#result: result, #id: id}),
      returnValue: false) as bool);
  @override
  void popUntil(_i42.RoutePredicate? predicate) =>
      super.noSuchMethod(Invocation.method(#popUntil, [predicate]),
          returnValueForMissingStub: null);
  @override
  void popRepeated(int? popTimes) =>
      super.noSuchMethod(Invocation.method(#popRepeated, [popTimes]),
          returnValueForMissingStub: null);
  @override
  _i16.Future<T?>? navigateTo<T>(String? routeName,
          {dynamic arguments,
          int? id,
          bool? preventDuplicates = true,
          Map<String, String>? parameters}) =>
      (super.noSuchMethod(Invocation.method(#navigateTo, [
        routeName
      ], {
        #arguments: arguments,
        #id: id,
        #preventDuplicates: preventDuplicates,
        #parameters: parameters
      })) as _i16.Future<T?>?);
  @override
  _i16.Future<T?>? navigateToView<T>(_i41.Widget? view,
          {dynamic arguments,
          int? id,
          bool? opaque,
          _i43.Curve? curve,
          _i44.Bindings? binding,
          Duration? duration,
          bool? fullscreenDialog = false,
          bool? popGesture,
          bool? preventDuplicates = true,
          _i45.Transition? transition}) =>
      (super.noSuchMethod(Invocation.method(#navigateToView, [
        view
      ], {
        #arguments: arguments,
        #id: id,
        #opaque: opaque,
        #curve: curve,
        #binding: binding,
        #duration: duration,
        #fullscreenDialog: fullscreenDialog,
        #popGesture: popGesture,
        #preventDuplicates: preventDuplicates,
        #transition: transition
      })) as _i16.Future<T?>?);
  @override
  _i16.Future<T?>? replaceWith<T>(String? routeName,
          {dynamic arguments,
          int? id,
          bool? preventDuplicates = true,
          Map<String, String>? parameters}) =>
      (super.noSuchMethod(Invocation.method(#replaceWith, [
        routeName
      ], {
        #arguments: arguments,
        #id: id,
        #preventDuplicates: preventDuplicates,
        #parameters: parameters
      })) as _i16.Future<T?>?);
  @override
  _i16.Future<T?>? clearStackAndShow<T>(String? routeName,
          {dynamic arguments, int? id, Map<String, String>? parameters}) =>
      (super.noSuchMethod(Invocation.method(#clearStackAndShow, [
        routeName
      ], {
        #arguments: arguments,
        #id: id,
        #parameters: parameters
      })) as _i16.Future<T?>?);
  @override
  _i16.Future<T?>? clearTillFirstAndShow<T>(String? routeName,
          {dynamic arguments,
          int? id,
          bool? preventDuplicates = true,
          Map<String, String>? parameters}) =>
      (super.noSuchMethod(Invocation.method(#clearTillFirstAndShow, [
        routeName
      ], {
        #arguments: arguments,
        #id: id,
        #preventDuplicates: preventDuplicates,
        #parameters: parameters
      })) as _i16.Future<T?>?);
  @override
  _i16.Future<T?>? clearTillFirstAndShowView<T>(_i41.Widget? view,
          {dynamic arguments, int? id}) =>
      (super.noSuchMethod(Invocation.method(#clearTillFirstAndShowView, [view],
          {#arguments: arguments, #id: id})) as _i16.Future<T?>?);
  @override
  _i16.Future<T?>? pushNamedAndRemoveUntil<T>(String? routeName,
          {_i42.RoutePredicate? predicate, dynamic arguments, int? id}) =>
      (super.noSuchMethod(Invocation.method(#pushNamedAndRemoveUntil, [
        routeName
      ], {
        #predicate: predicate,
        #arguments: arguments,
        #id: id
      })) as _i16.Future<T?>?);
}
