// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGoZ8VfG0hplz66_pNCXutlgeMpkAVhQs',
    appId: '1:455580464649:web:a06de8f65706243ad6ead8',
    messagingSenderId: '455580464649',
    projectId: 'demoapp-912ed',
    authDomain: 'demoapp-912ed.firebaseapp.com',
    storageBucket: 'demoapp-912ed.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-slei5yiAIb9AQKbYMLWQr9wt4B33Yk0',
    appId: '1:455580464649:android:463910cffb5d0ef4d6ead8',
    messagingSenderId: '455580464649',
    projectId: 'demoapp-912ed',
    storageBucket: 'demoapp-912ed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEQWa5FSPt1CYIvS7FAuMuQYTFViSWDSo',
    appId: '1:455580464649:ios:05b7ab8d06fb98b6d6ead8',
    messagingSenderId: '455580464649',
    projectId: 'demoapp-912ed',
    storageBucket: 'demoapp-912ed.appspot.com',
    androidClientId: '455580464649-79bh7kgpakcdoc25g75b56nmhupu0n69.apps.googleusercontent.com',
    iosClientId: '455580464649-4ec34ssah18vlmv60ujssr4j6fcca8n9.apps.googleusercontent.com',
    iosBundleId: 'com.example.appbar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEQWa5FSPt1CYIvS7FAuMuQYTFViSWDSo',
    appId: '1:455580464649:ios:05b7ab8d06fb98b6d6ead8',
    messagingSenderId: '455580464649',
    projectId: 'demoapp-912ed',
    storageBucket: 'demoapp-912ed.appspot.com',
    androidClientId: '455580464649-79bh7kgpakcdoc25g75b56nmhupu0n69.apps.googleusercontent.com',
    iosClientId: '455580464649-4ec34ssah18vlmv60ujssr4j6fcca8n9.apps.googleusercontent.com',
    iosBundleId: 'com.example.appbar',
  );
}
