default_platform(:android)

platform :android do

  desc "Submit a new internal build to Google Play"
  lane :internal do 
  
    sh "flutter build appbundle --dart-define='DB_URL=$DB_URL' --dart-define='DB_PASSWORD=$DB_PASSWORD'"

    upload_to_play_store(
      track: 'internal',
      aab: '../build/app/outputs/bundle/release/app-release.aab',
      json_key_data: ENV['PLAY_STORE_CONFIG_JSON'],
      )
  end
end
